### PR TITLE
[Feature]: Allow using custom and on-demand models in Fireworks AI + update data to model_prices_and_context_window.json 

### PR DESCRIPTION
**Pull request by danielbichuetti**
## Title
Allow using custom and on-demand models in Fireworks AI, and also update cost map data to use full path.

## Relevant issues
There was a transformation that would change custom account/models from Fireworks model name into a wrong format. The check was shortened to allow using patterns like `accounts/danielbichuetti/models/{model_name}`.

When the feature was added, it used the accepted pattern "fireworks_ai/{model_name}" and when the cost map is checked it only uses  "fireworks_ai/accounts/fireworks/models/{model_name}". 
The cost map was updated to reflect this.

## Type
🆕 Feature
🐛 Bug Fix 

##Changes
Shortened transformation in utils.py to allow using custom and on-demand models.
Fixed model_prices_and_context_window.json to include Fireworks AI models by full name

### CODE REVIEW

**Comment by danielbichuetti** [comment]
@krrishdholakia Fixed to reflect the way cost map is checked.

**Comment by ghost** [comment]
> and when the cost map is checked
hey @danielbichuetti can you share an example of the error? 

maybe the better fix is to have the relevant function make the right mod

**Comment by danielbichuetti** [comment]
@krrishdholakia 

```
Router(
        model_list=[
            {
                "model_name": "firefunctionv2",
                "litellm_params": {  
                    "model": "fireworks_ai/firefunction-v2",
                },
            }
        ],
    )  
```

And when calling completion:

```
Looking up model=fireworks_ai/accounts/fireworks/models/firefunction-v2 in model_cost_map
Model=accounts/fireworks/models/firefunction-v2 for LLM Provider=fireworks_ai not found in completion cost map.
```

```
Request to litellm:
litellm.completion(api_key='...', model='fireworks_ai/firefunction-v2', ...


SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: ...

POST Request Sent from LiteLLM:
curl -X POST \
https://api.fireworks.ai/inference/v1/ \
-d '{'model': 'accounts/fireworks/models/firefunction-v2', ...
```

As per Fireworks AI, the correct way of referencing their models is the full path. I think it will be better to set a standard as there is not only that path.

So, the reference way of setting it is:

```
Router(
        model_list=[
            {
                "model_name": "firefunctionv2",
                "litellm_params": {  
                    "model": "fireworks_ai/accounts/fireworks/models/firefunction-v2",
                },
            }
        ],
    )  
```

The cost map checks correctly for both cases (it transforms the alias into the official). The main problem is that it can't handle both the scenarios right now because the cost map was added for the alias pattern (which in an engineering perspective is wrong).

The code that does the transformation is here https://github.com/BerriAI/litellm/blob/606466d5fc4a9ff7190efd48e15b1cb6a5adf4e4/litellm/utils.py#L4420-L4428

If the JSON is fixed, the official way will work and the alias one too.

As you can see here in the above code, people could have other formatted patterns. I think that it would be even better to convert the current transformation code:

```
curl \
  -H "Authorization: Bearer ${API_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"model": "accounts/<ACCOUNT_ID>/models/<MODEL_ID>", "prompt": "hello, the sky is"}' \
  https://api.fireworks.ai/inference/v1/completions
```

Maybe it should only check 'till "accounts/" because if someone with a custom model tries to use, it will repeat and make it impossible to use.

**Comment by danielbichuetti** [comment]
@krrishdholakia Just pinging about this to avoid getting lost in the PR flow

**Pull request merged**
