### PR TITLE
Tutorial for using LiteLLM within Gradio Chatbot Application

### PR DESCRIPTION
**Pull request by ZQ-Dev8**
Based on discussions with @krrishdholakia [here](https://github.com/BerriAI/litellm/discussions/631), adding tutorial for those who want to use LiteLLM to make their LLM interactions via Gradio prompt agnostic. Happy to modify tutorial as needed.

### CODE REVIEW

**Comment by ghost** [comment]
hey @dcruiz01 you need to add this to sidebar.js so it shows the link in the sidebar 

also do you have a twitter/linkedin? would love to give you a shoutout when we announce this on our changelog

**Comment by ZQ-Dev8** [comment]
Ah yes, thanks for the reply @krrishdholakia. I updated sidebars.js to include the tutorial. Let me know if you can't see it :)

For attribution, I added my twitter handle to the bottom of the tutorial (tried to keep the same format I saw on other tutorials in the docs): `Credits to [ZQ](https://x.com/ZQ), for this tutorial.`

**Comment by ghost** [comment]
lgtm!

**Comment by ghost** [comment]
Congrats on the merge @dcruiz01

**Pull request merged**
