### PR TITLE
Prompt formatting for Bedrock Titan models

### PR DESCRIPTION
**Pull request by ryanh-ai**
Added formatting for Bedrock Titan models, including support for custom formatter if included in config

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
legendary⚡️

**Comment by ghost** [comment]
Hey @canada4663 i missed this PR, and added titan formatting yesterday - https://github.com/BerriAI/litellm/commit/cb5a13ed49d33e19a6ed45570491508abfa42cc0

Can you let me know if that solves your problem? 

Should be live in the latest litellm version v`1.23.15`

**Comment by ryanh-ai** [comment]
will look - seem to recall there was something slightly diff than this, but I will dig in and find out.

**Comment by ghost** [comment]
here it is @canada4663 https://github.com/BerriAI/litellm/blob/58fb6b2b5924041880b9aca1a7f653653a3527a4/litellm/llms/prompt_templates/factory.py#L427

**Comment by ghost** [comment]
bump on this? @canada4663

**Comment by ishaan-jaff** [comment]
closing due to inactivity

**Pull request closed without merging**
