### PR TITLE
docs: add languages to code blocks

### PR DESCRIPTION
**Pull request by jordanbtucker**
This PR updates the docs by adding languages to code blocks that didn't have them so they look better on the docs site, and a few other minor issues I found along the way, including:

- Adds missing languages to several code blocks throughout the docs.
- Removes the language from one instance of a `` ```bash `` code block for consistency with the rest of the docs.
- Fixes a typo in `completion/stream.md`.
- Fixes a couple typos in `tutorials/huggingface_tutorial.md`
- Removes a `.DS_Store` file that was committed before `.gitignore` was updated.

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@jordanbtucker thanks for the awesome work on this !

**Comment by ishaan-jaff** [comment]
We'll announce this in our changelog today - if you have a twitter/linkedin you'd like us to shoutout, can you share that here?

**Comment by jordanbtucker** [comment]
No need for any shoutouts. I prefer to fly under the radar to be honest.

**Comment by ghost** [comment]
Sounds good - thank you for the help @jordanbtucker  ! We'd love to have you in our community https://discord.com/invite/wuPM9dRgDw

**Pull request merged**
