### PR TITLE
Always run all local_tests, even after the first failure

### PR DESCRIPTION
**Pull request by Manouchehri**
This should still report a failure at the end of the run, but this way, it won't bail out so early. Right now the `-x` causes pytest to stop running any of the other unit tests.

### CODE REVIEW

**Comment by Manouchehri** [comment]
I've been waiting to see if #4857 actually was fixed or not, but because of the `-x`, other unrelated unit test failures cause pytest to bail out too early IMO.

**Comment by ishaan-jaff** [comment]
We need the `-x` otherwise it just runs several LLM API calls on failed testing runs

**Comment by ishaan-jaff** [comment]
just retried #4857 for you on ci/cd

**Comment by Manouchehri** [comment]
Okay, thanks.

> it just runs several LLM API calls on failed testing runs

Is this a bad thing for cost reasons? I don't see the problem with trying all unit tests imo.

**Pull request closed without merging**
