### PR TITLE
add mixtral 8x22

### PR DESCRIPTION
**Pull request by themrzmaster**

### CODE REVIEW

**Review by ishaan-jaff — APPROVED** [review]
lgtm ! good to merge ? @themrzmaster

**Comment by themrzmaster** [comment]
@ishaan-jaff I am trying to run function callings on mistral and it does not work for any model. should it work?

**Comment by ishaan-jaff** [comment]
@themrzmaster what's the error you see ? what version are you on ?

**Comment by themrzmaster** [comment]
i am on latest. no error, just never function or tools on response

**Comment by ghost** [comment]
I'm able to see a function call: 

```
ModelResponse(id='f38064aec670423080c13c30d1e22abb', choices=[Choices(finish_reason='tool_calls', index=0, message=Message(content='', role='assistant', tool_calls=[ChatCompletionMessageToolCall(function=Function(arguments='{"location": "Boston, MA", "unit": "fahrenheit"}', name='get_current_weather'), id='C99NwVL56', type='function')]))], created=1713403007, model='mistral/mistral-large-latest', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=35, prompt_tokens=119, total_tokens=154))
```

My call: 

```python
from litellm import completion
import os

os.environ['MISTRAL_API_KEY'] = "my-api-key"

tools = [
  {
    "type": "function",
    "function": {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA",
          },
          "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
        },
        "required": ["location"],
      },
    }
  }
]
messages = [{"role": "user", "content": "What's the weather like in Boston today?"}]

response = completion(
    model="mistral/mistral-large-latest", 
  messages=messages,
  tools=tools,
  tool_choice="auto"
)
print(response)
```

**Comment by ishaan-jaff** [comment]
@themrzmaster can you check the RAW response from the model - see if the model is responding with a function call 
set litellm.set_verbose=True

**Comment by themrzmaster** [comment]
yeah, tried a minimal example and worked. maybe it just not good enought for me or i need better prompt. thanks for the work guys

**Comment by ghost** [comment]
> maybe it just not good enought for me

hey @themrzmaster do you mean litellm isn't good enough or the llm api? 

If litellm, how can we improve here?

**Comment by themrzmaster** [comment]
i mean the LLM! mistral function calling does not seems to work for long prompts.

**Pull request merged**
