### PR TITLE
Support SageMaker Endpoint Message API

### PR DESCRIPTION
**Pull request by xqun3**
## Title

Support SageMaker Endpoint Message API

## Type

🆕 New Feature

### CODE REVIEW

**Comment by xqun3** [comment]
这是来自QQ邮箱的自动回复邮件。您好~您发送的邮件我已收到。谢谢您的邮件~

**Comment by ghost** [comment]
hey @xqun3 can you give me steps to deploy a sagemaker model with the messages API? this will help me validate if this works as intended

**Comment by xqun3** [comment]
Hi @krrishdholakia, thanks for your quick reply, here is the sample code for deploying LLM on SageMaker Endpoint,https://github.com/aws-samples/llm_deploy_gcr/blob/main/sagemaker/deepseek_coder_6.7_instruct.ipynb

**Comment by xqun3** [comment]
Hey @krrishdholakia, have you tested the codes? What should i do to help you validate it?

**Comment by ishaan-jaff** [comment]
hi @xqun3 - we recently [refactored sagemaker to be purely async](https://github.com/BerriAI/litellm/pull/5237). I'll be picking up adding Message API tomorrow. Does that work ?

**Comment by xqun3** [comment]
> hi @xqun3 - we recently [refactored sagemaker to be purely async](https://github.com/BerriAI/litellm/pull/5237). I'll be picking up adding Message API tomorrow. Does that work ?

Nice work! I'll test it with my deployed model also. Thanks.

**Comment by xqun3** [comment]
@ishaan-jaff I have test it with my deployed model, and i have found if i use litellm to invoke model still generate not correctly. It seems litellm did not apply the chat-template correctly. Maybe i need to construct a chat-template?
image

And i have a question here, for those models on Hugging Face that have a chat template, why do we not directly apply them to litellm's message API instead of constructing a Prompt-factory ourselves?
```
prompt = "Hello"
messages = [
    {"role": "user", "content": prompt}
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
```

Additionally, SageMaker now supports the message API.

**Comment by ghost** [comment]
@xqun3 

> template, why do we not directly apply them to litellm's message API instead of constructing a Prompt-factory ourselves?

We do check this - https://github.com/BerriAI/litellm/blob/1765976ce0db8dd434876ed4833f103398dec998/litellm/llms/prompt_templates/factory.py#L382

Let me know how we can improve this

**Comment by ghost** [comment]
>  i have found if i use litellm to invoke model still generate not

I can see the issue in your screenshot is with deepseek coder, great! i'll test this out as well 

I believe your call is missing the huggingface base model name param - `hf_model_name` - https://docs.litellm.ai/docs/providers/aws_sagemaker#applying-prompt-templates

Which is how we know what prompt template to apply

**Comment by xqun3** [comment]
Hi @krrishdholakia Thanks for your reply! I added the hf_model_name in the call, but still not a correct output. So I checked the final prompt, found that part of the prompt template content is still missing. 
Below is the final prompt with litellm
image

Here is the transformers final prompt
image

**Comment by ghost** [comment]
able to repro - working on a fix

**Comment by xqun3** [comment]
Hi @krrishdholakia, Have we fixed the bug in this prompt template?

**Comment by xqun3** [comment]
Hi @krrishdholakia, thank you for your contribution and for fixing the previous bug. Your efforts are greatly appreciated. However, I've encountered another issue with the latest version. When [describe the steps to reproduce the bug], [explain the observed behavior]. I've attached a screenshot for reference.
image

If possible, could you please look into this new bug? I think it's might be caused by the iter_bytes func, I think it might be caused by the iter_bytes func. You could reference the following code to solve it:
```
import io
import json

class TokenIterator:
    def __init__(self, stream):
        self.byte_iterator = iter(stream)
        self.buffer = io.BytesIO()
        self.read_pos = 0

    def __iter__(self):
        return self

    def __next__(self):
        while True:
            self.buffer.seek(self.read_pos)
            line = self.buffer.readline()

            # print(line)
            if line and line[-1] == ord("\n"):
                self.read_pos += len(line)
                full_line = line[:-1].decode("utf-8")
                # print(full_line)
                line_data = json.loads(full_line.lstrip("data:").rstrip("/n"))
                return line_data["token"].get("text", "")
            chunk = next(self.byte_iterator)
            self.buffer.seek(0, io.SEEK_END)
            self.buffer.write(chunk["PayloadPart"]["Bytes"])


def get_realtime_response_stream(sagemaker_runtime, endpoint_name, payload):
    response_stream = sagemaker_runtime.invoke_endpoint_with_response_stream(
        EndpointName=endpoint_name,
        Body=json.dumps(payload),
        ContentType="application/json",
        CustomAttributes='accept_eula=false'
    )
    return response_stream
    
prompt = ""

parameters = {
        "max_new_tokens":1024, 
        "do_sample": True,
    }

payload = {
    "inputs":  prompt,
    "parameters": parameters,
    "stream": True ## <-- to have response stream.
}
response_stream = get_realtime_response_stream(smr_client, endpoint_name, payload)
# print_response_stream(response_stream)
for token in TokenIterator(response_stream["Body"]):
    # pass
    print(token, end="", flush=True)
```
Full sample codes could find in https://github.com/aws-samples/llm_deploy_gcr/blob/main/sagemaker/deepseek_coder_6.7_instruct.ipynb.

Thank you for your time and attention to this matter again, and also thank you for supporting SageMaker. Looking forward to your feedback and continued improvements to the project.

**Comment by xqun3** [comment]
Test messages：
```
system_prompt = """You are a highly skilled translator with expertise in many languages. Your task is to identify the language of the text I provide and accurately translate it into the specified target language while preserving the meaning, tone, and nuance of the original text. Please maintain proper grammar, spelling, and punctuation in the translated version."""
prompt = """I made a bookmark!:)
 I redrew the first ever Genshin impact fanart I ever made as well❤️ If it guys want the bookmark yourself, feel free to tell me, and I ll give you a scan❤️ Otherwise I hope you all have a great evening❤️ (it s evening for me lol)
Translate to Chinese"""
messages = [{"content": system_prompt, "role": "system"}, { "content": prompt,"role": "user"}]
```

**Comment by ghost** [comment]
@xqun3 could you file this as a separate issue? will be easier to track

**Pull request closed without merging**
