### PR TITLE
Update deepinfra models

### PR DESCRIPTION
**Pull request by ichernev**
We added a few models and lowered the pricing on some of the models.

### CODE REVIEW

**Review by ishaan-jaff — APPROVED** [review]
lgtm !

**Comment by ishaan-jaff** [comment]
good to merge @ichernev ?

**Comment by ichernev** [comment]
@ishaan-jaff thanks for the quick turnaround. Yes, this is way more accurate than before, I'll do another one to increase ctx on a few models, but the current state is conservatively accurate.

**Comment by ghost** [comment]
@ichernev do you have a public api we can just pull this information from? 

Something like this - https://openrouter.ai/api/v1/models

**Comment by ichernev** [comment]
@krrishdholakia we almost do, I wrote a script to generate the data. The only thing we're missing is max context size. Do you have a script that updates the list?

**Comment by ghost** [comment]
Not yet - thinking about it 

If you can share the script, that'd be great too!

**Comment by ichernev** [comment]
> If you can share the script, that'd be great too!

We'll add context length in the returned metadata for each model, then I'll tweak the script and share it.

**Comment by ghost** [comment]
@ichernev in your context, is context length the max input token or max output token or max input + max output token?

**Pull request merged**
