### PR TITLE
Add return type annotations to util types

### PR DESCRIPTION
**Pull request by guitard0g**
## Title

When using litellm in another project (with strict mypy) I'm noticing a lot of type errors like:
```
error: Call to untyped function "Delta" in typed context  [no-untyped-call]
```

## Type

🐛 Bug Fix

## Changes

Add `-> None` to `__init__` functions on util types

### CODE REVIEW

**Review by helloworld — APPROVED** [review]

**Review by quentindnorris — APPROVED** [review]

**Review by ishaan-jaff — APPROVED** [review]

**Comment by ishaan-jaff** [comment]
curious - how do you use litellm today @quentindnorris @guitard0g @helloworld ?

**Comment by helloworld** [comment]
@ishaan-jaff just as unified sdk for ~4 apis. Do you know roughly when this PR will go out in a release?

**Comment by ishaan-jaff** [comment]
By EOD @helloworld

**Comment by helloworld** [comment]
Thank you!

**Comment by ishaan-jaff** [comment]
Looks like this broke our type checking on ci/cd

```
types/utils.py:339: error: Incompatible types in assignment (expression has type "Any | None", variable has type "FunctionCall")  [assignment]
types/utils.py:350: error: Incompatible types in assignment (expression has type "Any | None", variable has type "list[ChatCompletionDeltaToolCall]")  [assignment]
types/utils.py:677: error: Unexpected keyword argument "model" for "__init__" of "BaseModel"  [call-arg]
types/utils.py:677: error: Unexpected keyword argument "object" for "__init__" of "BaseModel"  [call-arg]
types/utils.py:677: error: Unexpected keyword argument "data" for "__init__" of "BaseModel"  [call-arg]
types/utils.py:677: error: Unexpected keyword argument "usage" for "__init__" of "BaseModel"  [call-arg]
types/utils.py:829: error: Unexpected keyword argument "id" for "__init__" of "BaseModel"  [call-arg]
types/utils.py:829: error: Unexpected keyword argument "object" for "__init__" of "BaseModel"  [call-arg]
```

**Comment by ishaan-jaff** [comment]
can you look into this https://app.circleci.com/pipelines/github/BerriAI/litellm/11731/workflows/bc7495ba-cd16-46c3-ba95-8104e41f5f34/jobs/27598 

@guitard0g @helloworld

**Comment by ishaan-jaff** [comment]
It looks like this change led to failing linting 

```
python3 -m mypy . --ignore-missing-imports
```

**Comment by ishaan-jaff** [comment]
We're happy to merge in this change but it's currently blocking all commits to main since it fails our linting check 

**Plan forward:**
1. Revert this PR done here: https://github.com/BerriAI/litellm/pull/4420/commits/faef56fe696ff3eba0fcff80c3270534b2887648 
2. @guitard0g @helloworld @quentindnorris make a new PR with fixes to the linting errors caused by this PR + send a screenshot of `python3 -m mypy . --ignore-missing-imports` working locally in the `litellm/litellm` directory 
3. once we see a screenshot of this working - happy to merge again

**Comment by guitard0g** [comment]
@ishaan-jaff Ah sorry for the trouble! Will make a new PR and make sure it doesn't hit this issue

**Pull request merged**
