### PR TITLE
(azure): Enable stream_options for Azure OpenAI

### LINKED ISSUE #5632: [Feature]: Always send `"stream_options": {"include_usage": true}` when `"stream": true`
### The Feature

When `"stream": true` is set for OpenAI and Azure OpenAI requests, it would be nice if `"stream_options": {"include_usage": true}` was always sent too (even if the user's request did not include it).

### Motivation, pitch

This would ensure always getting an perfectly accurate token count from upstream. It's also useful for users who have another proxy/gateway in front of LiteLLM (like Cloudflare AI Gateway).

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

### PR DESCRIPTION
**Pull request by Manouchehri**
Resolve #5632. Should be covered by existing unit tests.

Tested locally using `2024-09-01-preview`, but should also work with `2024-08-01-preview` too.

### CODE REVIEW

**Comment by Manouchehri** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/30821

https://github.com/YunsongB/azure-rest-api-specs/blob/698377edf035102b463624f3df2ff0a2043d8d1a/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-09-01-preview/inference.yaml

`stream_options` is officially supported in `2024-09-01-preview`.

**Comment by ghost** [comment]
Hey @Manouchehri 

> Should be covered by existing unit tests.


Which test do you believe covers this scenario?

**Comment by ghost** [comment]
> 2024-09-01-preview

Oh - is this supported across all models?

**Comment by ghost** [comment]
If you can share a screenshot of this working as expected, that should be good enough to merge to a dev branch for testing

**Comment by Manouchehri** [comment]
Yes, supported on all models.

**Comment by Manouchehri** [comment]
image

**Pull request merged**
