### PR TITLE
[Bug Fix] Use OpenAI Tool Response Spec When Converting To Gemini/VertexAI Tool Response

### PR DESCRIPTION
**Pull request by andrewmjc**
## Use OpenAI Tool Response Spec When Converting To Gemini/VertexAI Message History

OpenAI tool response messages no longer support the "name" field as per:
https://platform.openai.com/docs/api-reference/chat/create

This causes breaking incompatibilities with different OpenAI wrappers who strictly follow the OpenAI API doc (Langchains ChatOpenAI wrapper in particular) when trying to use LiteLLM with vertex AI chat models (Gemini-1.5-flash will return a 400 if the name field is empty)

This PR introduces a new way to get the "name" field required for gemini tool calling by matching the tool call id with the last tool called with a matching id, and pulling the tool name from there

## Type

🐛 Bug Fix
🧹 Refactoring

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

### CODE REVIEW

**Comment by ghost** [comment]
hey @andrewmjc can you share an example to trigger the issue? 

Would also be great if you could add a passing test (maybe with the same example) to ci/cd so we don't have future regressions here

here's the place to add it - https://github.com/BerriAI/litellm/blob/612af8f5be6435cbb1fc4cf151c02fbd02a00f2d/litellm/tests/test_amazing_vertex_completion.py#L4

**Comment by ghost** [comment]
is it this? 

Screenshot 2024-07-02 at 4 39 59 PM

**Comment by andrewmjc** [comment]
> https://platform.openai.com/docs/api-reference/chat/create

image
It's this message type ^. The current gemini conversion method expects a field "name" on message type "tool", but libraries like Langchain and other OpenAI wrappers do not send this field.

I can write a quick regression test for this tomorrow morning MST :)

**Comment by andrewmjc** [comment]
@krrishdholakia Unit test done! Lmk if you have any questions / corrections that need to be implemented. On a side note, I've also noticed some strange behaviour with this method (_gemini_convert_messages_with_history) where empty assistant messages will cause vertex to 400 due to the alternation of user/assistant being broken. I think this is a bug. I can fix this in a separate PR if you would like.

**Comment by ghost** [comment]
planning on merging this tonight

**Comment by ghost** [comment]
just realized this would fail calls from the `vertex_ai_beta/` route. 

@andrewmjc  can you update it here too - https://github.com/BerriAI/litellm/blob/e7122772d11965922ff6068c0d53c059c8aaf680/litellm/llms/vertex_httpx.py#L1032

**Comment by andrewmjc** [comment]
> just realized this would fail calls from the `vertex_ai_beta/` route.
> 
> @andrewmjc can you update it here too -
> 
> https://github.com/BerriAI/litellm/blob/e7122772d11965922ff6068c0d53c059c8aaf680/litellm/llms/vertex_httpx.py#L1032

Pretty sure that vertex_httpx uses the same updated method from vertex_ai, (_gemini_convert_messages_with_history) so it should be good to go now

**Pull request merged**
