### PR TITLE
Create GitHub Action to automatically build docker images

### PR DESCRIPTION
**Pull request by coconut49**
# Description
The purpose of this PR is to build a Docker image of LiteLLM Proxy Server via GitHub Action, so that we don't need to clone the entire repository and build the image ourselves when we need to use it. This makes it easier to deploy.

The main change to the code is to allow the `user_config_path` to be obtained via `LITELLM_CONFIG_PATH` to fit the container environment.

All other changes are code formatting and can be ignored.

# Test
```shell
docker run -dti -v ./secrets_template.toml:/litellm.secrets.toml -p 8000:8000 ghcr.io/coconut49/litellm:main
```

Screenshot 2023-10-18 at 14 28 09

https://github.com/coconut49/litellm/pkgs/container/litellm

image

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@coconut49 this looks like an amazing PR but I see no files changed

**Comment by coconut49** [comment]
> @coconut49 this looks like an amazing PR but I see no files changed

Hi @ishaan-jaff, I re-pushed the code and I don't know why pull bot cleared my changes.
image

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia this builds on your work for the proxy

**Comment by ghost** [comment]
Hey @coconut49 can we discuss this PR over a call, I'd like to understand this use-case/problem a bit more: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by SlapDrone** [comment]
Was just thinking this would be a welcome addition yesterday, nice work. Is it merged though? I see no files changed either.

**Comment by ghost** [comment]
@coconut49 did you pull the PR? 

not sure i understand what happened. 


@SlapDrone are you currently using the docker image?

**Comment by coconut49** [comment]
Hi @krrishdholakia I submitted the code yesterday, but the bot pulled it before the merge, leading to a force push that overwrote my relevant changes. I am investigating.

Screenshot 2023-10-20 at 12 09 20

**Comment by coconut49** [comment]
Sorry, I uninstalled the `pull` bot. I will create another PR to replicate the changes.

**Comment by coconut49** [comment]
Hi @krrishdholakia I have submitted the same code changes again in another PR. Could you please review? https://github.com/BerriAI/litellm/pull/655. Thank you.

**Comment by SlapDrone** [comment]
> @coconut49 did you pull the PR?
> 
> not sure i understand what happened.
> 
> @SlapDrone are you currently using the docker image?

Currently I have a Makefile that clones the repo locally, then builds and tags the docker image, then deletes the local repo. Having this image published natively on ghcr (as @coconut49 has implemented) would be really convenient! :)

**Comment by ghost** [comment]
@SlapDrone i initially built the proxy to solve a user problem for translating openai / non-openai calls locally. 

I'm trying to understand why people are using it in prod. Is there any way I can reach out to learn more about your use-case ?

My number is: +17708783016 (works for sms/imessage/whatsapp)
Discord: Krrish#8748
Email: krrish@berri.ai

**Pull request merged**
