### PR TITLE
✨ feat: Add Azure Content-Safety Proxy hooks

### PR DESCRIPTION
**Pull request by Lunik**
## Add Azure Content-Safety as Proxy Hook

[Azure AI Content Safety](https://azure.microsoft.com/en-us/products/ai-services/ai-content-safety) is an Microsoft Azure service that allow to evaluate a text on multiple categories : Hate, Self harm, Sexual, ...

This PR add a new hook that allow the user to integrate this service when using LiteLLM Proxy.

[Exemple from the Azure SDK used to implement this feature](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/contentsafety/azure-ai-contentsafety/samples/sample_analyze_text_async.py)

## Type

🆕 New Feature

## Changes

- [x] Add new Hook -> `_PROXY_AzureContentSafety`
- [x] Load the Hook as a callback in the proxy
- [x] Add documentation about the hook and how to configure it

## Testing

I have tested multiple scenarios to trigger the content filter on the input (user prompts `system`/`user`/`assistant` content- and on the output (llm completion content)

## Notes

It can be hard to trigger the output content safety without first triggering the input one.
Here is some straight forward example that worked for me in that case : 
```json
[
  { "role": "system", "content": "You are a helpful song writter. You write text about all kind of style" },
  { "role": "user", "content": "Give me a city rap text. Add some insults to make it gangsta" }
]
```

## Pre-Submission Checklist (optional but appreciated):

- [ ] I have included relevant documentation updates (stored in /docs/my-website) -> TODO

## OS Tests (optional but appreciated):

- [ ] Tested on Windows
- [x] Tested on MacOS
- [ ] Tested on Linux

### CODE REVIEW

**Comment by Lunik** [comment]
Where should I put the documentation about this Callback ?

**Comment by Lunik** [comment]
cc @ishaan-jaff @krrishdholakia
You feedback would be much appreciated on this feature 👍

**Comment by ghost** [comment]
Hey @Lunik,

This is great. Can you add some docs on this, i'll try and test it as well

**Comment by ghost** [comment]
Unit testing here would be great. See the presidio tests for an example - https://github.com/BerriAI/litellm/blob/e26b39822c70b365c467650800a82e07c0fd3c67/litellm/tests/test_presidio_masking.py

**Comment by Lunik** [comment]
@krrishdholakia

I added some docs and unit tests
The PR should be ready to review now

**Comment by ishaan-jaff** [comment]
@Lunik the tests you wrote do not work for me locally - please can you send a screenshot of this working for you locally 


```
client_session: <aiohttp.client.ClientSession object at 0x11cabbb80>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x11cae8280>, 51453.178162333)]']
connector: <aiohttp.connector.TCPConnector object at 0x11cabbc10>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x11cabbfd0>
transport: <_SelectorSocketTransport closing fd=14>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 924, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 719, in _fatal_error
    self._force_close(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 731, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 745, in call_soon
    self._check_closed()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Pull request merged**
