### PR TITLE
[bugfix] Prevent value error if model returns empty completion

### PR DESCRIPTION
**Pull request by dvruette**
Due to the validation in `OpenAIObject`, setting `model_response["choices"][0]["message"]["content"]` to the empty string leads to a value error. The field must be `None` or a non-empty string.

This is triggered if the API model (for whatever reason) generates the empty string, i.e. generates EOS as the first token.
Since the `content` field is `None` by default, we can just leave it as-is if that happens.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @dvruette - thanks for raising this issue. I think we'll need to change this in more than just `main.py`, including the individual model files (e.g. anthropic.py, etc.). 

Can you add that as well? if not I can take a look at this later.

**Comment by dvruette** [comment]
I can probably take a look tmrw or maybe the weekend. Fell free to take over from here though, it will likely be very quick esp. if you already know which files are affected.

**Comment by dvruette** [comment]
Ok I've fixed every occurrence I was able to find. If there's any `ModelResponse` that's not called `model_response`, I might have missed it.

**Comment by ghost** [comment]
Great thanks

**Comment by ghost** [comment]
Reviewing this now - is there a way to repro this scenario? would be helpful for our testing @dvruette

**Comment by dvruette** [comment]
Hmm I just ran into it when gpt-3.5-turbo-instruct returned an empty response. Don’t have the prompt I used on hand, but maybe you can find one to make it generate EOS immediately. For other models you’d probably have to simulate a response, don’t see an easy way otherwise.

Using stopping tokens might also help ellicit an empty completion.

**Comment by ghost** [comment]
Merge conflicts blocking - looking into this now.

**Comment by ghost** [comment]
Found some bugs + had to make fixes to make sure usage calculation still worked. Pushed it here - af2fd0e0de5b114a6d7a0eb4cbb2fa7d712b2cae. 

@dvruette

**Comment by dvruette** [comment]
Awesome, thanks for getting this fixed!

**Comment by ghost** [comment]
Do you have a linkedin would love to give a shoutout when we publish the changelog @dvruette

**Comment by dvruette** [comment]
Sure, you can find me as Dimitri von Rütte

**Pull request closed without merging**
