### PR TITLE
Fix: Update gpt-4o costs to those of gpt-4o-2024-08-06

### LINKED ISSUE #6713: [Bug]: Incorrect max_tokens for gpt-4o
### What happened?

`gpt-4o` should be an alias for `gpt-4o-2024-08-06` (see [openai docs](https://platform.openai.com/docs/models/o1#gpt-4o)).

However, the current `max_tokens` in the config is just `4096`!

https://github.com/BerriAI/litellm/blob/9160d80fa54f964eeaf0abe40475666f3f88fb3a/model_prices_and_context_window.json#L17

Or to check with the python SDK:

```python
>>> from litellm.utils import get_max_tokens
>>> get_max_tokens(model="gpt-4o")
4096
>>> get_max_tokens(model="gpt-4o-2024-08-06")
16384
```

I'll open a fix for this in a second

### Relevant log output

_No response_

### Twitter / LinkedIn details

@klieret / https://www.linkedin.com/in/kilian-lieret-0b0667104/

### PR DESCRIPTION
**Pull request by klieret**
Fixes #6713

### CODE REVIEW

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
I need a link to docs or a source

**Comment by klieret** [comment]
https://platform.openai.com/docs/models/o1#gpt-4o : gpt-4o should be an alias for gpt-4o-2024-08-06

**Comment by klieret** [comment]
The costs can be found here: https://openai.com/api/pricing/

**Comment by klieret** [comment]
But concretely I simply copied the config for `gpt-4o-2024-08-06` of the same file to the `gpt-4o` config and then double checked with the two sources

**Review by ishaan-jaff — APPROVED** [review]
lgtm

**Pull request merged**
