### PR TITLE
Update ollama.py for image handling

### LINKED ISSUE #1427: [Bug]: Base64 Ollama Vision
### What happened?

Hi all, I noticed a problem. In the OpenAI documentation for Vision, when loading images, the image_url format is different

https://platform.openai.com/docs/guides/vision/uploading-base-64-encoded-images

They add to base64 mime type. For example: image/jpeg;base64,<base64>
  
At the same time in LiteLLM documentation in the Vision example it is just base64:

https://docs.litellm.ai/docs/providers/ollama#ollama-vision-models

As a result:

My client compatible with OpenAI API sends correctly: image/jpeg;base64,<base64>
But LiteLLM expects just base64, and cannot decode image_url

### Relevant log output

```shell
{"error":"illegal base64 data at input byte 10"}

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 210, in acompletion
    response = await init_response
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/ollama.py", line 328, in ollama_acompletion
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/ollama.py", line 281, in ollama_acompletion
    raise OllamaError(status_code=resp.status, message=text)
litellm.llms.ollama.OllamaError: {"error":"illegal base64 data at input byte 10"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1489, in chat_completion
    response = await litellm.acompletion(**data)
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2365, in wrapper_async
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2257, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 227, in acompletion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6605, in exception_type
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6573, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: {"error":"illegal base64 data at input byte 10"}
```

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by rick-github**
ollama wants plain base64 jpeg/png images, and some clients send dataURI and/or webp.  Remove prefixes and convert all non-jpeg/png images to jpeg.

Fixes https://github.com/BerriAI/litellm/issues/1427, https://github.com/BerriAI/litellm/issues/2661

### CODE REVIEW

**Comment by jakobdylanc** [comment]
I think this implementation is flawed since you're doing image.split(",") for the comma you're expecting at the beginning, but the base64 encoded data itself can also contain commas.

**Comment by rick-github** [comment]
Hi Jakob,

base64 encoded data shouldn't contain commas, it's restricted to the
character set [A-Za-z0-9/+=]: https://en.wikipedia.org/wiki/Base64

**Comment by jakobdylanc** [comment]
Yeah realized that afterwards and deleted my comment :) sorry about that. I was confusing "," with "/"

**Comment by ghost** [comment]
@rick-github thanks for this - can you add a test with a mock call for this to `test_completions.py` we've had a couple regressions with merged ollama pr's recently.

place to add test - https://github.com/BerriAI/litellm/blob/b29994a0ae0fc496f182167a8c8d4a1b689712fd/litellm/tests/test_completion.py#L4

Example of a mock call - https://github.com/BerriAI/litellm/blob/b29994a0ae0fc496f182167a8c8d4a1b689712fd/litellm/tests/test_completion.py#L1314

**Comment by rick-github** [comment]
Done.

**Comment by ghost** [comment]
Thanks @rick-github just share a screenshot of it passing testing for your test + tests in `test_ollama.py` and we should be good to merge! 

Thank you again for your awesome work here

**Comment by rick-github** [comment]
Screenshot from 2024-05-28 18-01-24

**Comment by rick-github** [comment]
Screenshot from 2024-05-28 18-06-23

**Comment by ghost** [comment]
LGTM!

**Pull request merged**
