### PR TITLE
Litellm triton chatcompletion support - Resubmit of #3895

### PR DESCRIPTION
**Pull request by giritatavarty-8451**
## Title

Triton Changes for enabling chatcompletion support for Triton- trtllm 

## Relevant issues
python3 -m mypy litellm/llms/triton.py --ignore-missing-imports  is clean now .

## Type

🆕 New Feature

## Changes

mypy error fixes.

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

- embedding endpoint and chatcompletion are working fine.

### CODE REVIEW

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
is streaming supported with this PR ? 

We promise users `streaming` support when we onboard `completion` for any new provide

**Comment by giritatavarty-8451** [comment]
Ishaan,
Streaming is not supported or tested as of now, but it is on our roadmap .
Thank you

**Comment by ishaan-jaff** [comment]
I'm requesting you to add streaming support on this PR @giritatavarty-8451, will you not be able to do that on this PR ?

**Comment by giritatavarty-8451** [comment]
Will be 2-3 of weeks of work, to deploy a streaming enabled model  in triton and develop  & test streaming plugin. Your call.

**Comment by ishaan-jaff** [comment]
planning on merging this today @giritatavarty-8451 sorry for the delay

**Comment by landscapepainter** [comment]
Hi @giritatavarty-8451 @ishaan-jaff, was wondering if there's any update on this PR? Is it planned to be added some time soon? Thanks for the amazing work by the way!

**Comment by sophialoris-8451** [comment]
Hi @ishaan-jaff. I'm picking up this PR from Giri. I've pushed changes to his fork to support streaming and enable async completions. Let me know if there are any other changes you need. Thanks!

**Comment by ishaan-jaff** [comment]
hi @sophialoris-8451 could you send a screenshot of 
- acompletion working 
- acompletion with streaming working for you 

happy to merge after that

**Comment by sophialoris-8451** [comment]
Hi @ishaan-jaff. I've sent you screenshots in our email chain. Thanks!

**Pull request merged**
