### PR TITLE
fix(caching.py): pass kwargs to redis cache. Fixes #2050

### LINKED ISSUE #2050: Redis cache creation not working
I get the error below with the latest version. It used to work with 1.17

litellm.cache = Cache(type="redis", host='redis-xxxxxxxxredislabs.com', port=11912, password='xxxxxxxxxxx')

ValueError: Either 'host' or 'url' must be specified for redis.

Thanks,
Ravi.

### PR DESCRIPTION
**Pull request by stephenleo**
Fixes #2050 by passing the kwargs to the cache

### CODE REVIEW

**Comment by ghost** [comment]
Hey @stephenleo this is a good PR - but how would it close https://github.com/BerriAI/litellm/issues/2050? 

That doesn't seem specific to async caching

**Comment by stephenleo** [comment]
Hey @krrishdholakia, the redis_kwargs don't seem to be passed to the redis client right now. Hence the client throws an error while initialising as mentioned in #2050  
This PR passes the kwargs to the redis client which fixed the issue for me.

**Comment by ishaan-jaff** [comment]
@stephenleo how can I repro the bug you were seeing ? It will help to verify the fix

**Comment by stephenleo** [comment]
@ishaan-jaff i think the issue is fixed on the latest version. Will close this PR

**Pull request closed without merging**
