### PR TITLE
Fix TypeError in Exception mapping

### LINKED ISSUE #246: argument of type <ERROR> is not iterable
What's the problem? (if there are multiple - list as bullet points)

- LiteLLM raises `TypeError: argument of type <ERROR> is not iterable` instead of original error. 
For example, `argument of type 'AuthenticationError' is not iterable`
- Currently OpenAI for sure, others not tested

### PR DESCRIPTION
**Pull request by yujonglee**
Resolves #246

### CODE REVIEW

**Comment by yujonglee** [comment]
Actually it is not a right fix. Working on it.

**Comment by yujonglee** [comment]
@krrishdholakia  @ishaan-jaff  Seems like test in CI was in broken state.  There are many errors like `keyerror: 'INFISICAL_TOKEN'`

**Comment by ghost** [comment]
I believe that's b/c circle ci doesn't instantiate our .env's for pr's. Need a better solution out here.

**Comment by ghost** [comment]
just merged it so it can run through our circle ci testing, will revert it in case of errors. Will also need to bump the pyproject.toml version number so it can get published on pypi - i can take care of that.

**Comment by ghost** [comment]
looks like it worked. I'll bump the version so it can get published to pypi. Thanks for the PR @yujonglee

**Pull request merged**
