### PR TITLE
Remove dockerfile port override

### PR DESCRIPTION
**Pull request by nqngo**
This PR removes the port 4000 override from the project Dockerfiles. The default Uvicorn webapp for the LiteLLM proxy runs at port 8000, codified in:
https://docs.litellm.ai/docs/proxy/cli#--port
https://github.com/BerriAI/litellm/blob/688b903d195bd0c33d87617f2e899069c136993b/litellm/proxy/proxy_cli.py#L57

The override causes a bit of confusion when reading the Dockerfile as port 8000 is clearly intended to be the default. Since I am not too familiar with the project, I did not change the port override as specified in the CircleCI testing. If it is intended that we move permanently to port 8000, it is best that the project maintainer remedy that as well.

# How to reproduce

Use this `docker-compose.yml`:
```
name: litellm
services:
  litellm:
    container_name: litellm-proxy
    image: ghcr.io/berriai/litellm:main-v1.29.1
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: "--num_workers $LITELLM_WORKERS_NUM"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
````

`docker ps` shows unnecessary port 4000:
```
❯ docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED          STATUS         PORTS                                                 NAMES
6ffee5bdfe42   ghcr.io/berriai/litellm:main-v1.29.1   "litellm --num_workers…"   10 seconds ago   Up 9 seconds   4000/tcp, 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   litellm-proxy
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
This would be a breaking change for everyone using LiteLLM in production, We cannot switch the default Dockerfile port from 4000 to 8000

**Comment by ishaan-jaff** [comment]
Perhaps the right thing to do is to default the litellm cli tool to default start on 4000

**Comment by ishaan-jaff** [comment]
@nqngo can we hop on a quick call to better discuss this - happy to come to a resolution: link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-03

**Comment by nqngo** [comment]
> This would be a breaking change for everyone using LiteLLM in production, We cannot switch the default Dockerfile port from 4000 to 8000

> Perhaps the right thing to do is to default the litellm cli tool to default start on 4000

> @nqngo can we hop on a quick call to better discuss this - happy to come to a resolution: link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-03

If that is the case, happy to close this issue and reopen another one where we move everything to port 4000. Having a Dockerfile override vs the default behaviour is odd. Happy to raise an issue to discuss this further, let's take this to Github Issues.

**Comment by ishaan-jaff** [comment]
> reopen another one where we move everything to port 4000

This is a better approach

**Comment by nqngo** [comment]
Close pending discussion on https://github.com/BerriAI/litellm/issues/2366

**Pull request closed without merging**
