### PR TITLE
usage-based-routing-rate-limit-fix: get key is differs from set key in the cache

### PR DESCRIPTION
**Pull request by sumanth13131**
The get key differs from the set key in the cache.

Example:
Set key:=  `openai/gpt-3.5-turbo-0301:rpm:14-47`
Get key:=  `gpt-3.5-turbo-0301-ModelID-gpt-3.5-turbo-0301:rpm:14-47`

### CODE REVIEW

**Comment by ghost** [comment]
Hey @sumanth13131 i think this issue is relevant - https://github.com/BerriAI/litellm/issues/1069

We're planning on moving away from the stringified model id to the unique id's generated in `set_model_list()` 

A big motivation is how much harder it is to debug with the modelid as part of the model name. 

Your PR touches ModelID as well. Can we merge the efforts here? 

Here's the relevant model id code - https://github.com/BerriAI/litellm/blob/1b942568897a48f014fa44618ec3ce54d7570a46/litellm/router.py#L890

**Comment by ishaan-jaff** [comment]
FYI, we no longer use XXX-model-id so this is not required:

```python
original_model_string = item["litellm_params"]["model"]
# Find the index of "ModelID" in the string
index_of_model_id = original_model_string.find("-ModelID")
# Remove everything after "-ModelID" if it exists
if index_of_model_id != -1:
    deployment_name = original_model_string[:index_of_model_id]
else:
    deployment_name = original_model_string
```

**Comment by sumanth13131** [comment]
> FYI, we no longer use XXX-model-id so this is not required:
> 
> ```python
> original_model_string = item["litellm_params"]["model"]
> # Find the index of "ModelID" in the string
> index_of_model_id = original_model_string.find("-ModelID")
> # Remove everything after "-ModelID" if it exists
> if index_of_model_id != -1:
>     deployment_name = original_model_string[:index_of_model_id]
> else:
>     deployment_name = original_model_string
> ```

**Comment by sumanth13131** [comment]
@krrishdholakia, @ishaan-jaff  Closing The PR Will raise New Pull Request

**Pull request closed without merging**
