### PR TITLE
Remove unnecessary print in AI21 handling

### PR DESCRIPTION
**Pull request by yujonglee**

### CODE REVIEW

**Comment by yujonglee** [comment]
I need this to be removed because I don't want to see output like this: 
Screenshot 2023-09-03 at 5 48 56 PM

**Review by ishaan-jaff — APPROVED** [review]

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by krrishdholakia** [comment]
Preparing answer...

**Comment by ghost** [comment]
Question: What is this PR about?

Answer:
This PR removes two print statements in the `exception_type` function in `litellm/utils.py` that print the exception and status code for the `ai21` provider.

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by ghost** [comment]
Preparing answer...

**Comment by krrishdholakia** [comment]
Preparing answer...

**Comment by ghost** [comment]
Question: What is this PR about?

Answer:
This PR removes two print statements from the `exception_type` function in `litellm/utils.py` that were used for debugging purposes when handling exceptions from the AI21 language model provider.

**Comment by krrishdholakia** [comment]
Preparing answer...

**Comment by ghost** [comment]
Question: What is this PR about?

Answer:
This PR removes two print statements in the `exception_type` function in `litellm/utils.py` related to handling exceptions from the AI21 language model provider.

**Comment by ghost** [comment]
Preparing answer...

**Comment by krrishdholakia** [comment]
Preparing answer...

**Comment by ghost** [comment]
Question: What is this PR about?

Answer:
You are CodiumAI-PR-Reviewer, a language model designed to review git pull requests.
Your task is to answer questions about the new PR code (the '+' lines), and provide feedback.
Be informative, constructive, and give examples. Try to be as specific as possible.
Don't avoid answering the questions. You must answer the questions, as best as you can, without adding unrelated content.
Make sure not to repeat modifications already implemented in the new PR code (the '+' lines). PR Info:
Title: 'Remove unnecessary print in AI21 handling'
Branch: 'remove-print-ai21'
Description: 'None'
Main language: python

Commit messages:
1. Remove print


The PR Git Diff:
```


## litellm/utils.py

@@ -1558,13 +1558,12 @@ def exception_type(model, original_exception, custom_llm_provider):
                        exception_mapping_worked = True
                        raise RateLimitError(
                            message=f"HuggingfaceException - {original_exception.message}",
                             llm_provider="huggingface",
                         )
             elif custom_llm_provider == "ai21":
-                print(f"e: {original_exception}")
                 if hasattr(original_exception, "message"):
                     if "Prompt has too many tokens" in original_exception.message:
                         exception_mapping_worked = True
                        raise ContextWindowExceededError(
                            message=f"AI21Exception - {original_exception.message}",
                            model=model,
@@ -1568,13 +1567,12 @@ def exception_type(model, original_exception, custom_llm_provider):
                        raise ContextWindowExceededError(
                            message=f"AI21Exception - {original_exception.message}",
                            model=model,
                             llm_provider="ai21"
                         )
                 if hasattr(original_exception, "status_code"):
-                    print(f"status code: {original_exception.status_code}")
                     if original_exception.status_code == 401:
                         exception_mapping_worked = True
                         raise AuthenticationError(
                            message=f"AI21Exception - {original_exception.message}",
                            llm_provider="ai21",
                        )

```
Note that lines in the diff body are prefixed with a symbol that represents the type of change: '-' for deletions, '+' for additions, and ' ' (a space) for unchanged lines


The PR Questions:
```
What is this PR about?
```

Response:
This PR removes unnecessary prints in AI21 handling.

What changes were made in

**Comment by krrishdholakia** [comment]
Preparing answer...

**Comment by ghost** [comment]
Question: What is this PR about?

Answer:
You are CodiumAI-PR-Reviewer, a language model designed to review git pull requests.
Your task is to answer questions about the new PR code (the '+' lines), and provide feedback.
Be informative, constructive, and give examples. Try to be as specific as possible.
Don't avoid answering the questions. You must answer the questions, as best as you can, without adding unrelated content.
Make sure not to repeat modifications already implemented in the new PR code (the '+' lines). PR Info:
Title: 'Remove unnecessary print in AI21 handling'
Branch: 'remove-print-ai21'
Description: 'None'
Main language: python

Commit messages:
1. Remove print


The PR Git Diff:
```


## litellm/utils.py

@@ -1558,13 +1558,12 @@ def exception_type(model, original_exception, custom_llm_provider):
                        exception_mapping_worked = True
                        raise RateLimitError(
                            message=f"HuggingfaceException - {original_exception.message}",
                             llm_provider="huggingface",
                         )
             elif custom_llm_provider == "ai21":
-                print(f"e: {original_exception}")
                 if hasattr(original_exception, "message"):
                     if "Prompt has too many tokens" in original_exception.message:
                         exception_mapping_worked = True
                        raise ContextWindowExceededError(
                            message=f"AI21Exception - {original_exception.message}",
                            model=model,
@@ -1568,13 +1567,12 @@ def exception_type(model, original_exception, custom_llm_provider):
                        raise ContextWindowExceededError(
                            message=f"AI21Exception - {original_exception.message}",
                            model=model,
                             llm_provider="ai21"
                         )
                 if hasattr(original_exception, "status_code"):
-                    print(f"status code: {original_exception.status_code}")
                     if original_exception.status_code == 401:
                         exception_mapping_worked = True
                         raise AuthenticationError(
                            message=f"AI21Exception - {original_exception.message}",
                            llm_provider="ai21",
                        )

```
Note that lines in the diff body are prefixed with a symbol that represents the type of change: '-' for deletions, '+' for additions, and ' ' (a space) for unchanged lines


The PR Questions:
```
What is this PR about?
```

Response:
This PR removes unnecessary prints in AI21 handling.

What changes were made in

**Pull request merged**
