### PR TITLE
change max_tokens type to int

### PR DESCRIPTION
**Pull request by TanaroSch**
The docstring says int but the datatype was float. Since the amount of tokens is always integer, the datatype has been adjusted accordingly.

### CODE REVIEW

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
can you make the same change for litellm.acompletion on main 

(otherwise our ci/cd will fail tests)

**Comment by TanaroSch** [comment]
> can you make the same change for litellm.acompletion on main
> 
> (otherwise our ci/cd will fail tests)

Done. Also fixed other occurrences of max_tokens with float type.
Edit: It seems the ci/cd test still failed, but when trying to access the vercel details I get a 404 so I can't see why it failed

**Review by ishaan-jaff — APPROVED** [review]
lgtm !

**Comment by ishaan-jaff** [comment]
Confirmed this is correct on: https://platform.openai.com/docs/api-reference/chat

**Comment by ishaan-jaff** [comment]
Screenshot 2024-05-04 at 12 47 56 PM

**Pull request merged**
