### PR TITLE
Fix to support all file types supported by Gemini

### PR DESCRIPTION
**Pull request by nick-rackauckas**
## Title
Fix to support all file types supported by Gemini

## Type

🐛 Bug Fix

## Changes

- Add new enums, consts, and utils for determining file types (and getting associated mime type) from file extension
  - Included file types not used directly by the Gemini code, so it can be used elsewhere in the codebase
- Update Vertex AI logic to support all supported file types, rather than the 4 it was hardcoded to
- Removed unused function to avoid confusion (had similar logic)

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locally
No existing test suite for Vertex AI

### CODE REVIEW

**Comment by ghost** [comment]
hey @nick-rackauckas thanks for this PR. we have an existing test suite for vertex ai - https://github.com/BerriAI/litellm/blob/707a41fd6c5d2133ceecf0c4823d2a2be896ac5e/litellm/tests/test_amazing_vertex_completion.py#L4

could you please confirm it passes on your branch (attaching a screenshot here would be great)

```
cd litellm/litellm/tests

pytest test_amazing_vertex_completion.py -x -vv
```

**Comment by nick-rackauckas** [comment]
> pytest test_amazing_vertex_completion.py -x -vv

Trying to run it, but getting this error
````
original_exception = VertexAIError('401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.')
````
Passing in our private key id and private key through env vars

Is there a test running guide or something I'm missing?

**Comment by ghost** [comment]
replace this file (locally) with your service account.json - https://github.com/BerriAI/litellm/blob/636bc0e2ec4c78c7fb715e6a79054d33d4955427/litellm/tests/vertex_key.json


in the test, we run this function before the actual calls to setup the vertex credentials in the environment - https://github.com/BerriAI/litellm/blob/636bc0e2ec4c78c7fb715e6a79054d33d4955427/litellm/tests/test_amazing_vertex_completion.py#L27

**Comment by nick-rackauckas** [comment]
> replace this file (locally) with your service account.json - https://github.com/BerriAI/litellm/blob/636bc0e2ec4c78c7fb715e6a79054d33d4955427/litellm/tests/vertex_key.json
> 
> in the test, we run this function before the actual calls to setup the vertex credentials in the environment -
> 
> https://github.com/BerriAI/litellm/blob/636bc0e2ec4c78c7fb715e6a79054d33d4955427/litellm/tests/test_amazing_vertex_completion.py#L27

Did that, now seeing this
````
litellm.exceptions.BadRequestError: VertexAIException BadRequestError - 403 Caller does not have required permission to use project adroit-crow-413218. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=adroit-crow-413218 and then retry. Propagation of the new permission may take a few minutes.
````

**Comment by ghost** [comment]
got it - i think we have our service account hard coded in a few places - @nick-rackauckas  are you able to run these 2 tests on your end just to confirm it works? I can take care of any other issues that come up after that

- image call https://github.com/BerriAI/litellm/blob/636bc0e2ec4c78c7fb715e6a79054d33d4955427/litellm/tests/test_amazing_vertex_completion.py#L506

- function calling https://github.com/BerriAI/litellm/blob/636bc0e2ec4c78c7fb715e6a79054d33d4955427/litellm/tests/test_amazing_vertex_completion.py#L596

**Comment by nick-rackauckas** [comment]
> * test_gemini_pro_function_calling
Screenshot 2024-06-07 at 1 23 07 PM
Screenshot 2024-06-07 at 1 23 17 PM

**Comment by ghost** [comment]
Great!

**Pull request merged**
