### PR TITLE
Add system role support to model_prices_and_context_window.json

### PR DESCRIPTION
**Pull request by rajivpant**
## Add System Role Support

Added support for whether an LLM supports the "system" role along in its prompt or not. For example, Google Gemini models currently do not, so custom instructions and curated data sets need to be used as the "user" role instead of the "system" role as with other many other LLMs. 

## Relevant issues

For more information, see the files engines.yaml, helpers.py, ragbot_streamlit.py and ragbot.py in
https://github.com/rajivpant/ragbot

## Type

🆕 New Feature

## Changes

Tested json file for syntax locally.

### CODE REVIEW

**Comment by rajivpant** [comment]
Discussion in this LinkedIn thread: https://www.linkedin.com/feed/update/urn:li:activity:7196003160778272768/?commentUrn=urn%3Ali%3Acomment%3A(activity%3A7196003160778272768%2C7196111501546377216)&dashCommentUrn=urn%3Ali%3Afsd_comment%3A(7196111501546377216%2Curn%3Ali%3Aactivity%3A7196003160778272768)&dashReplyUrn=urn%3Ali%3Afsd_comment%3A(7197414218294267904%2Curn%3Ali%3Aactivity%3A7196003160778272768)&replyUrn=urn%3Ali%3Acomment%3A(activity%3A7196003160778272768%2C7197414218294267904)

**Comment by rajivpant** [comment]
On why this change is needed, see the following code at the end of https://github.com/rajivpant/ragbot/blob/main/helpers.py

    # Google Generative AI models don't seem to accept the "system" role for the prompt.
    if supports_system_role:
        messages = [
            {"role": "system", "content": "\n".join(custom_instructions) + "\n".join(curated_datasets)},
            {"role": "user", "content": prompt}  # Dynamic user input for current interaction
        ]
    else:
        messages = [
            {"role": "user", "content": "\n".join(custom_instructions)},
            {"role": "user", "content": "\n".join(curated_datasets)},
            {"role": "user", "content": prompt}  # Dynamic user input for current interaction
        ]
    
    llm_response = completion(model=model, messages=messages,  max_tokens=max_tokens, temperature=temperature)
    response = llm_response.get('choices', [{}])[0].get('message', {}).get('content')
    
    return response

**Comment by ghost** [comment]
i believe google gemini does support system role - 
Screenshot 2024-05-19 at 12 31 46 PM
https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference

It's something we need to add on our end

**Comment by rajivpant** [comment]
@krrishdholakia Thank you for this info.  Do I understand correctly then that once you add it on your (LiteLLM) end, the code above from my helpers.py that  I shared above could be simplified to the following and it would work with Google Gemini the same way it currently works for OpenAI GPT-4 and Anthropic Claude 3? In other words, I'd use the following format and LiteLLM would make it also work with Google Gemini? That I wouldn't need the if condition there anymore. Once you've added it, would you let me know? I'll test it with Ragbot.AI Thanks in advance.

<pre>

messages = [
    {"role": "system", "content": "\n".join(custom_instructions) + "\n".join(curated_datasets)},
    {"role": "user", "content": prompt}  # Dynamic user input for current interaction
]

llm_response = completion(model=model, messages=messages,  max_tokens=max_tokens, temperature=temperature)
response = llm_response.get('choices', [{}])[0].get('message', {}).get('content')

return response

</pre>

**Comment by ghost** [comment]
@rajivpant you don't need to do your if/else block today, if i'm not mistaken. 

We should already be converting system to user.

**Comment by rajivpant** [comment]
@krrishdholakia Thank you for your reply.  When I tried my code without the if/else block, it didn't work, i.e. the prompt context didn't contain the information I had put in my custom instructions and curated datasets.

Converting "system" to "user" is undesirable, because for Ragbot.AI to be most effective, I need the system instructions to be provided to the LLM as the "system" role in the prompt (not "user" role) and only the user's prompt to be sent to the LLM as "user" role in the prompt.

I'm sure Ragbot isn't the only product that needs this behavior (separation of "system" and "user" roles in the prompt) to work correctly in LiteLLM. If LiteLLM converts "system" to "user", it would make apps that use LiteLLM perform worse in terms of LLM response quality than those who don't use LiteLLM. Important for LiteLLM to fix.

Thank you in advance. I appreciate your engagement on this issue.

**Pull request closed without merging**
