### PR TITLE
[Feature]: Add advanced parameter to Ollama models

### PR DESCRIPTION
**Pull request by dhlidongming**
## Title
Add advanced parameter to Ollama models

## Relevant issues
#2886 

## Type
🆕 New Feature

## Changes
- add parameters `system` `template` `context` `raw` `keep_alive`  `suffix` inside ollama.py
- add parameter `keep_alive` inside ollama_chat.py

### CODE REVIEW

**Comment by ghost** [comment]
Hi @dhlidongming this is not needed as litellm already supports provider-specific params without needing them to be specified. 

example - https://docs.litellm.ai/docs/completion/provider_specific_params#proxy-usage

**Comment by ghost** [comment]
Feel free to create an issue if you see any errors with that approach (Also open to feedback, if you'd already explored that and wanted a better solution here)

**Comment by dhlidongming** [comment]
@krrishdholakia  Thank you for your response. Based on the method described in [your reply](https://docs.litellm.ai/docs/completion/provider_specific_params#proxy-usage), I have configured the config.yaml as follows:
```
model_list:
  - model_name: starcoder2:3b
    litellm_params:
      model: ollama/starcoder2:3b
      api_base: xxxxxx
      system: You are an expert software developer. You give helpful and concise responses.
```
then made a request using the following curl command:
```bash
curl -X POST 'http://0.0.0.0:4000/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-1234' \
-d '{
  "model": "starcoder2:3b",
  "messages": [
    {
      "role": "user",
      "content": "this is a test request"
    }
  ],
  "max_tokens": 100
}'
```
The LiteLLM logs show:
```
POST Request Sent from LiteLLM:
curl -X POST \
http://xxxxxx/api/generate \
-d '{'model': 'starcoder2:3b', 'prompt': 'this is a test request', 'options': {'num_predict': 100, 'system': 'You are an expert software developer. You give helpful and concise responses.'}, 'stream': False}'
```
It seems that the system parameter is included inside the options parameter, but according to the [Ollama documentation](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion), the system parameter should be at the same level as options.

**Comment by dhlidongming** [comment]
It appears that there is an issue in https://github.com/BerriAI/litellm/blob/398295116f38346333d1dee2bd7cc09e6ec72e96/litellm/llms/ollama.py#L221-L230
The parameters other than model, prompt, stream, format, and images are being wrapped inside the options parameter.

**Comment by ghost** [comment]
@dhlidongming the system parameter (i believe) is for the `/completion` endpoint. for `/chat/completion` which is what ollama_chat uses, just a normal openai system message should work fine 

should we just add the system message as message[0] on the ollama call?

**Comment by dhlidongming** [comment]
@krrishdholakia Yes, including the system message as message[0] should work. However, it's worth noting that some useful parameters in Ollama, such as `raw` and `keep_alive`, are managed similarly to the `system` message in LiteLLM, being wrapped under the options parameter. This might cause limitations, as these parameters may not function as intended in certain scenarios.

**Comment by ghost** [comment]
@dhlidongming that's fixed as of today morning - https://github.com/BerriAI/litellm/blob/c7b39786551fd9bf54803181f634d122ef4e3161/litellm/llms/ollama.py#L532

**Comment by dhlidongming** [comment]
@krrishdholakia, thanks for the fix! Could you also apply a similar modification to the `get_ollama_response` parameter handling? Some Ollama models' `/completion` endpoint requires the `raw` parameter. Appreciate you!

**Pull request closed without merging**
