### PR TITLE
Fixes and minor improvements for Helm Chart

### PR DESCRIPTION
**Pull request by rbren**
## Relevant issues
None

## Type
🐛 Bug Fix

## Changes
* Removed broken `initContainer`
  * the `default` block around the image tag is invalid, and causes an error when using the helm chart--not sure how this got in
  * the whole "init container to check if the DB is ready" seems like an antipattern to me--the regular litellm server restarts if the DB is not ready. So I don't think it really adds anything
* added an `extraContainers` block
  * I need this for GCP SQL proxy, so I can connect using the [sidecar pattern](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#run_the_in_a_sidecar_pattern)

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall

closest I can get:
```
❯ helm --debug template deploy/charts/litellm-helm/ > out.yaml
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /home/rbren/git/litellm/deploy/charts/litellm-helm


❯ echo $?
0
```

`helm template` works well

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for this @rbren - is it possible to add any unit testing for this? to prevent future regressions

**Comment by rbren** [comment]
Hmm...I added `helm lint` as a command to run in CI, which should at least ensure the chart isn't broken

I don't think this GH workflow runs on every commit though--lmk if there's a better place to put it

**Comment by ghost** [comment]
yes! we run circle ci - this is the right place to add it - https://github.com/BerriAI/litellm/blob/bcce21a5b0568ee76be52de3775c8ae5d9ac60a4/.circleci/config.yml#L404

**Comment by rbren** [comment]
Done!

I also updated the app version--would y'all be able to add changing `appVersion` in the Chart.yaml to your release process?

**Comment by ghost** [comment]
Hey @rbren definitely - how do we do that? 

Here's our release process - https://github.com/BerriAI/litellm/blob/bcce21a5b0568ee76be52de3775c8ae5d9ac60a4/.github/workflows/ghcr_deploy.yml

**Comment by rbren** [comment]
@krrishdholakia it'd be a manual step, just like updating your pyproject.toml

Ideally it'd happen after the docker image is published, but nbd if there's a gap

**Comment by ishaan-jaff** [comment]
Hi @rbren  thanks for using LiteLLM. Any chance we can hop on a call to learn how we can improve LiteLLM Proxy for you ? 

We’re planning roadmap and I’d love to get your feedback 

my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Pull request merged**
