### PR TITLE
Use current Git folder for building Dockerfile

### PR DESCRIPTION
**Pull request by Manouchehri**

### CODE REVIEW

**Comment by ghost** [comment]
does this mean somebody using the Dockerfile would just get the latest commit on the repo? @Manouchehri

**Comment by Manouchehri** [comment]
correct

**Comment by ghost** [comment]
cc: @PSU3D0 i believe you also use the dockerfile - would this change impact you?

**Comment by ghost** [comment]
I just tried to debug an issue with litellm which only shows up with the Docker build, and i completely agree with this change.

**Comment by ghost** [comment]
merged!

**Pull request merged**
