### PR TITLE
feat: added support for OPENAI_API_BASE

### PR DESCRIPTION
**Pull request by ErikBjare**
Added this after noticing it was missing in https://github.com/AntonOsika/gpt-engineer/pull/574#issuecomment-1695600449, which conflicted with https://github.com/AntonOsika/gpt-engineer/pull/639 (which uses `OPENAI_API_BASE`).

### CODE REVIEW

**Comment by ErikBjare** [comment]
CI errors seems to just be a secrets issue (since I'm not a contributor, I assume).

**Comment by ghost** [comment]
acknowledging this PR - looks good to me. I'll fix the CI issue and run it again.

**Comment by ghost** [comment]
@ishaan-jaff looks like i was able to get circle ci working off a push to `main` but it threw .env errors when i re-ran this PR. Any thoughts on what could be causing this? 


Screenshot 2023-08-28 at 7 30 45 AM

**Comment by ghost** [comment]
@ErikBjare your changes should be live in `v.0.1.493`

Let me know if you face any issues.

**Comment by ghost** [comment]
closing for now - but @ishaan-jaff i think we'll need to figure this circle ci issue.

@ErikBjare please re-open this if you face issues with using OPENAI_API_BASE via .env

**Comment by ErikBjare** [comment]
You didn't merge the PR and made a different one? :(

Discouraging to not get credit in the commit log, something to think about in the future with other contributors.

**Comment by ishaan-jaff** [comment]
Hi @ErikBjare sorry for the confusion about that. Our CI/CD pipeline has not been working well for PRs 

I re-opened this to merge it and add you as a contributor

**Comment by ishaan-jaff** [comment]
we definitely want contributors to get credit on their work - that's our top priority

**Comment by ishaan-jaff** [comment]
@ErikBjare what's your twitter/linkedin - would love to give you a shoutout in our daily changelog 

Here's a link to our discord https://discord.com/invite/wuPM9dRgDw -> I'd love to give you a shoutout once you join !

**Comment by ErikBjare** [comment]
Nice, thanks again guys!

**Pull request merged**
