### PR TITLE
Add `/engines/{model}/chat/completions` endpoint

### PR DESCRIPTION
**Pull request by msabramo**
Add endpoint: `"/engines/{model:path}/chat/completions"`

Without this, it results in:

```pytb
Traceback (most recent call last):
  File "/Users/abramowi/Code/OpenSource/litellm/litellm/proxy/proxy_server.py", line 3836, in completion
    raise HTTPException(
fastapi.exceptions.HTTPException: 400: {'error': 'completion: Invalid model name passed in model=gpt-3.5-turbo/chat'}
```

- [X] Includes a test

### CODE REVIEW

**Comment by ghost** [comment]
@msabramo thanks! can you attach a screenshot of this passing testing for you! 

Looks good to merge, after that.

**Comment by msabramo** [comment]
Screenshot of passing test:

Screenshot 2024-05-05 at 11 17 35 AM

**Comment by msabramo** [comment]
@krrishdholakia

**Comment by ghost** [comment]
Missed this. Thanks for the bump @msabramo

**Comment by ghost** [comment]
LGTM!

**Pull request merged**
