### PR TITLE
Allow multiple tools in anthropic response

### PR DESCRIPTION
**Pull request by Xirider**
Currently in litellm's anthropic response only the first tool is extracted and the rest is ignored. This PR allows to also parse the rest of the tools.

### CODE REVIEW

**Comment by ghost** [comment]
Hey @Xirider could you share a test for this either here or in the test script for ci/cd - https://github.com/BerriAI/litellm/blob/ff9de34a5d4c48e7cd829f1e80988b80204ecbae/litellm/tests/test_completion.py#L133

**Comment by ghost** [comment]
bump on this? @Xirider

**Comment by widike** [comment]
I would be great to have this as parallel function calling is quite efficient.

**Comment by Xirider** [comment]
I'm currently quite busy. So feel free to take it over!

**Comment by Xirider** [comment]
Nevermind, I think this is not longer necessary since anthropic enables their built in function calling

**Pull request closed without merging**
