### PR TITLE
Add async iterator to fix/enable streaming responses

### PR DESCRIPTION
**Pull request by estill01**
Add `__aiter__` and ` __anext__` to `CustomStreamWrapper` class so that it returns an async iterator

### CODE REVIEW

**Comment by estill01** [comment]
I'm building a streaming OpenAI chat response interface using `completion` and it seems this is necessary

**Comment by estill01** [comment]
Here's my server log output:
```txt
index.py", line 39, in stream_response
     async for chunk in response:
TypeError: 'async for' requires an object with __aiter__ method, got CustomStreamWrapper
```

**Comment by ishaan-jaff** [comment]
looks awesome ! thanks for the contribution @estill01 ! Is the key difference you're trying to do 

`async for chunk in response` and we only support `for chunk in response`

**Comment by ishaan-jaff** [comment]
if so we can add this to docs too, under Streaming - happy to add that in a separate PR / track it as an issue

**Review by ishaan-jaff — APPROVED** [review]

**Comment by ghost** [comment]
This is amazing! 

Can you help me understand the async case better @estill01? 

I used LiteLLM for streaming on our playground - https://litellm.ai/playground, and just used streaming as is. How do you use async here? 

For context, here's my API call code from my Next.js frontend: 

## api call
```
        const response = await fetch(apiUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(body)
        })
```

## stream output parsing
```
if (contentType && contentType.includes("text/event-stream")) {
            const response_body = response.body;
            const reader = response_body.getReader();
            const decoder = new TextDecoder();
            let done = false;

            while (!done) {
              const { value, done: readingDone } = await reader.read();
              done = readingDone;

              let chunkValue = decoder.decode(value);
              // Check if chunkValue starts with "data: " and remove it
              if (chunkValue.startsWith('data: ')) {
                chunkValue = chunkValue.slice(6);
              }
              // Split by new lines
              const lines = chunkValue.split('\n');

              // Check & Parse each line 
              lines.forEach(line => {
                if (line.startsWith('data: ')) {
                  line = line.slice(6); // remove "data: " 
                }
    
                if(line.trim() === "") return; // skip empty lines
    
                try {
                  const data = JSON.parse(line);
                  const content = data.choices[0].delta.content;
                  console.log("model:", body.model);
                  console.log("content:", content);
                  if (content) {
                    switch (body.model) {
                      case model1:
                        setValue1((prev) => prev + content);
                        break;
                      case model2:
                        setValue2((prev) => prev + content);
                        break;
                      case model3:
                        setValue3((prev) => prev + content);
                        break;
                      default:
                        console.error('Unexpected model:', body.model);
                    }
                  }
                } 
                catch (error) {
                  console.error("Error parsing JSON:", error);
                }
              });
            }
```

**Comment by estill01** [comment]
> looks awesome ! thanks for the contribution @estill01 ! Is the key difference you're trying to do
> 
> `async for chunk in response` and we only support `for chunk in response`

Yeah - exactly

**Comment by estill01** [comment]
> Can you help me understand the async case better @estill01?

Sure - Without an async iterator it blocks execution of other tasks that could be running concurrently while it's waiting for the next chunk of the response e.g. llm output sanitizer logic.

It also provides a DX boost so that it's harder to write code that doesn't work with `completion`

**Pull request merged**
