### PR TITLE
fix: Stream completion responses from anthropic. (Fix #3129)

### LINKED ISSUE #3129: [Bug]: anthropic streaming, streams chunks all at once
### What happened?

calling anthropic api streams all the chunks at once

this is caused b/c of not passing the stream param to the httpx client 

### Relevant log output

_No response_

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by jmandel**
Fix #3129

### CODE REVIEW

**Comment by jmandel** [comment]
Fixes #3129

**Comment by ghost** [comment]
hey @jmandel can you share a screenshot of it working for you? You can run the testing we have in `test_completion.py` and `test_streaming.py` for this as well 

Our ci/cd will also catch any issues once merged, testing before hand just helps keep main more stable 


Here's a test you could run - https://github.com/BerriAI/litellm/blob/f220a337bd8ca3182bb2166511df89c1778569cb/litellm/tests/test_streaming.py#L891

**Comment by jmandel** [comment]
https://youtu.be/bnfVjvwi4T4?si=Am3F4fP-r6xm2mOF&t=316 is a video of this working for me from a client-side web app. 

I tried following instructions at https://github.com/BerriAI/litellm?tab=readme-ov-file#contributing to run tests but this resulted in numerous unrelated (see below -- I'm sure there are just steps I'm not taking; I'm not super familiar with the build tooling so just proceeding based on the README).
```
$ poetry run pytest . -k test_claude_3_streaming_finish_reason
============================================================== test session starts ===============================================================
platform linux -- Python 3.11.7, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/jmandel/hobby/litellm/litellm/tests
plugins: anyio-4.3.0, mock-3.12.0
collected 492 items / 24 errors / 491 deselected / 1 selected                                                                                    

===================================================================== ERRORS =====================================================================
_______________________________________________________ ERROR collecting test_alerting.py ________________________________________________________
ImportError while importing test module '/home/jmandel/hobby/litellm/litellm/tests/test_alerting.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_alerting.py:12: in <module>
    from litellm.proxy.utils import ProxyLogging
../proxy/utils.py:3: in <module>
    import litellm, backoff
E   ModuleNotFoundError: No module named 'backoff'
```

**Comment by ghost** [comment]
great - thanks!

**Pull request merged**
