### PR TITLE
Add support for getAssistant endpoint

### PR DESCRIPTION
**Pull request by kiwiz**
## Title

Add support for the OpenAI [getAssistant](https://platform.openai.com/docs/api-reference/assistants/getAssistant) endpoint

## Relevant issues

None

## Type

🆕 New Feature

## Changes

* Add routes for `assistants/{id}`

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locally

WIP

### CODE REVIEW

**Comment by ghost** [comment]
Hey @kiwiz thanks for this. Can you share a screenshot of this passing your test?

**Comment by ishaan-jaff** [comment]
following up on this @kiwiz - can you share a screenshot of it passing your test ^

**Comment by kiwiz** [comment]
Sorry, I'll test this out soon.

**Comment by kiwiz** [comment]
Screenshot 2024-08-23 at 5 55 03 PM

Caveat! I disabled Azure when running this test as I don't have any azure keys.

**Comment by kiwiz** [comment]
Bump @krrishdholakia (apologies for the delay). I'm not sure if this has been resolved in the meantime? If so, feel free to close.

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
@kiwiz can you resolve the merge conflicts?

**Comment by kiwiz** [comment]
Updated

**Pull request merged**
