### PR TITLE
add alert function using ms-teams

### PR DESCRIPTION
**Pull request by kdongho**
Hello! In the environment I use, I primarily receive alerts through Ms-Teams instead of Slack, so I've configured alerts using Ms-Teams.

### Required Set-up
With the following configuration, it's possible to apply:

in proxy_config.yaml
```
general_settings:
  alerting: ["ms_teams"]
  alerting_threshold: 10
```

set enviroment
```
MS_TEAMS_WEBHOOK_URL=https://blabla.webhook.office.com/webhook2/blabla...
```

### Test Result
I successfully received the following message using hidden end point for alert `/health/services`:

image

** If this PR is accepted, the next plan will be to write documentation for Teams alert!

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@kdongho this is an awesome PR - any chance you can chat over a quick call: https://meet.google.com/otj-fksa-uiw ? 

It will help us approve the PR faster 

If you prefer a different time sharing a link to my calendar for your convenience - https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2023-10

**Comment by ghost** [comment]
Hey @kdongho i just tested a ms teams webhook url by just replacing the slack webhook url with teams, and it worked without any changes

**Comment by ghost** [comment]
Screenshot 2024-06-13 at 2 16 26 PM

**Comment by ghost** [comment]
Doc added here - https://github.com/BerriAI/litellm/commit/3a0af0eda36ad0deea68fd3c7030496c56c44d6d

https://docs.litellm.ai/docs/proxy/alerting#advanced---using-ms-teams-webhooks

**Comment by kdongho** [comment]
Dear @krrishdholakia 
That's nice works! Thanks for your test.

**Pull request closed without merging**
