### PR TITLE
Fix pytest warnings

### LINKED ISSUE #3417: Clean up / Fix test warnings resulting from pydantic V2 migration
Created a PR to clean up warnings appearing during  a pytest run:
```
========================================================================= warnings summary ==========================================================================
../../../../Library/Caches/pypoetry/virtualenvs/litellm-vO9t8ogX-py3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py:272: 23 warnings
  /Users/lj/Library/Caches/pypoetry/virtualenvs/litellm-vO9t8ogX-py3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py:272: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)

../proxy/_types.py:219
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:219: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:306
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:306: PydanticDeprecatedSince20: `pydantic.config.Extra` is deprecated, use literal values instead (e.g. `extra='allow'`). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    extra = Extra.allow  # Allow extra fields

../proxy/_types.py:309
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:309: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:338
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:338: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:385
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:385: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:454
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:454: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:466
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:466: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:509
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:509: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:546
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:546: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:840
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:840: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:867
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:867: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../proxy/_types.py:886
  /Users/lj/Documents/litellm/litellm/proxy/_types.py:886: PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    @root_validator(pre=True)

../utils.py:39
  /Users/lj/Documents/litellm/litellm/utils.py:39: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== short test summary info ======================================================================
ERROR test_azure_perf.py - openai.OpenAIError: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPEN...
ERROR test_config.py - ValueError: api_base is required for Azure OpenAI. Set it on your config. Model - {'model_name': 'gpt-3.5-turbo', 'litellm_params': {'model': 'azure/chatgpt-v-2...
ERROR test_model_alias_map.py - Failed: Error occurred: AnyscaleException - Traceback (most recent call last):
ERROR test_multiple_deployments.py - Failed: An exception occurred: 'NoneType' object has no attribute '_response_ms'
ERROR test_register_model.py - Failed: An error occurred: OpenAIException - Traceback (most recent call last):
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================== 36 warnings, 5 errors in 2.68s ===================================================================
```

### PR DESCRIPTION
**Pull request by lj-wego**
## Relevant issues
Fix #3417 

## Type
🧹 Refactoring

### CODE REVIEW

**Comment by ghost** [comment]
Hi @lj-wego can you use write some unit tests to make sure completion sync + async calls work 

you can use the `mock_response` param to avoid making actual llm api calls 

https://github.com/BerriAI/litellm/blob/5333474a6f60a1daee3e4695efc008b11908546e/litellm/tests/test_promptlayer_integration.py#L90

**Comment by lj-wego** [comment]
> Hi @lj-wego can you use write some unit tests to make sure completion sync + async calls work
> 
> you can use the `mock_response` param to avoid making actual llm api calls
> 
> https://github.com/BerriAI/litellm/blob/5333474a6f60a1daee3e4695efc008b11908546e/litellm/tests/test_promptlayer_integration.py#L90

@krrishdholakia I have added a simple test to highlight `pytest.mark.asyncio` decorator is working as intended after the addition of the plugin `pytest-asyncio`

I suspect prior to adding this plugin to poetry, test were passing due to other users having the plugin installed in their environment from other projects.

Other than resolving the warning, having the plugin in the `pyproject.toml` should help ensure contributor's env are consistent.

Also, if you would like, we can also implement [auto](https://pytest-asyncio.readthedocs.io/en/latest/concepts.html#auto-mode) mode in the pytest config so we can skip the decorator.

**Comment by lj-wego** [comment]
```zsh
➜ poetry run pytest test_acompletion.py::test_mock_acompletion
Configuration file exists at /Users/lj/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/lj/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
======================================================================== test session starts ========================================================================
platform darwin -- Python 3.11.3, pytest-7.4.4, pluggy-1.4.0
rootdir: /Users/lj/Documents/litellm
configfile: pyproject.toml
plugins: anyio-4.3.0, mock-3.12.0, asyncio-0.23.6
asyncio: mode=Mode.STRICT
collected 1 item                                                                                                                                                    

test_acompletion.py .                                                                                                                                         [100%]

========================================================================= 1 passed in 0.04s =========================================================================
```

**Comment by lj-wego** [comment]
I'm closing this for now. Can't keep up with the rapid changes. Let me know if any body wants me to try refactoring all the pydantic migration warnings.

**Comment by ghost** [comment]
We tried it in #3600  @lj-wego 

had to revert that PR because of these issues - https://github.com/BerriAI/litellm/pull/3664

Any help would be great here!

**Comment by lj-wego** [comment]
> We tried it in #3600 @lj-wego
> 
> had to revert that PR because of these issues - #3664
> 
> Any help would be great here!

I redid the replacements again,  could you run your CI on my PR? #3670

**Comment by ghost** [comment]
@ishaan-jaff is there a way to run CI on this without merging it in?

**Pull request closed without merging**
