### PR TITLE
Add Amazon Nova models

### PR DESCRIPTION
**Pull request by iwamot**
## Title

Add Amazon Nova models.
https://docs.aws.amazon.com/nova/latest/userguide/what-is-nova.html
https://aws.amazon.com/bedrock/pricing/

## Type

🆕 New Feature

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

### CODE REVIEW

**Comment by ghost** [comment]
Closing in favor of #7008

**Comment by yigitkonur** [comment]
I have implemented proper config but messages array is not being sent correctly I guess:

```
{
    "error": {
        "message": "litellm.BadRequestError: BedrockException - {\"message\":\"Malformed input request: #: required key [messages] not found, please reformat your input and try again.\"}\nReceived Model Group=nova-lite\nAvailable Model Group Fallbacks=None",
        "type": null,
        "param": null,
        "code": "400"
    }
}
```

**Comment by yigitkonur** [comment]
# Incoming Request to Proxy

{
  "message": "Request received by LiteLLM:\n{\n    \"model\": \"nova-pro\",\n    \"messages\": [\n        {\n            \"role\": \"user\",\n            \"content\": \"Hello, how are you?\"\n        }\n    ]\n}",
  "level": "DEBUG",
  "timestamp": "2024-12-04T08:18:52.882910"
}

# Raw Request Sent to Bedrock

{
  "message": "[92m\n\nPOST Request Sent from LiteLLM:\ncurl -X POST \\\nhttps://bedrock-runtime.us-east-1.amazonaws.com/model/amazon.nova-pro-v1:0/invoke \\\n-H 'Content-Type: *****' -H 'X-Amz-Date: *****' -H 'Authorization: xxxx/20241204/us-east-1/bedrock/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=xxx********************************************' -H 'Content-Length: *****' \\\n-d '{\"inputText\": \"Hello, how are you?\", \"textGenerationConfig\": {}}'\n[0m\n",
  "level": "DEBUG",
  "timestamp": "2024-12-04T08:18:54.919220"
}

**Comment by iwamot** [comment]
Hi @krrishdholakia,

Thank you for adding support for Amazon Nova!

Regarding the above error, it seems to be caused by the Converse API not being used internally. I'll try to investigate this further myself when I have the time.

Additionally, Amazon Nova Micro does not support vision and PDF input. Could you please check and update the configuration file accordingly?
https://docs.aws.amazon.com/nova/latest/userguide/what-is-nova.html

Thank you in advance for your help!

**Comment by ghost** [comment]
this is fixed on main - new release will be out soon

**Comment by iwamot** [comment]
After upgrading to v1.53.5, I specified `bedrock/amazon.nova-pro-v1:0` as the model and confirmed that the error could not be reproduced. Thanks so much!

**Pull request closed without merging**
