### PR TITLE
Add Opus model

### PR DESCRIPTION
**Pull request by tjandy98**
## Title

Add Opus to the table
## Type
📖 Documentation

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@tjandy98 curious - do you use litellm today ?

**Comment by tjandy98** [comment]
> @tjandy98 curious - do you use litellm today ?

Thank you for merging! 
Yes, I am using it.

**Comment by ishaan-jaff** [comment]
@tjandy98 - do you use the LiteLLM SDK or Proxy server ?

**Comment by tjandy98** [comment]
> @tjandy98 - do you use the LiteLLM SDK or Proxy server ?

I am using (experimenting) with the proxy

**Comment by ishaan-jaff** [comment]
what are you trying to do with the proxy ? 

If you prefer we can continue convo over DMs, my linkedin: https://www.linkedin.com/in/reffajnaahsi/

context - trying to learn how we can improve for you

**Comment by ishaan-jaff** [comment]
hi @tjandy98 can we hop on a call sometime this week. I'd love to learn how we can improve litellm for you. What's the best email to send an invite to ?

If it's easier here's a link to my cal https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Pull request merged**
