### PR TITLE
Add langfuse `sdk_integration`

### PR DESCRIPTION
**Pull request by marcklingen**
`sdk_integration` helps to track which Langfuse events are ingested via the integration. Helpful for everyone using multiple integrations and langfuse>=2.6

### CODE REVIEW

**Comment by ghost** [comment]
@marcklingen if a user is on an older version of langfuse, wouldn't this change cause errors for their logging?

**Comment by marcklingen** [comment]
I understood that the current version of litellm requires langfuse>=2.6.3 based on the requirements, is that incorrect? `sdk_integration` is available from 2.6.0 onwards. I can also conditionally add this depending on the version.

**Comment by ghost** [comment]
Conditional would be great - i think you can see logic for it in the langfuse_v_2 function @marcklingen 

Thanks for this!

**Comment by marcklingen** [comment]
@krrishdholakia updated, sorry for delay

**Comment by marcklingen** [comment]
@krrishdholakia can you have a look?

**Pull request merged**
