### PR TITLE
Athina callback now handles streaming mode

### PR DESCRIPTION
**Pull request by vivek-athina**
Callback is working now in both streaming and non-stream modes

Screenshot 2024-04-17 at 12 13 18 AM
Screenshot 2024-04-17 at 12 13 23 AM
Screenshot 2024-04-17 at 12 13 30 AM

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@vivek-athina can you address this before we merge any other athina changes: https://github.com/BerriAI/litellm/discussions/2957

**Comment by vivek-athina** [comment]
@ishaan-jaff Addressed it.

**Comment by vivek-athina** [comment]
@ishaan-jaff @krrishdholakia Can you please review this and merge it?

**Comment by vivek-athina** [comment]
@ishaan-jaff @krrishdholakia Can you please review this and merge it?

**Pull request merged**
