### PR TITLE
Update model config definition to use v2 style

### PR DESCRIPTION
**Pull request by lj-wego**
Context:
Addresses bug found in https://github.com/BerriAI/litellm/commit/beffa4e3984bd6862f8d278459ae146435ffd53f
Fixed by in 3d3502e15babc61a56789a2c26d6bcb00cdf6533

## Type
🐛 Bug Fix
🧹 Refactoring

## Changes
Updates `class Config` --> `model_config` as per Pydantic V2 guidelines

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@lj-wego can you send a screenshot of it passing locally ?

**Comment by lj-wego** [comment]
> @lj-wego can you send a screenshot of it passing locally ?

@ishaan-jaff 
image

**Comment by lj-wego** [comment]
Seems like there are new pydantic warnings about `model_dump` will look into it some other time

**Comment by ishaan-jaff** [comment]
Hi @lj-wego curious do you use litellm proxy in production today ?

**Comment by lj-wego** [comment]
> Hi @lj-wego curious do you use litellm proxy in production today ?

we are using litellm sdk in production (limited a/b testing release). we have plans to use the proxy in the near future

**Comment by ishaan-jaff** [comment]
@lj-wego any chance we can hop on a call - I'd love to learn how can improve litellm for you ? 

If you want to dm - my linkedin is here: https://www.linkedin.com/in/reffajnaahsi/ 
My cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2023-10

**Comment by ishaan-jaff** [comment]
Hi @lj-wego - wanted to follow up on this. I'd love to hop on a quick call to meet you and learn how we can improve litellm for you. 

If call does not work - can we setup a 1:1 support channel to help your team with any litellm issues 
Linkedin: https://www.linkedin.com/in/reffajnaahsi/
Discord: https://discord.com/invite/wuPM9dRgDw

**Pull request merged**
