### PR TITLE
[WIP] feat(vertex_ai_anthropic.py): Add support for claude 3 on vertex ai

### PR DESCRIPTION
**Pull request by ghost**
Addresses - https://github.com/BerriAI/litellm/issues/2658

## Blocker 

Awaiting Google to approve our Vertex AI Quota increase

### CODE REVIEW

**Comment by analogpvt** [comment]
any update on this

**Comment by ghost** [comment]
Hey @analogpvt, should be out this week (aiming for tomorrow)

**Comment by analogpvt** [comment]
Any update on this

**Comment by ghost** [comment]
Hey @analogpvt 

completions is now working.

Going to implement streaming + Async and merge this into main tomorrow

**Comment by analogpvt** [comment]
any update

**Pull request merged**
