### PR TITLE
Databricks Integration: Integrate Databricks SDK as optional mechanism for fetching API base and token, if unspecified

### PR DESCRIPTION
**Pull request by dbczumar**
## Title

Integrate Databricks SDK as optional mechanism for fetching API base and token, if unspecified

## Type

🆕 New Feature

## Changes

This PR introduces support for using the Databricks SDK to automatically fetch an API token and API base from the current environment when handling completions requests, if the user does not specify a token / base manually.

**Unit tests**

Screenshot 2024-09-17 at 12 28 19 AM

**Manual tests**

Ran the following script and confirmed that the output is sane:

```
import asyncio
from litellm import completion, acompletion, embedding, aembedding
import os

response = completion(
    model="databricks/databricks-dbrx-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    stream=False,
)

print(response)
print(list(response))

os.environ["DATABRICKS_API_KEY"] = "...."
os.environ["DATABRICKS_API_BASE"] = "...."


response = completion(
    model="databricks/databricks-dbrx-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    stream=True
)
print(response)
print(list(response))

response = asyncio.run(acompletion(
    model="databricks/databricks-dbrx-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}]
))
print(response)

response = asyncio.run(acompletion(
    model="databricks/databricks-dbrx-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    stream=True
))
print(response)
print(asyncio.run(anext(asyncio.run(response.fetch_stream()))))

response = embedding(
    model="databricks/databricks-bge-large-en",
    input=["Hello, how are you?"],
)

print(response)
print(list(response))

response = asyncio.run(aembedding(
    model="databricks/databricks-bge-large-en",
    input=["Hello, how are you?"],
))

print(response)
print(list(response))
```

### CODE REVIEW

**Comment by dbczumar** [comment]
@krrishdholakia I refiled this against `main`, since https://github.com/BerriAI/litellm/pull/5733/files was closed when the target branch was deleted. Can you take another look?

**Comment by ghost** [comment]
Yup. Assigning myself to this ticket. Great work on this @dbczumar

**Comment by ghost** [comment]
Aiming to have this merged into tomorrow's release

**Comment by dbczumar** [comment]
@krrishdholakia Did you get a chance to take a look at this?

**Comment by ghost** [comment]
thanks for the bump @dbczumar

**Pull request merged**
