### PR TITLE
Fix streaming anthropic

### PR DESCRIPTION
**Pull request by adriensas**
Streaming not working due to missing parameter in requests.post streaming=True

### CODE REVIEW

**Comment by ghost** [comment]
Hi @adriensas the data dict already contains the stream = true parameter. The proposed PR would set it to always true. Can you please share a screenshot + code snippet of the existing streaming not working?

**Comment by adriensas** [comment]
@krrishdholakia In my code the stream=True is in the data for anthropic and as a requests.post paramater (not the data transfered but the function parameter) otherwise (at least in my case with python 3.9) it waits for the whole stream before getting the entire response.
It won't set it to always true as I've passed optionnal_parameter["stream"] and not True

**Comment by ghost** [comment]
Ok makes sense - give me a day to test this and i'll either merge or get back in case anything is missing. thanks for the PR @adriensas

**Comment by ghost** [comment]
Do you have a twitter / linkedin? would love to give a shoutout once this is merged

**Comment by adriensas** [comment]
It's a pleasure 😊 
I was also wondering if it was normal that the litellm streaming with together AI can't be called in the same way as openai or anthropic (testing and looking at the corresponding notebook).
If it's not I may correct that too.
My twitter is @ASasportes

**Comment by ghost** [comment]
it should be the same - i'll look into it. Thanks for the heads up.

@adriensas are you using multiple llm providers in production?

**Comment by adriensas** [comment]
Not yet in production but we are planning to do it.
Together ai allows to fine tune smaller model that can be runned at a very very competitive price.

**Comment by ghost** [comment]
Sounds good - sorry for the delay. This will be done tomorrow.

**Comment by ishaan-jaff** [comment]
looks like some tests are failing due to an outdated / invalid key on our end on circle ci cc @krrishdholakia

**Comment by krrishdholakia** [comment]
Hey @adriensas streaming for anthropic and together ai should be working now (v0.1.487+). Can you confirm this? 

I reviewed the PR and it seems like the key change here is to explicitly call out 'stream': the value? 

I don't think removing the constants is a good idea (which i believe your PR also does) - was there a specific reason for doing that?

**Comment by ghost** [comment]
Hi @adriensas - i cloned your PR - had minor issues that I fixed. This should be live now in `v0.1.491`. 

I also realized the same logic applies to the together ai api endpoint call, so updated that too. Thank you for this amazing PR!

**Comment by ghost** [comment]
@adriensas it's now live on https://litellm.ai/ if you want to test it out

**Comment by ishaan-jaff** [comment]
re opening this PR to give @adriensas credit on our commit log😊

**Comment by ishaan-jaff** [comment]
merging this - will take care of any merge conflicts / changes

**Comment by ghost** [comment]
Hi @adriensas,

Did this resolve your issue?

**Pull request merged**
