### PR TITLE
Fix bad returns in get_available_deployment

### PR DESCRIPTION
**Pull request by nathankim7**

### CODE REVIEW

**Comment by PrathamSoni** [comment]
Thanks Nathan

**Comment by ishaan-jaff** [comment]
cc @krrishdholakia this is related to router

**Comment by ghost** [comment]
lgtm!

**Comment by ghost** [comment]
@nathankim7 do you have a way to repro this scenario? will add it to our test suite.

**Comment by ghost** [comment]
@nathankim7 @PrathamSoni  revisiting this PR - when could you possibly trigger item[0]  - wouldn't that imply the random shuffle didn't work (which i can only think of happening if potential deployments is empty) 

Screenshot 2023-11-10 at 9 35 03 AM

**Pull request merged**
