### PR TITLE
fix(vertex_httpx.py): support sending extra_headers

### PR DESCRIPTION
**Pull request by Manouchehri**
@krrishdholakia I spent about an hour trying to get this working before giving up, not sure why `extra_headers` isn't being used. =/

Related to #4317.

### CODE REVIEW

**Comment by ghost** [comment]
hey @Manouchehri is this done? 

unclear based on your comments 


If so - can you please add a test for this. Similar to - https://github.com/BerriAI/litellm/blob/3feaf231ac5d461b717d4cda3ba9331f34aca810/litellm/tests/test_amazing_vertex_completion.py#L859

**Comment by Manouchehri** [comment]
It's not done, I gave up and hardcoded the headers I wanted to add in our private LiteLLM fork. =(

**Comment by ghost** [comment]
why do you need to pass in extra headers? @Manouchehri

**Comment by Manouchehri** [comment]
To pass in `extra_headers: {"cf-skip-cache": "true"}`.

**Pull request closed without merging**
