### PR TITLE
Update custom-mapping table to be more readable

### PR DESCRIPTION
**Pull request by pratik9315**
Modified the custom mapping [table ](https://docs.litellm.ai/docs/exception_mapping#custom-mapping-list)into a 2D table

Solves #288 

My [Twitter](https://twitter.com/nateman0801)

### CODE REVIEW

**Comment by ghost** [comment]
Great work @pratik2315 

Small thing - I was referring to the exception name + provider name



While this is great, it's hard for me to know what exception name i should be try-catching so I can do error handling

**Comment by ghost** [comment]
Here's an example of how that gets used 

https://litellm-ahgo339av-clerkieai.vercel.app/docs/tutorials/model_fallbacks#3-context-window-exceptions

**Comment by ghost** [comment]
Screenshot 2023-09-09 at 8 56 15 AM

rough idea

**Comment by ghost** [comment]
@pratik2315 are you planning on making the updates - if not, i can close the PR

**Comment by pratik9315** [comment]
Hey @krrishdholakia 
Apologies for the delay in changes. I'll be making the updates today itself.

**Comment by pratik9315** [comment]
Hey @krrishdholakia !
Can you check if it's right now?😄

**Comment by pratik9315** [comment]
Do let me know if I can add something or fix it, I'll do it right away :)

**Comment by ghost** [comment]
no worries - made the fix

**Comment by ghost** [comment]
Thanks for the PR and welcome to the community - https://discord.com/invite/wuPM9dRgDw

**Pull request merged**
