### PR TITLE
(feat - watsonx provider) Add support for passing watsonx.ai API client

### PR DESCRIPTION
**Pull request by simonsanvil**
## Add support for passing watsonx.ai API client

Some watsonx.ai users might want to pass an instance of `ibm_watsonx_ai.client.APIClient` to make requests to the API, which has more authentication options and better support for non-SAAS deployments.  This PR adds support for passing a `client` argument to the completion and embeddings function when you specify the `watsonx` provider without adding new dependencies or breaking the previous functionality.

## Type

🆕 New Feature: Support for passing watsonx.ai API client
🐛 Bug Fix: Fixed issue with watsonx aembeddings not returning a coroutine. 

## Changes

- watsonx.py: support for passing the `client` argument and handling of 'service unavailable errors', fixed bug with aembeddings
- main.py: pass client argument to watsonx provider completion and embeddings functions.
- docs (providers/watsonx): added documentation on passing a client to the completion endpoints. 

### Example:

```python
from ibm_watsonx_ai.client import APIClient
from litellm import completion

watsonx_client = APIClient(
    credentials={
        'apikey': "",
        'url': ""
    },
    project_id=""
)
response = completion(
    model="watsonx/ibm/granite-13b-chat-v2",
    messages=[{ "content": "What is your favorite color?","role": "user"}],
    client=watsonx_client # NEW
)
response
# ModelResponse(id='chatcmpl-...', choices=[Choices(finish_reason='stop', index=0, message=Message(content="I don't have a favorite color, but I do like the color blue. What's your favorite color?", role='assistant'))], created=1716740689.482, model=ibm/granite-13b-chat-v2, object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=19, completion_tokens=45, total_tokens=64), finish_reason='eos_token')
```

### Test:

`pytest tests/test_completion.py -k "watsonx" `

`python -m mypy . --ignore-missing-imports`

### CODE REVIEW

**Comment by simonsanvil** [comment]
@krrishdholakia wondering if we can bump this for the next release?

**Comment by ghost** [comment]
can we add testing for this @simonsanvil 

this will prevent future regressions 

pending 
- add testing 
- share screenshot of testing passing

**Comment by ghost** [comment]
Reviewing further. @simonsanvil why not do it similar to the bedrock_httpx.py implementation 

- we use boto3 to handle credentials -> it returns the access token -> we use that for the http call 

This lets the client library handle the auth, but lets us handle http call management - so if parameters get added etc., client versions don't need to keep being updated 

https://github.com/BerriAI/litellm/blob/3167bee25aaae02f166c5048931d752580e10042/litellm/llms/bedrock_httpx.py#L212

**Comment by simonsanvil** [comment]
I'm open to this idea. I will close this PR for the time being and submit a new one once I manage to implement it that way

**Comment by ghost** [comment]
i believe it's already done - https://github.com/BerriAI/litellm/blob/5aae2313f3fa9bc099eaa82ead51144205e5f203/litellm/llms/watsonx.py#L284

**Pull request closed without merging**
