### PR TITLE
[Feat] UI view spend per API Key

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## UI Improvements
screenshot-rocks

## New Endpoints - [Spend Tracking]
- `/spend/keys` - View all keys created, ordered by spend
- `/spend/logs` - View all spend logs, if request_id is provided, only logs for that request_id will be returned

Example response for `/spend/logs`
```json
[{"request_id":"chatcmpl-6dcb2540-d3d7-4e49-bb27-291f863f112e","call_type":"acompletion","api_key":"51**","spend":7.25e-05,"startTime":"2024-01-18T18:07:54.071000Z","endTime":"2024-01-18T18:07:55.510000Z","model":"cohere.command-text-v14","user":"litellm-is-awesome-user","modelParameters":{},"messages":[{"role":"user","content":"what llm are you-444"}],"response":"{\"id\":\"chatcmpl-6dcb2540-d3d7-4e49-bb27-291f863f112e\",\"choices\":[{\"finish_reason\":\"stop\",\"index\":0,\"message\":{\"content\":\" I am an AI chatbot, trained as an LLM by Cohere. Is there anything else you would like to know about LLMs? \",\"role\":\"assistant\"}}],\"created\":1705630075,\"model\":\"cohere.command-text-v14\",\"object\":\"chat.completion\",\"system_fingerprint\":null,\"usage\":{\"prompt_tokens\":7,\"completion_tokens\":31,\"total_tokens\":38}}","usage":{"total_tokens":38,"prompt_tokens":7,"completion_tokens":31},"metadata":{"headers":{"host":"0.0.0.0:8000","accept":"*/*","user-agent":"curl/7.88.1","content-type":"application/json","authorization":"Bearer sk-zNhplEZxJ-yOuZkqRvwO_g","content-length":"224"},"endpoint":"http://0.0.0.0:8000/chat/completions","deployment":"bedrock/cohere.command-text-v14","model_group":"BEDROCK_GROUP","user_api_key":"2b6e4ff4c14f67b6ccd7318948f0d66fe8724099224baeaf4733792a2048aeb3","caching_groups":null,"user_api_key_user_id":"ishaan2@berri.ai","user_api_key_metadata":{}},"cache_hit":""}]
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
passes testing

**Comment by ghost** [comment]
is `/spend/logs` admin only?

**Comment by ishaan-jaff** [comment]
@krrishdholakia no, even non admin keys can see this

**Comment by ishaan-jaff** [comment]
example, this should work too 

```
curl -X GET "http://0.0.0.0:8000/spend/logs?request_id=chatcmpl-6dcb2540-d3d7-4e49-bb27-291f863f112e" \
-H "Authorization: Bearer sk-_0lFKXbIcxBg7bPMP8sANA"
```

**Pull request merged**
