### PR TITLE
VertexAI[FIX]: Fixing alternating messages breaking with empty assistant/user messages

### PR DESCRIPTION
**Pull request by andrewmjc**
## VertexAI[FIX]: Fixing alternating messages breaking with empty assistant/user messages

Previously, when sending empty assistant messages between user messages (and vice versa), google would throw a 400 due to the alternating of user/assistant messages being broken (the merging strategy missed this edge case).

To fix this, we simply filter out all assistant / user messages with no content or tool calls before merging assistant/user messages

## Type

🐛 Bug Fix

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

### CODE REVIEW

**Comment by ghost** [comment]
hey @andrewmjc can you share a test case for repro

**Comment by andrewmjc** [comment]
@krrishdholakia The following will throw a 500 ```curl -X 'POST' \
  'http://lite-llm-url/openai/deployments/gemini-1.5-flash/chat/completions' \
  -H 'accept: application/json' \
  -H 'API-Key: sk-key' \
  -d '{"messages":[{"role":"user","content":"hi"},{"role":"assistant","content":""},{"role":"user","content":"what"}],"model":"gemini-1.5-flash"}'```

**Comment by ghost** [comment]
Hey @andrewmjc i just ran your test on multiple providers (anthropic, vertex, bedrock, azure, openai, google ai studio) and saw it fail in couple of places. 

Made a new pr to do this across providers. Thanks for this test case

**Comment by ghost** [comment]
Closing in favor of #4678 

@andrewmjc can we do a 10min call this/next week to learn how you're using litellm? Would love to improve for your use-case


https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by andrewmjc** [comment]
Awesome! Thank you for the PR! Also I will book a call for next week :)

**Pull request closed without merging**
