### PR TITLE
Adding gpt-4o

### PR DESCRIPTION
**Pull request by HowieG**
## Title

Adding gpt-4o to model costs

## Notes

First contribution feel free to let me know if any changes are required. Not sure if you support an array for "mode". Since this model is trimodal I felt like adding all three was best. Might require a code change if anything relies on it being a string

### CODE REVIEW

**Comment by HowieG** [comment]
Resolves #3612

**Comment by ghost** [comment]
Closing in favor of #3613

**Comment by emsi** [comment]
Actually I'm getting:
`Error occurred in getting api base - LLM Provider NOT provided`
when using `gpt-4o-2024-05-13` as model.

**Comment by ishaan-jaff** [comment]
@emsi can you try again - it takes about 5 mins for the change to propagate. Should be live now

**Comment by emsi** [comment]
> @emsi can you try again - it takes about 5 mins for the change to propagate. Should be live now

It works now! Thank you!

**Pull request closed without merging**
