### PR TITLE
Delete node_modules directory

### PR DESCRIPTION
**Pull request by w3bdesign**
This folder should generally not be committed to Github

### CODE REVIEW

**Comment by ghost** [comment]
thanks - is there a specific .gitignore we should add this to? I suspect this will resurface if we don't have this ignored in the right place @w3bdesign

**Comment by w3bdesign** [comment]
> thanks - is there a specific .gitignore we should add this to? I suspect this will resurface if we don't have this ignored in the right place @w3bdesign

It should be enough to add to add it to the .gitignore in the root directory (where README.md is)

Then the node_modules directory should be deleted.

**Comment by w3bdesign** [comment]
> thanks - is there a specific .gitignore we should add this to? I suspect this will resurface if we don't have this ignored in the right place @w3bdesign

@krrishdholakia 

It should be enough to add to add it to the .gitignore in the root directory (where README.md is)

Then the node_modules directory should be deleted.

I will add this to the PR.

**Comment by w3bdesign** [comment]
Added to .gitignore in this PR now.

https://github.com/BerriAI/litellm/pull/2791/commits/255dbdedffd21a371d06106f58613866122a14f6

**Comment by ghost** [comment]
Thanks @w3bdesign

**Pull request merged**
