### PR TITLE
Fix minor typos in image_generation.md

### PR DESCRIPTION
**Pull request by cmungall**
Fixed two typos

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Thanks for the contribution @cmungall

**Review by ishaan-jaff — APPROVED** [review]
lgtm

**Comment by ishaan-jaff** [comment]
@cmungall will give you a shoutout in our daily changelog

What do you use litellm for ?

**Comment by cmungall** [comment]
Thanks!

I use Simon Willison's [llm](https://github.com/simonw/llm/) on the command line for ad-hoc tasks, and litellm gives me an easy bridge to use a wider variety of models

We are planning to use litellm in our [OntoGPT](https://github.com/monarch-initiative/ontogpt/) tool, which allows for extraction of structured knowledge from the literature

- https://github.com/monarch-initiative/ontogpt/issues/179

Methods described here: https://arxiv.org/abs/2304.02711

We are also planning to use it in [CurateGPT](https://github.com/monarch-initiative/curate-gpt) and in [DRAGON-AI](https://www.linkedin.com/feed/update/urn:li:activity:7142971769526685696/)

- https://github.com/monarch-initiative/curate-gpt/issues/15

**Pull request merged**
