### PR TITLE
Fix issue with delta being None when Deferred / Async Content Filter is enabled on Azure OpenAI

### LINKED ISSUE #3761: [Bug]: ModuleNotFoundError since upgrading to 1.36.0+
### What happened?

I'm trying to upgrade [Elia](https://github.com/darrenburns/elia) to the latest version of LiteLLM (from 1.35.38). When I upgrade from 1.35.38 to 1.36.0, I get a `ModuleNotFoundError`, as some module is failing to be imported.

### Relevant log output

```shell
│ /Users/darrenburns/code/elia/.venv/lib/python3.11/site-packages/litellm/types/llms/__init__.py:3 in <module>       │
│                                                                                                                    │
│   1 __all__ = ["openai"]                                                                                           │
│   2                                                                                                                │
│ ❱ 3 from . import openai                                                                                           │
│   4                                                                                                                │
│                                                                                                                    │
│ /Users/darrenburns/code/elia/.venv/lib/python3.11/site-packages/litellm/types/llms/openai.py:12 in <module>        │
│                                                                                                                    │
│     9 from typing_extensions import override, Required                                                             │
│    10 from pydantic import BaseModel                                                                               │
│    11                                                                                                              │
│ ❱  12 from openai.types.beta.threads.message_content import MessageContent                                         │
│    13 from openai.types.beta.threads.message import Message as OpenAIMessage                                       │
│    14 from openai.types.beta.thread_create_params import (                                                         │
│    15 │   Message as OpenAICreateThreadParamsMessage,                                                              │
│                                                                                                                    │
│ ╭──────────────────── locals ────────────────────╮                                                                 │
│ │       Any = typing.Any                         │                                                                 │
│ │ BaseModel = <class 'pydantic.main.BaseModel'>  │                                                                 │
│ │  BinaryIO = <class 'typing.BinaryIO'>          │                                                                 │
│ │  Iterable = typing.Iterable                    │                                                                 │
│ │   Literal = typing.Literal                     │                                                                 │
│ │  Optional = typing.Optional                    │                                                                 │
│ │  override = <function override at 0x104faa8e0> │                                                                 │
│ │  Required = typing.Required                    │                                                                 │
│ │     Union = typing.Union                       │                                                                 │
│ ╰────────────────────────────────────────────────╯                                                                 │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'openai.types.beta.threads.message_content'
```

### Twitter / LinkedIn details

_No response_

### LINKED ISSUE #3811: [Bug]: Enabling Async Streaming mode on Azure OpenAI breaks streaming due to `delta` bing none
### What happened?

Azure OpenAI has a (new) async streaming mode for its output response content filter. When this mode is enabled, sometimes the `delta` of a `chunk` can be `None` and this breaks streaming. Here's a similar issue reported on another repo: https://github.com/langgenius/dify/issues/3384

The solution is pretty simple, check for `None` on the `utils.py` function that process the streaming chunks.

### Relevant log output

_No response_

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by afbarbaro**
## Title

Fix issue with Deferred / Async Content Filter streaming in Azure OpenAI

## Relevant issues

Fixes #3811 

## Type

🐛 Bug Fix

## Changes

Just changes to `utils.py`

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

Tested with failing test on my repo exhibiting the issue

### CODE REVIEW

**Comment by afbarbaro** [comment]
@krrishdholakia, FYI, I'd appreciate your review and comments. This is a bit of a blocker for me at the moment as it prevents me from using Azure (I get errors).

**Comment by ghost** [comment]
hey @afbarbaro can you add a test for this in `test_streaming.py` so we don't have regressions here? 

See how this huggingface test was implemented with a mock response - https://github.com/BerriAI/litellm/blob/18f8287e29fd91a1db297bcee68a5d999afb6e53/litellm/tests/test_completion.py#L1314

just add it here - https://github.com/BerriAI/litellm/blob/18f8287e29fd91a1db297bcee68a5d999afb6e53/litellm/tests/test_streaming.py

and share a screenshot of it passing

**Comment by afbarbaro** [comment]
> test_streaming

Cool. Will do. Thanks for the quick response.

**Comment by afbarbaro** [comment]
Hey @krrishdholakia : I implemented a test, but:
1. used a different pattern I saw in another test, which tests the `litellm.CustomStreamWrapper` directly. This is a lot easier than mocking a chunked response.
2. I didn't run the tests locally. Can you confirm it works or give me a hint as to how to run just this tests? command line example will do.

**Comment by afbarbaro** [comment]
> Hey @krrishdholakia : I implemented a test, but:
> 
> 1. used a different pattern I saw in another test, which tests the `litellm.CustomStreamWrapper` directly. This is a lot easier than mocking a chunked response.
> 2. I didn't run the tests locally. Can you confirm it works or give me a hint as to how to run just this tests? command line example will do.

Cleaned up the test and pushed again. Let me know if you have any questions and/or additional guidance @krrishdholakia .

**Comment by afbarbaro** [comment]
ok @krrishdholakia test passes now.

```
poetry run pytest ./test_streaming.py::test_completion_azure_stream_content_filter_no_delta
```

image

**Comment by ghost** [comment]
LGTM! thanks @afbarbaro 

i'll queue up a new release

**Pull request merged**
