### PR TITLE
support langfuse tags feature

### PR DESCRIPTION
**Pull request by deenaawny-github-account**
Added support for langufuse trace tagging, the tags can be provided in the metadata when calling a completion.

### CODE REVIEW

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
Can you add this to docs too

**Comment by ishaan-jaff** [comment]
Thanks for the contribution would love to give you a shoutout on our changelog @deenaawny-github-account ! What's your Linkedin / Twitter ?

**Comment by deenaawny-github-account** [comment]
@ishaan-jaff
I will try to add the feature to the docs.
Thanks for the shoutout. My LinkedIn: https://www.linkedin.com/in/deena-awny-a95a45210/

**Comment by ishaan-jaff** [comment]
Awesome ! curious, do you use the litellm proxy server or the package ?

**Comment by deenaawny-github-account** [comment]
@ishaan-jaff I am using the package.

**Comment by deenaawny-github-account** [comment]
@ishaan-jaff updated the docs.
I also wanted to give you some insight about the contribution workflow.
One of the steps was to run the `poetry run pytest .` . The command returns 22 errors (both before and after the change). Some of the errors referred to missing key values in the .env file.
Thanks for accepting the contribution.

**Comment by ishaan-jaff** [comment]
@deenaawny-github-account how can we improve the workflow ?

**Review by ishaan-jaff — APPROVED** [review]
lgtm !

**Comment by deenaawny-github-account** [comment]
@ishaan-jaff testing is important, so I can't really give any feedback on how to improve it.

**Pull request merged**
