### PR TITLE
Fix route `/openai/deployments/{model}/chat/completions` not working properly

### LINKED ISSUE #3372: [Bug]: `/openai/deployments/{model}/chat/completions` returns 401 error
### What happened?

Looks like [/openai/deployments/{model}/chat/completions](https://litellm-api.up.railway.app/#/completions/completion_openai_deployments__model__completions_post) is supported but it's not working:

```
curl --request POST \
  --url 'https://llm-proxy.xyz.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-02-15-preview' \
  --header 'Authorization: Bearer sk-7A...peQ' \
  --header 'Content-Type: application/json' \
  --data '{
  "messages": [{"role":"system","content":"you are a helpful assistant"},{"role":"user","content":"what is your name?"}]
}'
```
The key in auth header is an api key generated via /key/generate, not master key. If I pass master key instead, it returns 400 bad request. The model is deployed in Azure OpenAI.

The response is 401 for above request:
```
content-length: 240
content-type: application/json
{
	"error": {
		"message": "Authentication Error, Only master key can be used to generate, delete, update info for new keys/users/teams. Route=/openai/deployments/gpt-35-turbo/chat/completions",
		"type": "auth_error",
		"param": "None",
		"code": 401
	}
}
```

But the following call works:
```
curl --request POST \
  --url https://llm-proxy.xyz.com/chat/completions \
  --header 'Authorization: Bearer sk-7A...peQ' \
  --header 'Content-Type: application/json' \
  --data ' {
        "model": "gpt-35-turbo",
        "messages": [{"role":"system","content":"you are a helpful assistant"},{"role":"user","content":"what is your name?"}]
    }'
```
The response is 200:
```
{
	"id": "chatcmpl-9JnxDbAu4dQNwic4",
	"choices": [
		{
			"finish_reason": "stop",
			"index": 0,
			"message": {
				"content": "I am an AI language model created by OpenAI, and do not have a personal name. You can simply refer to me as \"assistant.\" How can I assist you today?",
				"role": "assistant"
			}
		}
	],
	"created": 1714507283,
	"model": "gpt-35-turbo",
	"object": "chat.completion",
	"system_fingerprint": null,
	"usage": {
		"completion_tokens": 36,
		"prompt_tokens": 21,
		"total_tokens": 57
	}
}
```

### Relevant log output

_No response_

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by msabramo**
by moving code around so that the `chat_completion` route is defined before the `completion` route. This is necessary because the `chat_completion` route is more specific than the `completion` route, and [the order of route definitions matters in FastAPI](https://fastapi.tiangolo.com/tutorial/path-params/#order-matters).

Without this, doing a request to
`/openai/deployments/{model_in_url}/chat/completions` might trigger `completion` being called (with `model` set to `{model_in_url}/chat` instead of `chat_completion` getting called, which is the correct function.

#### Before

```shell
$ curl --request POST \
  --url 'http://127.0.0.1:4000/openai/deployments/gpt-4-1106-preview/chat/completions' \
  --header "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
  --header 'Content-Type: application/json' \
  --data '{
  "messages": [{"role":"system","content":"you are a helpful assistant named Michaelangelo who answers questions about art"},{"role":"user","content":"what is your name? What can you help with?"}]
}'
{"error":{"message":"400: {'error': 'Invalid model name passed in model=gpt-4-1106-preview/chat'}","type":"None","param":"None","code":400}}
```

Note that the value of `model` here is `'gpt-4-1106-preview/chat'`. This is because the `completion` function appears first in the source code and so the first route match is `"/openai/deployments/{model:path}/completions"` and `model` gets set to `'gpt-4-1106-preview/chat'`

and in the console:

```
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/Users/abramowi/Code/OpenSource/litellm/litellm/proxy/proxy_server.py", line 3486, in completion
    raise HTTPException(
fastapi.exceptions.HTTPException: 400: {'error': 'Invalid model name passed in model=gpt-4-1106-preview/chat'}
INFO:     127.0.0.1:51698 - "POST /openai/deployments/gpt-4-1106-preview/chat/completions HTTP/1.1" 400 Bad Request
```

#### After

```shell
$ curl --request POST \
  --url 'http://127.0.0.1:4000/openai/deployments/gpt-4-1106-preview/chat/completions' \
  --header "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
  --header 'Content-Type: application/json' \
  --data '{
  "messages": [{"role":"system","content":"you are a helpful assistant named Michaelangelo who answers questions about art"},{"role":"user","content":"what is your name? What can you help with?"}]
}'
{"id":"chatcmpl-9JsRbVVaRha8Qkiw9P4zP1TFugr0N","choices":[{"finish_reason":"stop","index":0,"message":{"content":"My name is Michaelangelo, named after the famous Renaissance artist, Michelangelo Buonarroti. I can help answer your questions about art, including art history, famous artworks, artists, techniques, movements, and much more. Whether you're looking for information on a particular painting, advice on art-related topics, or insights into the art world, feel free to ask!","role":"assistant"}}],"created":1714524543,"model":"gpt-4","object":"chat.completion","system_fingerprint":"fp_2f57f81c11","usage":{"completion_tokens":76,"prompt_tokens":35,"total_tokens":111}}
```

Fixes: GH-3372

Cc: @taralika

### CODE REVIEW

**Review by taralika — APPROVED** [review]

**Comment by ghost** [comment]
Thanks for this @msabramo 

Is there a test we can add here - https://github.com/BerriAI/litellm/blob/main/tests/test_openai_endpoints.py

to prevent any future regressions?

---

P.S.: Would love to setup a 1:1 support channel for y'all, to move quicker on issues. 

- Discord: https://discord.com/invite/wuPM9dRgDw
- LinkedIn: https://www.linkedin.com/in/krish-d/
- Slack: krrishdholakia@gmail.com (and Ishaan's is ishaanjaffer0324@gmail.com)

Let me know what works best!

**Comment by msabramo** [comment]
> Is there a test we can add here - https://github.com/BerriAI/litellm/blob/main/tests/test_openai_endpoints.py

Hi @krrishdholakia, I'd love to add a test but I'm having trouble getting the tests to run, so maybe you can help with that?

```shell
abramowi at Marcs-MacBook-Pro-3 in ~/Code/OpenSource/litellm (GH-3372●●)
$ poetry run pytest tests/test_openai_endpoints.py
...
------------------------------------------------------------ Captured stdout call ------------------------------------------------------------
{"error":{"message":"Authentication Error, Connect Proxy to database to generate keys - https://docs.litellm.ai/docs/proxy/virtual_keys ","type":"auth_error","param":"None","code":400}}

========================================================== short test summary info ===========================================================
FAILED tests/test_openai_endpoints.py::test_chat_completion - Exception: Request did not return a 200 status code: 400
FAILED tests/test_openai_endpoints.py::test_chat_completion_ratelimit - Failed: Wrong error received - Request did not return a 200 status code: 400
FAILED tests/test_openai_endpoints.py::test_chat_completion_different_deployments - Exception: Request did not return a 200 status code: 400
FAILED tests/test_openai_endpoints.py::test_chat_completion_streaming - openai.BadRequestError: Error code: 400 - {'error': {'message': {'error': 'Invalid model name passed in model=gpt-3.5-turbo-large'}, 'typ...
FAILED tests/test_openai_endpoints.py::test_chat_completion_old_key - Exception: Request did not return a 200 status code: 400
FAILED tests/test_openai_endpoints.py::test_completion - Exception: Request did not return a 200 status code: 400
FAILED tests/test_openai_endpoints.py::test_embeddings - Exception: Request did not return a 200 status code: 400
FAILED tests/test_openai_endpoints.py::test_image_generation - Exception: Request did not return a 200 status code: 400
FAILED tests/test_openai_endpoints.py::test_openai_wildcard_chat_completion - Exception: Request did not return a 200 status code: 400
============================================================= 9 failed in 0.55s ==============================================================
```

After struggling with this for a bit, I noticed that the `README.md` actually recommends running the tests in a directory:

```shell
cd litellm/tests # pwd: Documents/litellm/litellm/tests
poetry run flake8
poetry run pytest .
```

but that fails too:

```shell
abramowi at Marcs-MacBook-Pro-3 in ~/Code/OpenSource/litellm (GH-3372●●)
$ cd litellm/tests
poetry run flake8
poetry run pytest .
...
========================================================== short test summary info ===========================================================
ERROR test_azure_perf.py - openai.OpenAIError: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_...
ERROR test_config.py - ValueError: api_base is required for Azure OpenAI. Set it on your config. Model - {'model_name': 'gpt-3.5-turbo', 'litellm_params': {'mod...
ERROR test_model_alias_map.py - Failed: Error occurred: AnyscaleException - Traceback (most recent call last):
ERROR test_multiple_deployments.py - Failed: An exception occurred: 'NoneType' object has no attribute '_response_ms'
ERROR test_register_model.py - Failed: An error occurred: OpenAIException - Traceback (most recent call last):
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================= 36 warnings, 5 errors in 2.02s =======================================================
```

What's the best, cleanest way to get the tests running?

Ideally all of them, but especially `tests/test_openai_endpoints.py`.

**Comment by ghost** [comment]
@msabramo 
> poetry run pytest .

Can you try just running it on your specific test 

for e.g. if it's in test_openai_endpoints, then `pytest test_openai_endpoints.py::<my-test-name>` 


Once that works, can you rename your branch to start with `litellm_`. Our ci/cd suite will pick it up then, and we can catch any other issues raised as well.

**Comment by msabramo** [comment]
Added a test in 152b5c8c.

**Comment by msabramo** [comment]
Created a branch that starts with `litellm_` - https://github.com/msabramo/litellm/tree/GH-3372 - but the branch is in my fork, so I doubt that your CI will run on that? I have a feeling that you will need to push the branch to `origin` for your CI to run on it?

**Comment by ghost** [comment]
Got it - we probably need a better solution for this. 

For now though, @msabramo can you confirm this passes your testing? screenshot works

**Comment by msabramo** [comment]
> For now though, @msabramo can you confirm this passes your testing? screenshot works

Yep, with 4dfadb0cf, I get this:

Screenshot 2024-05-02 at 12 24 26 PM

**Comment by ghost** [comment]
LGTM! Thanks for the work on this @msabramo

**Comment by msabramo** [comment]
No problem. I have a follow-up coming soon that improves the testing in `test_proxy_server.py`...

**Comment by msabramo** [comment]
> No problem. I have a follow-up coming soon that improves the testing in `test_proxy_server.py`...

https://github.com/BerriAI/litellm/pull/3406 is what I alluded to.

**Pull request merged**
