### PR TITLE
fix(ci): set up QEMU and Buildx for multi platform images

### PR DESCRIPTION
**Pull request by adrien-f**
Follow up of https://github.com/BerriAI/litellm/pull/2060 which is missing some actions

### CODE REVIEW

**Comment by adrien-f** [comment]
@ishaan-jaff I'm not sure if there's a process to run this in a branch or you have to merge it first ?

**Comment by adrien-f** [comment]
According to other projects I looked at, it appears to do to the trick

**Comment by ishaan-jaff** [comment]
Looks good, will retry with this PR and see if it fixes it

**Comment by ishaan-jaff** [comment]
This fixed the issue @adrien-f Thanks so much ! 

https://github.com/BerriAI/litellm/pkgs/container/litellm/180805924?tag=main-latest

**Comment by adrien-f** [comment]
Awesome! The `unknown/unknown` is a bit weird, it might be the `local` parameter 😅 

image

**Comment by ishaan-jaff** [comment]
yeah @adrien-f curious are you using the litellm proxy today ?

**Pull request merged**
