### PR TITLE
added test for interface to ollama

### PR DESCRIPTION
**Pull request by m-c-frank**

### CODE REVIEW

**Comment by ghost** [comment]
@m-c-frank how would this work on circle-ci?

**Comment by ghost** [comment]
we already have a local ollama test - https://github.com/BerriAI/litellm/blob/5e5ffc3d8a10a7dd180a601f8f9a1cab741a2af9/litellm/tests/test_ollama_local.py#L4

**Comment by m-c-frank** [comment]
sorry my autonomous agent decided it was a good idea to somehow create a fork and then submit a pull request.

whoops

at least i now know that this partly works

thanks for the feedback, ill improve the system!

**Comment by ghost** [comment]
no worries.

**Pull request closed without merging**
