### PR TITLE
Adds "pre-fill" support for Claude

### PR DESCRIPTION
**Pull request by spdustin**
Claude allows you to "put words in its mouth" to ensure it always begins its response in a particular way. For example, to improve its ability to return JSON without any introductory prose, you can end your completion request with:

```
Assistant: {
```

This PR updates the prompt factory for Claude models to check for an "assistant" role in the final message in the array of messages. If it exists, it will no longer add an empty `Assistant: ` prompt.

### CODE REVIEW

**Comment by spdustin** [comment]
I'll note that I didn't update the documentation for this, but I'm happy to.

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
can you add a test for this under `litellm/tests` ? Want to ensure we don't push regressions for this

**Comment by ghost** [comment]
This is a great pr! Thanks for your work @spdustin

**Comment by spdustin** [comment]
> can you add a test for this under `litellm/tests` ? Want to ensure we don't push regressions for this

You bet. I'll update the docs, too.

**Comment by spdustin** [comment]
I added tests for several variations of `messages` for both anthropic factories (and fixed the test for codellama that was sitting in there). I also updated the docs for Bedrock and Anthropic to show examples of using `system` role messages as well as the `assistant` "pre-fill".

**Comment by spdustin** [comment]
Sorry, snuck one more in there. Claude 2.1 was added to the supported models table in the bedrock docs. So hold off on the merge, because an update is needed to the factory.

**Comment by spdustin** [comment]
Okay, now it's good. Test added and run. I had to add boto3 to my `pyproject.toml` to complete the tests in `test_bedrock_completion.py`, fyi.

```
calling bedrock claude 2.1 completion params auth
ModelResponse(id='chatcmpl-f4f5ee03-8530-4c29-aad6-bd31e7588f43', choices=[Choices(finish_reason='stop', index=0, message=Message(content=' Here is a short poem about the sky:', role='assistant'))], created=1704497767, model='anthropic.claude-v2:1', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=14, completion_tokens=9, total_tokens=23), finish_reason='max_tokens')
```

**Review by ishaan-jaff — APPROVED** [review]
amazing !!! thank so much for your contribution

**Comment by ishaan-jaff** [comment]
will merge after our existing ci/cd passes testing

**Comment by spdustin** [comment]
> will merge after our existing ci/cd passes testing

Is that the workflow that's currently on hold?

**Pull request merged**
