### PR TITLE
[Feat] Observability integration - Opik by Comet

### PR DESCRIPTION
**Pull request by jverre**
## Title

Added Comet's Opik open-source observability integration for logging and evaluation.

For more information on Opik, see: https://github.com/comet-ml/opik

Hope you find this useful!

## Type

🆕 New Feature

## Changes
The integration was implemented following the Langsmith and Datadog integration.

1. Adds documentation: docs/my-website/docs/observability/opik_integration.md
2. Lists Opik in sidebar
3. Adds the integration: litellm/integrations/opik/opik.py
4. Added tests: tests/local_testing/test_opik.py 

### UI Changes
Screenshot 2024-10-04 at 13 07 40
 a screenshot/GIF of working UI fixes

## Testing
All tests pass:

```
pytest tests/local
```

Screenshot 2024-10-04 at 12 59 04

### CODE REVIEW

**Comment by jverre** [comment]
@ishaan-jaff @krrishdholakia I've created a new PR with the updated Opik integration that I have based on the Langsmith and Datadog integration. It also do not depend on the Opik SDK anymore and uses the new `CustomBatchLogger` method.

I did find an issue though with this approach, today the Opik integration proposed here and the existing Langsmith integration fails when it is not run in an async framework. Running the following code (taken from the documentation):

```python
import litellm
import os

os.environ["LANGSMITH_API_KEY"] = ""
os.environ["LANGSMITH_PROJECT"] = "" # defaults to litellm-completion
os.environ["LANGSMITH_DEFAULT_RUN_NAME"] = "" # defaults to LLMRun
# LLM API Keys
os.environ['OPENAI_API_KEY']=""

# set langsmith as a callback, litellm will send the data to langsmith
litellm.success_callback = ["langsmith"] 
 
# openai call
response = litellm.completion(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": "Hi 👋 - i'm openai"}
  ]
)
```

Returns the following error:
```
  File "/Users/jacquesverre/Documents/code/litellm/litellm/litellm_core_utils/litellm_logging.py", line 2164, in _init_custom_logger_compatible_class
    _langsmith_logger = LangsmithLogger()
                        ^^^^^^^^^^^^^^^^^
  File "/Users/jacquesverre/Documents/code/litellm/litellm/integrations/langsmith.py", line 96, in __init__
    asyncio.create_task(self.periodic_flush())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py312_llm_eval/lib/python3.12/asyncio/tasks.py", line 417, in create_task
    loop = events.get_running_loop()
```
There is a similar issue when using the OpikLogger and the DatadogLogger.

How would you like to solve this issue ?

**Comment by ghost** [comment]
if there's no running event loop, couldn't you use `asyncio.run` here? I think we had to solve a similar issue for streaming logging - https://github.com/BerriAI/litellm/blob/0c9c42915f72c28388fcd06c03a1ea2b776c6fe0/litellm/utils.py#L8116

**Comment by jverre** [comment]
@krrishdholakia I took a look and I wasn't able to get it working as from what I understand the periodic_flush function runs indefinitely.
I'm a little out of my depth so looping in @Lothiraldan that is much more knowledgeable than me on these topics

**Comment by Lothiraldan** [comment]
Hi @krrishdholakia, thanks for the suggestion. I don’t think we can use `asyncio.run` here because it would block the current thread until `periodic_flush` finishes, which won't ever happen since it's an infinite loop. To solve this, we'd need to move it into a separate thread.

Mixing `asyncio` with threads can get tricky. It requires careful handling to avoid deadlocks, minimize latency (both for the main thread and the logger), and prevent data loss for the logger. Implementing and maintaining this would involve a fair amount of code and complexity.

I wanted to check if you're comfortable with this level of complexity moving forward or if we should explore other alternatives.

**Comment by Lothiraldan** [comment]
After reviewing the Datadog integration, we noticed that it sends events synchronously in `log_success_event` (https://github.com/BerriAI/litellm/blob/main/litellm/integrations/datadog/datadog.py#L187-L193) while relying on `CustomBatchLogger` for asyncio-based workflows. We're planning to update the PR to follow a similar approach.

Let us know if this works for you or if you'd prefer a different direction.

**Comment by ishaan-jaff** [comment]
@Lothiraldan  yes that works - thanks

**Comment by jverre** [comment]
@ishaan-jaff @krrishdholakia Thanks for the feedback. I've updated the PR and added a new test scenario for `litellm.completion` calls in the SDK, so we should be good to go. Let me know what you think and happy to make any other changes

**Review by ishaan-jaff — APPROVED** [review]
LGTM thanks for working with us on this @jverre

**Comment by ishaan-jaff** [comment]
hi @jverre @Lothiraldan - can we add LiteLLM on the Opik docs too - on this section 

https://www.comet.com/docs/opik/ 

Screenshot 2024-10-10 at 6 29 57 PM

**Comment by Lothiraldan** [comment]
@ishaan-jaff Thank you, now that it is merged, we can push the docs and cookbooks on our side.

~~I don't think it's part of a release yet, right? Does users usually install LiteLLM from Pypi or from the source directly?~~

Edit: I saw that you are making release on daily basis my bad, we are gonna have the docs ready by tomorrow!

**Comment by ishaan-jaff** [comment]
@Lothiraldan  majority of users use LiteLLM through our Proxy / gateway - can we make sure that's on the Comet ml docs. Happy to connect on Linkedin re this: https://www.linkedin.com/in/reffajnaahsi/

**Comment by Lothiraldan** [comment]
@ishaan-jaff We will make sure to highlight the LiteLLM proxy in our Comet ml docs

**Comment by jverre** [comment]
@ishaan-jaff Docs have been released: https://www.comet.com/docs/opik/tracing/integrations/litellm with a section for both the Python SDK and the proxy docs

Thanks for all the help on the integration

**Pull request merged**
