### PR TITLE
Create GitHub Action to automatically build docker images

### PR DESCRIPTION
**Pull request by coconut49**
Hi there,

I wanted to let you know that this PR is essentially the same as https://github.com/BerriAI/litellm/pull/634. However, I regret to inform you that I had misconfigured the Github Pull App, which caused the changes to be purged by the Pull Bot before the code merge. I have since removed the Bot and am resubmitting the code once more.

Would it be possible for you to create a docker build in GitHub Action after the code merge? It would be greatly appreciated.

Thank you.

### CODE REVIEW

**Comment by ghost** [comment]
Hey @coconut49 what does 
>create a docker build in GitHub Action

mean?

**Comment by coconut49** [comment]
Hi @krrishdholakia Could you kindly navigate to https://github.com/BerriAI/litellm/actions/workflows/docker.yml and click on the `Run workflow` button, please? Because I'm not a maintainer, I don't have access to trigger workflows.

image

**Comment by SlapDrone** [comment]
+1 here, would be great if y'all published the package @krrishdholakia! :smile:

**Comment by ghost** [comment]
done @coconut49 
Screenshot 2023-10-20 at 11 33 42 AM

@SlapDrone / @coconut49 any help understanding why y'all are doing this would be great, so we can actually make this better for your use-case. 

attaching my calendly, even a 10 minute chat on this would help a lot - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat.

**Comment by ghost** [comment]
fyi - @coconut49 @SlapDrone there was an issue with the build 

Screenshot 2023-10-20 at 12 11 54 PM

**Comment by ghost** [comment]
what's the right naming scheme for docker images?

**Comment by ghost** [comment]
cc: @ishaan-jaff i think you've worked on this

**Comment by SlapDrone** [comment]
> what's the right naming scheme for docker images?

@krrishdholakia lowercase (berriai) and I think typically for ghcr the tag should match the branch, so `main`, but I am not an expert on ghcr, so perhaps it's possible to change this behaviour.


> done @coconut49 Screenshot 2023-10-20 at 11 33 42 AM
> 
> @SlapDrone / @coconut49 any help understanding why y'all are doing this would be great, so we can actually make this better for your use-case.
> 
> attaching my calendly, even a 10 minute chat on this would help a lot - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat.

Sorry I am in the absolute worst time zone for this haha!

But hopefully it's simple enough: At least for me the use-case is literally just to be able to pull (an up-to-date) litellm directly from a docker repository (i.e. `docker pull ghcr.io/.../litellm:main`) rather than clone this repo and build the image locally. This means I can just have litellm set up for example as a service in a docker-compose file.

**Comment by ghost** [comment]
@SlapDrone thanks. 


What does: 
> litellm set up for example as a service in a docker-compose file.
mean? 

Is this our simple-proxy that you're trying to spin up? https://github.com/BerriAI/litellm/tree/main/openai-proxy?

**Comment by ghost** [comment]
Hey @coconut49 @SlapDrone got an image deployed - https://github.com/orgs/BerriAI/packages/container/package/litellm

Will formalize this into a proper workflow

**Comment by coconut49** [comment]
> > what's the right naming scheme for docker images?
> 
> @krrishdholakia lowercase (berriai) and I think typically for ghcr the tag should match the branch, so `main`, but I am not an expert on ghcr, so perhaps it's possible to change this behaviour.
> 
> > done @coconut49 Screenshot 2023-10-20 at 11 33 42 AM
> > @SlapDrone / @coconut49 any help understanding why y'all are doing this would be great, so we can actually make this better for your use-case.
> > attaching my calendly, even a 10 minute chat on this would help a lot - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat.
> 
> Sorry I am in the absolute worst time zone for this haha!
> 
> But hopefully it's simple enough: At least for me the use-case is literally just to be able to pull (an up-to-date) litellm directly from a docker repository (i.e. `docker pull ghcr.io/.../litellm:main`) rather than clone this repo and build the image locally. This means I can just have litellm set up for example as a service in a docker-compose file.

Hi @krrishdholakia I have merged the https://github.com/BerriAI/litellm/pull/678 . Can you try to create a docker build in GitHub Action again?

**Comment by SlapDrone** [comment]
+1, will be super nice to get the CI pipeline publishing packages regularly.

**Pull request merged**
