### PR TITLE
add deepeval testing

### PR DESCRIPTION
**Pull request by jwongster2**

### CODE REVIEW

**Comment by ghost** [comment]
Hey @ColabDog  - how do you use the longer_context_model_fallback_dict, ContextWindowExceededError? 
Screenshot 2023-09-29 at 1 54 18 PM

it's not clear to me how those are used in your code example

**Comment by ghost** [comment]
Screenshot 2023-09-29 at 1 55 03 PM

what is `test_quickstart.py`?

**Comment by ghost** [comment]
Screenshot 2023-09-29 at 1 55 44 PM

i'm confused what these functions actually do

**Comment by ghost** [comment]
this looks like something that would be helpful to have on deepeval docs b/c my instinct is to try and figure out what these things mean

**Comment by ishaan-jaff** [comment]
@ColabDog any update on this ?

**Pull request closed without merging**
