### PR TITLE
fix commit for sql injection in api key

### PR DESCRIPTION
**Pull request by CodeVigilanteOfficial**
## Relevant issues
https://huntr.com/bounties/491e4884-0306-4cd4-8fe2-9a19de33bf5c

## Type

🐛 Bug Fix

## Changes

sql query changed for fixing the vulnerability

### CODE REVIEW

**Comment by Manouchehri** [comment]
Why has the entire file been changed?

**Comment by CodeVigilanteOfficial** [comment]
[image: image.png]

Le ven. 31 mai 2024 à 16:03, David Manouchehri ***@***.***> a
écrit :

**Comment by Manouchehri** [comment]
> [image: image.png]

that's just a filename =P

**Comment by CodeVigilanteOfficial** [comment]
ahah sorry
https://ibb.co/SnhCdb2

Le ven. 31 mai 2024 à 16:10, David Manouchehri ***@***.***> a
écrit :

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
Thanks for the PR. I saw the screenshot of the code changes but github is showing the entire file as changed. Please can you limit the changes to what you're screenshot is sharing @CodeVigilanteOfficial

**Comment by ishaan-jaff** [comment]
`13,653 additions, 13,656 deletions not shown because the diff is too large. Please use a local Git client to view these changes.` 

I see this @CodeVigilanteOfficial

**Comment by ghost** [comment]
Fixed - https://github.com/BerriAI/litellm/commit/f75c15d6cd535aa78014378ad532de1df6be2f56

thanks @CodeVigilanteOfficial

**Comment by Manouchehri** [comment]
Was this actually ever reachable? It seems like an admin would have to create a key that contained the SQL injection text.

**Comment by ghost** [comment]
i don't think so. 

we also run the `sk-` on user_api_key_auth which occurs before this

**Pull request closed without merging**
