### PR TITLE
Fix Greenscale Documentation

### PR DESCRIPTION
**Pull request by greenscale-nandesh**
@krrishdholakia, my previous PR didn't add the documentation correctly to the sidebar; my apologies. This PR fixes sidebar reference to Greenscale documentation.

### CODE REVIEW

**Comment by ghost** [comment]
Just checked out the link - https://greenscale.ai/

How does a user actually use this? 
Screenshot 2024-04-24 at 2 04 57 PM

**Comment by greenscale-nandesh** [comment]
@krrishdholakia When onboarding users, we will work closely with them and provide all the details they need to set up.

**Comment by ishaan-jaff** [comment]
@greenscale-nandesh can you resolve merge conflicts

**Comment by greenscale-nandesh** [comment]
@ishaan-jaff Conflicts have been resolved. Thank you for the review.

**Pull request merged**
