### PR TITLE
updated oobabooga to new api and support for embeddings

### PR DESCRIPTION
**Pull request by danikhan632**
the current implementation uses the old api which has now been deprecated and the openai interface is the default one any my fork adjusts completions function for that. 

Additionally it also implements the embeddings function for oobabooga

### CODE REVIEW

**Comment by ghost** [comment]
LGTM! @danikhan632 why are you using litellm with oobabooga? It's already openai-compatible

**Comment by danikhan632** [comment]
> LGTM! @danikhan632 why are you using litellm with oobabooga? It's already openai-compatible

I may have told you about this a while ago however I suppose I did it to make it easier as I am currently working on adding function calling support using guidance and I wanted to also be able to use it with oobabooga. 

```python
def function_call_prompt(messages: list, functions: list):
#todo: use guidance to implement this function
```

**Comment by ghost** [comment]
And since oobabooga doesn't support function calling, you're trying to use litellm to do that? 


so is it 
`guidance -> litellm -> oobabooga`?

**Comment by danikhan632** [comment]
> And since oobabooga doesn't support function calling, you're trying to use litellm to do that?
> 
> so is it `guidance -> litellm -> oobabooga`?

I suppose so but not just oobabooga but also all the other models

see #1258 as I have already pushed semi working implementation that uses LlamaCpp as of now but is a work in progress

**Pull request merged**
