### PR TITLE
Add missing tool_calls and name to messages

### PR DESCRIPTION
**Pull request by elisalimli**
I have added missing tool_calls and name (tool name) attributes to messages array for Mistral API. It is needed to add function calls to messages array before passing the function call result.

### CODE REVIEW

**Comment by ghost** [comment]
hey @elisalimli can you add testing for this in `test_completion.py` 

similar to this - https://github.com/BerriAI/litellm/blob/f89f8a415782da5504da4a0437465c555dae2e3f/litellm/tests/test_completion.py#L164

**Comment by ghost** [comment]
or if you can give me an example of the issue and the required asserts, i can do it @elisalimli

**Comment by elisalimli** [comment]
> hey @elisalimli can you add testing for this in `test_completion.py`
> 
> similar to this -
> 
> https://github.com/BerriAI/litellm/blob/f89f8a415782da5504da4a0437465c555dae2e3f/litellm/tests/test_completion.py#L164

Right. I have added tests to test_completion.py and test_streaming.py in [319e006](https://github.com/BerriAI/litellm/pull/3124/commits/319e006d13d66a27f7850d7fc57815a99f874716) and [e404dd7](https://github.com/BerriAI/litellm/pull/3124/commits/e404dd756946b7a91a1dddd86a72fa9c7b1f1ec2) accordingly.

**Comment by homanp** [comment]
hey @krrishdholakia would be amazing if we could get this released ASAP! Thanks!

**Comment by ghost** [comment]
LGTM! Thanks for the bump @homanp

**Comment by ghost** [comment]
will take care of fixing any issues which show up on ci/cd

**Pull request merged**
