### PR TITLE
Fix failing tests on PR-4760

### PR DESCRIPTION
**Pull request by skucherlapati**
## Title

Fixing failing test due to https://github.com/BerriAI/litellm/pull/4760
Related to #4759 

## Type

🐛 Bug Fix
✅ Test

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
image

### CODE REVIEW

**Review by ishaan-jaff — APPROVED** [review]
lgtm thanks for being proactive on this. Is it good to merge ?

**Comment by skucherlapati** [comment]
@ishaan-jaff - I fixed the test that was failing due to the new additions I made in previous PR linked in the description.

**Comment by skucherlapati** [comment]
Yeah the new test is passing locally.

**Comment by skucherlapati** [comment]
> lgtm thanks for being proactive on this. Is it good to merge ?

Yeah the new test is passing locally.

**Comment by ishaan-jaff** [comment]
still failing :( @skucherlapati 
Screenshot 2024-07-17 at 8 15 39 PM

**Comment by ishaan-jaff** [comment]
It fails for me locally too - please can you look into this @skucherlapati 

link to failing test: https://app.circleci.com/pipelines/github/BerriAI/litellm/12650/workflows/e95e8c33-2a6b-4bb4-81a7-9c6c2727533f/jobs/30521/tests#failed-test-0

**Comment by skucherlapati** [comment]
> It fails for me locally too - please can you look into this @skucherlapati
> 
> link to failing test: https://app.circleci.com/pipelines/github/BerriAI/litellm/12650/workflows/e95e8c33-2a6b-4bb4-81a7-9c6c2727533f/jobs/30521/tests#failed-test-0

Yeah I saw that the test is failing. I think the additions to json files were deleted and my local main (which has the changes from merge) is different from latest changes. My bad.

**Comment by skucherlapati** [comment]
@ishaan-jaff : Added the lines back in this PR - https://github.com/BerriAI/litellm/pull/4766.

**Pull request merged**
