### PR TITLE
Exclude /docs to reduce Docker image size

### PR DESCRIPTION
**Pull request by Hitro147**
This PR introduces a `.dockerignore` file with an entry to exclude the `/docs` directory from Docker builds. By doing so, it aims to reduce the Docker image size, leading to improved build performance and efficiency.

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Awesome PR - this will really help our docker builds

**Comment by ishaan-jaff** [comment]
Can you also ignore

- cookbook
- .circleci
- .github
- tests

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
Can you also ignore

cookbook
.circleci
.github
tests

**Comment by Hitro147** [comment]
@ishaan-jaff, I've updated the PR to include the additional directories. Thanks!

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
last request before merging - can you run a `docker build` + `docker run` with these changes. Just to ensure litellm builds correctly ?

**Comment by Hitro147** [comment]
@ishaan-jaff, I've successfully executed the Docker build and run as per the last request. During this process, an issue was encountered, which seems related to configuration settings external to our `.dockerignore` adjustments. Specifically, it appears tied to the setup of necessary API credentials. Other than this all seems in order with the changes made.

image

**Review by ishaan-jaff — APPROVED** [review]

**Comment by ishaan-jaff** [comment]
Awesome !

**Comment by Hitro147** [comment]
Thank you very much for giving this opportunity to contribute ❤️

**Pull request merged**
