### PR TITLE
✨ Refresh Helm chart structure

### PR DESCRIPTION
**Pull request by Lunik**
The goal of this PR is to make a refresh of the Helm chart to the newest version.

# Notable changes

## Features

- Upgrade the app to `v1.24.5`
- Documentation on how to deploy with Helm

## Fixes

- Add the Helm release as prefix of secrets (db + masterkey)
- Helm test connection pod

## Breaking changes

- Rename the chart to `litellm`
- Remove the `ui` specific resources and related docs
- Remove the `-proxy` suffix on resources
- Disable ingress deployment by default

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@Lunik is there a way we can test our helm chart to ensure we don't have future regressions ? 

I want to make sure it stays in sync and is usable

**Comment by Lunik** [comment]
Yes, the simpler way to do it only require a standalone Kubernetes cluster (Docker Desktop or Rancher Desktop)

Then follow, the updated deployment in the documentation : `./docs/my-website/docs/proxy/deploy.md`

And run `helm test mydeploy` to verify that the service is working

In the futur, you can add more tests in `deploy/charts/litellm/templates/tests` directory.

==

Also, when publishing a new release of Litellm, don't forget to update the `appVersion` in `deploy/charts/litellm/Chart.yaml`

I have seen that there are GitHub actions to publish the Helm chart, not sure if they work. If possible, in the future, it could be interresting to publish the Helml chart as a repo using GitHub pages see : https://helm.sh/docs/howto/chart_releaser_action/

**Comment by ishaan-jaff** [comment]
> And run helm test mydeploy to verify that the service is working

I think we'll need to automate this 

> Also, when publishing a new release of Litellm, don't forget to update the appVersion in deploy/charts/litellm/Chart.yaml

This too, we push 1-2 new releases / day, so def will need to be automated

**Review by ishaan-jaff — APPROVED** [review]

**Comment by ShaunMaher** [comment]
@ishaan-jaff 
> This too, we push 1-2 new releases / day, so def will need to be automated

If the "Build, Publish LiteLLM Helm Chart. New Release" Github Action is used, the appVersion is automatically updated (well, it should be).

**Comment by ShaunMaher** [comment]
> Rename the chart to litellm

The reason I added the "-helm" suffix was to avoid a conflict when it is published to the ghcr.  When I published the chart with the name "litellm" it replaced the docker image in the registry called "litellm".  Adding the suffix was my solution.  This was my first foray into GitHub Actions though so better solutions doubtlessly exist.

> If possible, in the future, it could be interresting to publish the Helml chart as a repo using GitHub pages...

I deliberately tried to avoid this additional overhead by pushing to the OCI registry instead.

**Pull request merged**
