### PR TITLE
Proxy: Add `x-litellm-call-id` HTTP response header

### PR DESCRIPTION
**Pull request by msabramo**
This gives the value of `logging_obj.litellm_call_id` and one particular use of this is to correlate the HTTP response from a request with a trace in an LLM logging tool like Langfuse, Langsmith, etc.

For example, if a user in my environment (w/ Langfuse) gets back this in the response headers:

```
x-litellm-call-id: ffcb49e7-bd6e-4e56-9c08-a7243802b26e
```

then they know that they can see the trace for this request in Langfuse by visiting https://langfuse.domain.com/trace/ffcb49e7-bd6e-4e56-9c08-a7243802b26e

They can also use this ID to submit scores for this request to the Langfuse scoring API. In other words, they can POST to https://langfuse.domain.com/api/public/scores with something like this to score a response:

```json
{
	"traceId": "ffcb49e7-bd6e-4e56-9c08-a7243802b26e",
	"name": "answer_correctness",
	"value": 0.95,
	"comment": "This answer is great!"
}
```

This is a potential replacement for https://github.com/BerriAI/litellm/pull/4132

Cc: @krrishdholakia, @databill86

### CODE REVIEW

**Comment by msabramo** [comment]
I decided to use an HTTP header instead of adding to the JSON for a few reasons:

- LiteLLM already adds a bunch of headers and I like following established patterns 
- You can’t modify JSON if response is not JSON - e.g.: image or audio
- Messing with JSON more likely to cause problems for clients not expecting this.

**Comment by msabramo** [comment]
This is better than #4132 because it does its work in centralized proxy code instead of in the Langfuse logger, which is one of many loggers and also loggers run in threads, which means that modifying the response in the logger is strange and probably likely to fail sometimes because of race conditions.

**Comment by msabramo** [comment]
The thing that would be cool to add but I haven’t been able to figure out is if each logger (ex. Langfuse, Langsmith) could have a method that given the call_id, returns a list or dict with (name, URL) pairs for that call. Then the code could iterate through the loggers and if there are any loggers that define such a method it can get the URLs and add them to headers - ex. 

```
x-litellm-langfuse-trace-url: https://langfuse.domain.com/trace/ffcb49e7-bd6e-4e56-9c08-a7243802b26e
```

But this could be done in a separate PR. I wouldn’t let this idea delay the merging of this PR.

**Comment by msabramo** [comment]
@krrishdholakia @ishaan-jaff: Thoughts on this one?

**Comment by ghost** [comment]
hey @msabramo re: langfuse trace - we actually have built this already - https://github.com/BerriAI/litellm/blob/ff3f3ed933c3e32ae682bc14c886407f6112590a/litellm/litellm_core_utils/litellm_logging.py#L1779

it's how we get the langfuse trace for a slack alert

**Comment by msabramo** [comment]
Oops I think there's a bug for `/completion`:

```
$ curl -i -sSL --request POST \
  --url 'http://0.0.0.0:4000/completions' \
  --header "Authorization: Bearer ${LLM_PROXY_API_KEY}" \
  --header 'Content-Type: application/json' \
  --header 'LiteLLM-Disable-Message-Redaction: true' \
  --data '{
  "model": "gpt-35-turbo-1106",
  "prompt": "Name 5 colors"
}'
HTTP/1.1 500 Internal Server Error
date: Fri, 12 Jul 2024 05:12:13 GMT
server: uvicorn
content-length: 97
content-type: application/json

{"error":{"message":"name 'logging_obj' is not defined","type":"None","param":"None","code":500}}
```

**Comment by msabramo** [comment]
> Oops I think there's a bug for `/completion`:
> 
> ```
> $ curl -i -sSL --request POST \
>   --url 'http://0.0.0.0:4000/completions' \
>   --header "Authorization: Bearer ${LLM_PROXY_API_KEY}" \
>   --header 'Content-Type: application/json' \
>   --header 'LiteLLM-Disable-Message-Redaction: true' \
>   --data '{
>   "model": "gpt-35-turbo-1106",
>   "prompt": "Name 5 colors"
> }'
> HTTP/1.1 500 Internal Server Error
> date: Fri, 12 Jul 2024 05:12:13 GMT
> server: uvicorn
> content-length: 97
> content-type: application/json
> 
> {"error":{"message":"name 'logging_obj' is not defined","type":"None","param":"None","code":500}}
> ```

@krrishdholakia: Check out https://github.com/BerriAI/litellm/pull/4670 which seems to fix it.

**Comment by ghost** [comment]
i already fixed it @msabramo  https://github.com/BerriAI/litellm/commit/cff66d6151560cf0b7087240457e2673387e0861

**Comment by databill86** [comment]
This is awesome! thank you!

**Pull request merged**
