### PR TITLE
[Feature]: Proxy: Support API-Key header in addition to Authorization header

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## Type

🆕 New Feature
🐛 Bug Fix
🧹 Refactoring
📖 Documentation
🚄 Infrastructure
✅ Test

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

### CODE REVIEW

**Comment by msabramo** [comment]
Hi @ishaan-jaff,

I tested this in an environment that was previously failing and it works now! Thanks!

👍

**Comment by msabramo** [comment]
@ishaan-jaff Do you think it’s possible to merge this today? I’d love to push out a version with this and have our ML engineers test it.

**Comment by ishaan-jaff** [comment]
@msabramo i'lll merge this now, queue up a release and add testing in a separate PR

**Comment by msabramo** [comment]
Hi @ishaan-jaff, is a Docker image available yet? I didn't see a new release.

**Comment by ishaan-jaff** [comment]
@msabramo I can queue up a dev release, looks like our CI/cd pipeline is having some trouble

**Comment by ishaan-jaff** [comment]
okay queued up `v1.40.7.dev1` - will be out in 15 mins @msabramo

**Comment by ishaan-jaff** [comment]
it's here @msabramo https://github.com/BerriAI/litellm/releases/tag/v1.40.7.dev1

**Pull request merged**
