### PR TITLE
Add support for Gemini 2.0 GoogleSearch tool

### PR DESCRIPTION
**Pull request by samling**
## Title

Add `googleSearch()` tool to valid tool list for Gemini/VertexAI models to support Gemini 2.0 grounding.

## Relevant issues

Enhances https://github.com/BerriAI/litellm/issues/7188

## Type

🆕 New Feature
✅ Test

## Changes

- Add `googleSearch()` tool to list of valid tools for Gemini/VertexAI models
- Update test

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locally

image

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for the PR @samling

**Comment by ghost** [comment]
Could you contribute a doc update on this too - https://github.com/BerriAI/litellm/blob/d1124a736ce16f8549f69644882f134820626ef9/docs/my-website/docs/providers/vertex.md#L4?

**Comment by samling** [comment]
@krrishdholakia Certainly, I'll submit a follow-up PR with some doc additions tomorrow.

**Comment by ishaan-jaff** [comment]
hi @samling - curious do you use LiteLLM Proxy in production? 

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Pull request merged**
