### PR TITLE
chore: add black check to GitHub workflow

### PR DESCRIPTION
**Pull request by bufferoverflow**

### CODE REVIEW

**Comment by ghost** [comment]
Hey @bufferoverflow i realized this after merging the initial commit. 

We moved from github workflows to circle ci - https://github.com/BerriAI/litellm/tree/main/.circleci (Let me know where it would've been helpful to have this on our docs). 

We also use commitizen, and I added the black check as a pre-commit hook, so all our commits now go through it as well - https://github.com/BerriAI/litellm/blob/main/.pre-commit-config.yaml

**Comment by ghost** [comment]
added black formatting to the circle ci pipeline - https://github.com/BerriAI/litellm/commit/9a19c7c59900c89f9258b50d14307170ef6d9244 

@bufferoverflow 

Does that cover the scope of what this PR intended?

**Comment by ghost** [comment]
closing PR based on comments above.

**Comment by bufferoverflow** [comment]
@krrishdholakia I think the the removal of some ignore within `.flake8` and black formatting here is still worth to add. Shall I completely remove the GH workflow?

**Comment by ghost** [comment]
Yes - that makes sense!

**Pull request closed without merging**
