### PR TITLE
improve bedrock exception granularity

### PR DESCRIPTION
**Pull request by dleen**

### CODE REVIEW

**Comment by ghost** [comment]
@dleen what would a good test be for this exception? Happy to add it to our ci/cd as well

**Comment by dleen** [comment]
Passing a model name like: `bedrock/invalid-model-name`

**Comment by dleen** [comment]
Is there a guide on how to run the tests? Is it just `pytest`?

**Comment by ghost** [comment]
Yup: 
```python 
cd litellm/litellm

pytest . -x 
```

**Pull request merged**
