### PR TITLE
[3] Databricks integration: Modularize client logic

### PR DESCRIPTION
**Pull request by dbczumar**
**NOTE: This PR depends on https://github.com/BerriAI/litellm/pull/5713 and https://github.com/BerriAI/litellm/pull/5714. The diff will shrink significantly once these dependent PRs are merged**

## Title

Databricks integration: Modularize client logic

## Type

🆕 New Feature

## Changes

This PR splits API request logic into a separate module (databricks/client.py) and refactors the code for improved readability.

**Unit tests**

Screenshot 2024-09-16 at 12 52 17 PM

**Manual tests**

Ran the following script and confirmed that the output is sane:

```
import asyncio
from litellm import completion, acompletion, embedding, aembedding
import os

response = completion(
    model="databricks/databricks-dbrx-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    stream=False,
)

print(response)
print(list(response))

os.environ["DATABRICKS_API_KEY"] = "...."
os.environ["DATABRICKS_API_BASE"] = "...."


response = completion(
    model="databricks/databricks-dbrx-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    stream=True
)
print(response)
print(list(response))

response = asyncio.run(acompletion(
    model="databricks/databricks-dbrx-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}]
))
print(response)

response = asyncio.run(acompletion(
    model="databricks/databricks-dbrx-instruct", 
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    stream=True
))
print(response)
print(asyncio.run(anext(asyncio.run(response.fetch_stream()))))

response = embedding(
    model="databricks/databricks-bge-large-en",
    input=["Hello, how are you?"],
)

print(response)
print(list(response))

response = asyncio.run(aembedding(
    model="databricks/databricks-bge-large-en",
    input=["Hello, how are you?"],
))

print(response)
print(list(response))
```

### CODE REVIEW

**Comment by dbczumar** [comment]
@krrishdholakia Can you take a look at this PR? Thanks for your help :)

**Comment by ghost** [comment]
Hey @dbczumar - thank you for this PR. Why is this necessary? 

Ideally we have similar code across provider implementations, making it easier to debug issues

**Comment by dbczumar** [comment]
> Hey @dbczumar - thank you for this PR. Why is this necessary?
> 
> Ideally we have similar code across provider implementations, making it easier to debug issues

Because the current code is quite difficult to reason about and maintain (lots of `if` branching, weak typing). Abstracting the API request layer out makes it much simpler to extend (e.g. in https://github.com/BerriAI/litellm/pull/5725). https://github.com/BerriAI/litellm/pull/5725 would be significantly harder to implement otherwise

The Databricks team is happy to help debug issues and maintain the Databricks integration

**Comment by ghost** [comment]
Hmm, i understand your perspective re: trying to simplify databricks credential management. The issue is that the databricks.py file is currently used as an openai-like handler file, and called in other routes that have openai-like api's but need some tweaks. 


It would be great to maintain an openai-like handler to handle the calling logic, and separate the 'get auth' side of this. 

I haven't read your PR in enough detail to comment on it, but if we could just focus on solving the 'get auth' problem for now, it would be great. 


Here's how it's used in the vertex ai llama 3.1 api implementation (openai-like api but needs vertex to get credentials) - https://github.com/BerriAI/litellm/blob/3a5039e284adac1279964849879619fe2cef309c/litellm/llms/vertex_ai_and_google_ai_studio/vertex_ai_partner_models/main.py#L113

in sagemaker's huggingface messages api implementation - https://github.com/BerriAI/litellm/blob/3a5039e284adac1279964849879619fe2cef309c/litellm/llms/sagemaker/sagemaker.py#L275


---
If you could share specifics on what makes the implementation hard to maintain over time, happy to work through them with you!

**Comment by dbczumar** [comment]
@krrishdholakia The challenge here is that the `get auth` layer isn't feasible to implement with an openai-like handler because our Databricks SDK does not offer public / stable APIs for fetching the API base and auth token (nor do we plan to offer these, because API keys are periodically refreshed within Databricks environments, and we don't want users to extract the keys once & fail to refresh them). Token / API base resolution is handled internally by the Databricks SDK. Databricks SDK methods like `WorkspaceClient.api_client.do()` need to be called directly, rather than extracting API keys / tokens and passing them to the openai handler.

Without the refactoring in this PR, the `if / else` logic to determine whether to call the openai-like handler or the Databricks SDK APIs is very tricky to maintain.

> The issue is that the databricks.py file is currently used as an openai-like handler file, and called in other routes that have openai-like api's but need some tweaks.

Naively, it does seem a little strange to have non-Databricks LLM providers depend on utilities in `databricks.py`. Can we remove or refactor those dependencies?

**Comment by ghost** [comment]
> Naively, it does seem a little strange to have non-Databricks LLM providers depend on utilities in databricks.py. Can we remove or refactor those dependencies?

Yep. we plan to have a separate `openai-like` handler, to clean up the logic.

**Comment by ghost** [comment]
> The challenge here is that the get auth layer isn't feasible to implement with an openai-like handler

Got it. Can we do a custom implementation then? To check for the credentials in the environment / handle refresh in a handler file. Alternatively, we can hold off on this, until there's something more stable for us to use. 

Our preference is to really avoid additional dependencies here. 

Context - a lot of litellm users, deploy our proxy via the dockerfile, and we'd prefer to keep those requirements as light as possible.

**Comment by dbczumar** [comment]
> Got it. Can we do a custom implementation then? To check for the credentials in the environment / handle refresh in a handler file. Alternatively, we can hold off on this, until there's something more stable for us to use.
> 
> Our preference is to really avoid additional dependencies here.

The challenge with a custom implementation is that it will quickly diverge from the implementation in the Databricks SDK, which is maintained by a large team of engineers and is used by 10,000+ Databricks customers. We'd effectively be creating a parallel auth layer to maintain, just for LiteLLM compatibility. This is likely unsustainable due to the complexities of Databricks auth and the pace of iteration within the Databricks SDK.

The proposed change doesn't make the Databricks SDK a hard dependency. It optionally uses the Databricks SDK if the user doesn't manually configure a key and an API base. You don't need to add the Databricks SDK to your library's requirements files.

I fully understand that the current LiteLLM abstractions assume that each provider's auth and request execution components can be decoupled. However, Databricks is an example of a provider where that isn't feasible (unless users mint their own long-lived access tokens and hardcode them in the `DATABRICKS_API_KEY` environment variable, which is not recommended / not a best practice for Databricks users). I suspect other providers with similar constraints may emerge in the future. If possible, can we align on an approach for accommodating such providers?

**Pull request closed without merging**
