### PR TITLE
docs: correction steps for installing virtual environment

### PR DESCRIPTION
**Pull request by Regun63**
I added a virtual environment setup for installation

### CODE REVIEW

**Comment by ghost** [comment]
@biswassushmita947 This changed 37 files. Can you review and just submit the 1 that was actually modified?

**Comment by Regun63** [comment]
@krrishdholakia  i modified only readme file only

**Comment by Regun63** [comment]
Without using a virtual environment, it's harder to install packages and can cause problems because different programs can clash with each other due to conflicting dependencies.

**Comment by ghost** [comment]
Do we really need instructions for teaching people how to set up a venv? this seems quite redundant. Can you tell me more about the problem you faced using litellm @biswassushmita947

**Comment by ghost** [comment]
closing due to inactivity.

**Pull request closed without merging**
