### PR TITLE
Add a Helm chart for deploying LiteLLM Proxy

### PR DESCRIPTION
**Pull request by ShaunMaher**
Hi.

This pull request adds a [Helm chart](https://helm.sh/) to the LiteLLM repository.

## Features

* The chart can, optionally, deploy a Postgres database server instance to use
* The chart can, optionally, deploy the Admin UI alongside the proxy
* The README.md shows all relevant options and gives some examples.
* Where files have deviated from the Helm boilerplate, I have included in-file
  comments explaining why.  If I'm hit by a bus, another developer should be
  able to understand the "code" and reasoning behind anything that deviates from
  expectation.
* Health checks will allow Kubernetes to action (e.g. restart) misbehaving
  services
* A few extra entries are added to .gitignore

## Limitations

* The Admin UI is unable to add models.  This is because it would need to update
  the `config.yaml` file which is a exposed ConfigMap, and therefore, read-only.
  This is a limitation of this helm chart, not the Admin UI itself.  I will
  circle back and resolve this in a future version.

## GitHub workflow

I have included a separate GitHub workflow that packages the Chart and pushes it
into the project's OCI (Docker Image) registry.  No need to get project pages
working and generate an index.yaml, etc.  It should just work.

The workflow populates the Chart's `appVersion` field with the name of the
repo's most recent release tag.  It also increments the Chart's own version by
one patch level.  Consumers of the chart should therefore see fresh LiteLLM
releases when they refresh the chart in their deployments.
  
The goal here was to have zero maintenance required by the LiteLLM team while
still keeping the chart up to date.

For this PR I have left this workflow separate from the "Build, Publish LiteLLM Docker Image. New Release"
workflow.  If the project decides that it should all happen as one combined
workflow, the two .yaml files should be trivial to merge.

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
wow ! this is an amazing PR 🎉🎉 🎉we've had a couple users ask us for Helm charts ! Thanks so much

**Comment by ishaan-jaff** [comment]
@ShaunMaher there is one action and one workflow here. What do I need to run to get this started ?

**Comment by ShaunMaher** [comment]
Hi.

After a release of LiteLLM itself, and the tag has been added to the repository, run the "Build, Publish LiteLLM Helm Chart. New Release" workflow to build and publish the helm chart into the GHCR docker image registry.

The helm chart build process uses the latest release tag on the repo to set the "AppVersion" field of the chart which becomes the default version on LiteLLM that gets installed by the chart (i.e. the tag of the litellm image to use).

If everything goes well, you should see a "litellm-helm" object appear in the BerryAI packages.

This separate workflow could be merged with the "Build, Publish LiteLLM Docker Image. New Release" workflow.  I just kept is apart as to not have any effect of your current processes.

Cheers.
Shaun.

**Comment by ishaan-jaff** [comment]
lgtm - merging !

**Comment by ishaan-jaff** [comment]
Hi @ShaunMaher  any chance we can hop on a call to better understand how we can improve litellm for you ?

Link to my cal for your convenience
https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-02

**Pull request merged**
