### PR TITLE
Add empower-functions integration to litellm

### PR DESCRIPTION
**Pull request by liuyl**
## Title Add empower-functions integration to litellm

empower-functions is a function-calling model that is 3X faster and 10X cheaper than GPT-4, read more about the model: https://docs.empower.dev/inference/tool-use/introduction

## Type

🆕 New Feature

## Changes

Adding empower models to liteLLM, This is a updated PR of https://github.com/BerriAI/litellm/pull/2802

### CODE REVIEW

**Comment by ghost** [comment]
can you add a test against a mock endpoint please

reference: https://github.com/BerriAI/litellm/blob/8375e9621ccbb08675326e7344e214100f1fa1d6/litellm/tests/test_completion.py#L1381

**Comment by ghost** [comment]
and share a screenshot of it passing

**Comment by liuyl** [comment]
> and share a screenshot of it passing

I added a test, but `poetry run pytest .` finished with a lot of failed tests, I pasted the log below. I wonder if it is OK to run just the test I added?

> FAILED test_ratelimit.py::test_rate_limit[usage-based-routing-False-2-3] - openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
FAILED test_ratelimit.py::test_rate_limit[usage-based-routing-False-3-2] - openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
FAILED test_spend_logs.py::test_spend_logs - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_spend_logs.py::test_get_predicted_spend_logs - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_spend_logs.py::test_spend_report_endpoint - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_team.py::test_team_new - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_team.py::test_team_info - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_team.py::test_team_update_sc_2 - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_team.py::test_team_delete - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_team.py::test_member_delete - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_team.py::test_team_alias - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_team.py::test_users_in_team_budget - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]
FAILED test_team_logging.py::test_team_logging - Failed: Unexpected error: Cannot connect to host 0.0.0.0:4000 ssl:default [Connect call failed ('0.0.0.0', 4000)]

**Comment by ghost** [comment]
just run it on your test to confirm it works @liuyl

**Comment by liuyl** [comment]
image

@krrishdholakia please find the test result above :)

**Comment by ghost** [comment]
LGTM! Planning on merging once main is stable (v1.41.14 is released)

**Pull request merged**
