### PR TITLE
[Fix] UI - split multiple model names with comma

### LINKED ISSUE #3001: [Bug]: Add model through UI creates a model for each letter of formValues["model"]
### What happened?

If i add a model through UI it tries to create a model for each letter of formValues["model"].
Maybe split the model names with a comma

https://github.com/BerriAI/litellm/blob/5e171881f431d3a79fa7bd3aea3f5c39f77df163/ui/litellm-dashboard/src/components/model_dashboard.tsx#L259

### Relevant log output

_No response_

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by zJuuu**
Fix #3001 where Object.values splits model name string into single letters
https://github.com/BerriAI/litellm/blob/5e171881f431d3a79fa7bd3aea3f5c39f77df163/ui/litellm-dashboard/src/components/model_dashboard.tsx#L259

### CODE REVIEW

**Review by ishaan-jaff — COMMENTED** [review]
Can I see a screenshot of what this looked like before and after the change ?

**Comment by zJuuu** [comment]
It creates a post request to the /model/new endpoint for each letter of "openai/mistralai/Mistral-7B-Instruct-v0.2" after the change it splits the string of the input at each comma
Multiple requests on model add

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
can you send a screenshot that this still works for adding Azure models
- Add an Azure OpenAI models - fake credentials are fine 
- After 5s view Azure model in the "Models" Page

**Comment by ishaan-jaff** [comment]
can merge after the following screenshot is sent ^ will verify there are no regressions @zJuuu

**Comment by ishaan-jaff** [comment]
@zJuuu can you pull latest changes from main before you send a screenshot of it working, thanks

**Comment by zJuuu** [comment]
Missed the dropdown selection on the other providers. Latest commit handles both. String seperated by comma for the openai compatible endpoint, azure provider and array for the dropdown selection for openai and other providers.
Logs with azure: 
azure model add

Logs of Openai :
openai provider add

**Pull request closed without merging**
