### PR TITLE
feat(bedrock_httpx.py): Add Cloudflare AI Gateway support

### PR DESCRIPTION
**Pull request by Manouchehri**
## Title

This adds Cloudflare AI Gateway support for Bedrock httpx

## Relevant issues

Fxies #1040. Related to #3467.

## Type

🆕 New Feature

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locally

image

### CODE REVIEW

**Comment by Manouchehri** [comment]
Confirmed 1a6cdc3a2c188c99ef3132676e529dc2dd2d1107 working after rebasing to main.

image

**Comment by Manouchehri** [comment]
Bump on this, it's been stable for me for awhile now. :)

**Comment by Manouchehri** [comment]
The new nice converse Bedrock flow works with Cloudflare AI Gateway. :)

**Comment by Manouchehri** [comment]
TODO: Add unit test.

**Comment by Manouchehri** [comment]
Let's maybe add a `aws_bedrock_runtime_endpoint_proxy` instead?

**Review by ghost — CHANGES_REQUESTED** [review]
change to support a simple `aws_proxy_url` param 

just use that for logging api_base param and client.post url param

**Comment by Manouchehri** [comment]
CLosing as I will make a new PR to address the changes requested.

**Pull request closed without merging**
