### PR TITLE
Add function call result submission support for Claude 3 models

### PR DESCRIPTION
**Pull request by lazyhope**
Claude 3 now supports submission of function call results using <function_results> tag (https://docs.anthropic.com/claude/docs/functions-external-tools#function-calling-format), litellm can support submission of function call results by allowing OpenAI's `"role": "tool"` messages.

This PR is to address https://github.com/BerriAI/litellm/issues/2526 and aim to make Anthropic's Tool Use more complete on litellm. It also refactors `anthropic_messages_pt` to merge consecutive messages with the same role, as Claude models are trained to operate on alternating user and assistant conversational turns.

### CODE REVIEW

**Comment by ghost** [comment]
nice - can you add a test to `test_completion.py` for this - you'll see a bunch of `claude_3` tests there. 

Do you have an ETA on this PR? @lazyhope

**Comment by lazyhope** [comment]
> nice - can you add a test to `test_completion.py` for this - you'll see a bunch of `claude_3` tests there. 
> 
> Do you have an ETA on this PR? @lazyhope 

Yes, I just implemented a new `anthropic_pt` that supports alternative roles and tool call conversations, only have tests left now, should be ready for review in the next 24 hours

**Comment by lazyhope** [comment]
> nice - can you add a test to `test_completion.py` for this - you'll see a bunch of `claude_3` tests there.
> 
> Do you have an ETA on this PR? @lazyhope

The functional code has been implemented, please feel free to review it. I am going to writing tests for the refactored `anthropic_messages_pt` now.

**Comment by lazyhope** [comment]
@krrishdholakia Tests uploaded, it is ready for a full review.

**Comment by ghost** [comment]
LGTM!

**Comment by ghost** [comment]
this should be live in the next release

**Comment by ghost** [comment]
@lazyhope do you have a twitter/linkedin? Would love to give a shoutout on our changelog

**Comment by lazyhope** [comment]
> @lazyhope do you have a twitter/linkedin? Would love to give a shoutout on our changelog

Thanks for the review and the merge! My linkedin link is www.linkedin.com/in/lazyhope, appreciate the shoutout!

**Pull request merged**
