### PR TITLE
Added "deepseek/" as a supported provider (openai compatible)

### PR DESCRIPTION
**Pull request by paul-gauthier**
Uses the `DEEPSEEK_API_KEY` env var.

### CODE REVIEW

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
please can you add 1 test for deepseek so we can ensure there are no regressions. 

Can be added to `test_completion.py` I will get an API key

**Comment by paul-gauthier** [comment]
Sure thing, I added a simple test.

**Review by ishaan-jaff — APPROVED** [review]
lgtm ! will merge once main is stable

**Comment by ishaan-jaff** [comment]
@paul-gauthier would love to give you credit for the PR - mind sharing a link to your linkedin / twitter ? Will mention it in today's changelog 

Edit: NVM found you

**Pull request merged**
