### PR TITLE
fix: change actual github action for a call to discord RESTful API

### LINKED ISSUE #2146: [Feature]: fix discord publish workflow for github releases
### The Feature

our publish to discord workflow isn't working 

https://github.com/BerriAI/litellm/blob/21b132cff6105f635ffa95d4916cd0cb6221e5df/.github/workflows/ghcr_deploy.yml#L150

It would be great if somebody could help with this 

### Motivation, pitch

Help users keep up with latest litellm releases

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by DanielChico**
Fixes #2146

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
Nice ! do we need to provide any discord keys for this action ?

**Comment by DanielChico** [comment]
You need to provide the Discord webhook URL as a secret in your GitHub repository. I think this is already done. This URL is the only thing you need for this operation according with my research. The webhook URL contains a token that allows posting messages to the specific Discord channel you've set up the webhook for. Pls check this out and let me know if you found any issue. I'll be pleased to solve it.

**Comment by ghost** [comment]
Thanks for this @DanielChico

**Comment by ghost** [comment]
hey @DanielChico could i ask for your help here: 

The current action just announces a new version is out. 
Screenshot 2024-03-01 at 1 24 17 PM


It would be helpful if the release notes were part of the announcement. 

Is that possible?

**Comment by DanielChico** [comment]
Hello @krrishdholakia, I have submitted another pull request incorporating this new feature. Review it and let me know if it worked.

**Pull request merged**
