### PR TITLE
add test for rate limits - Router isn't coroutine safe

### PR DESCRIPTION
**Pull request by CLARKBENHAM**
These tests show that if the a Router(routing_strategy="usage-based-routing") is called with asyncio.run then the rate limits will be bypassed. But if it's run non-concurrently then rate limits will be respected.

You'd need another layer of concurrency control to use Router in a thread-safe manner. That may be acceptable as long as the docs are updated.

The other strategies do not respect rate limits:  https://github.com/CLARKBENHAM/litellm/blob/clark/test_ratelimit_other_routing_strategies/tests/test_ratelimit.py

In response to ask for tests: https://github.com/BerriAI/litellm/issues/2153
and Issue https://github.com/BerriAI/litellm/issues/527

### CODE REVIEW

**Comment by ghost** [comment]
hey @CLARKBENHAM can you add some comments to the test, talking through what's happening - will make it quicker for me to add it to repo 

thanks for this! 

> The other strategies do not respect rate limits:

can you clarify this? we check for tpm/rpm limits on lowest-latency routing as well

**Comment by CLARKBENHAM** [comment]
Added comments. 
The lowest-latency routing strategy makes more calls than the rate limits should allow. I've updated this branch to include those tests. You can see all [latency-based-routing-*] tests fail when num_try_send > num_allowed_send, regardless of if sync or not, but pass when num_try_send <= num_allowed_send.

**Comment by ghost** [comment]
Interesting - anything our unit tests could be missing for this - https://github.com/BerriAI/litellm/blob/e453a96c6726054e89388770a35cfdea4c5bff7d/litellm/tests/test_lowest_latency_routing.py#L4

**Comment by CLARKBENHAM** [comment]
The issue is that lowest_latency_logger always returns a deployment even if none should be available. The previous tests only check where 1 deployment should exist not where no deployments should exist.

Furthermore, you sequentially make async calls then the rate limits work (at least with "usage-based-routing").  And it's  sequential calls that are tested https://github.com/BerriAI/litellm/blob/e453a96c6726054e89388770a35cfdea4c5bff7d/litellm/tests/test_lowest_latency_routing.py#L101
eg. if the rate limit is 4 and you make 4 calls then 4 calls then the 2nd set of calls will fail as expected. 
Rather you'd want to make these calls simultaneously and then see if they're fixed.

Issue is line 297 in lowest_latency, always choosing from "healthy deploys" even if none of the deploys are healthy https://github.com/BerriAI/litellm/blob/e453a96c6726054e89388770a35cfdea4c5bff7d/litellm/router_strategy/lowest_latency.py#L297

This is why none of the new usage tests trigger for lowest_latency.

While with usage-based-routing you do return none https://github.com/BerriAI/litellm/blob/e453a96c6726054e89388770a35cfdea4c5bff7d/litellm/router_strategy/lowest_tpm_rpm.py#L212 
but there's still the async bug.

**Comment by ghost** [comment]
@CLARKBENHAM let me know when this is ready for review

**Comment by CLARKBENHAM** [comment]
@krrishdholakia  Ready except we need to decide how to handle the async bug. I suggest we just update the docs with a warning that rate limits aren't valid across coroutines and comment out these tests until we make it async safe. 
I can make those changes if that's the route we choose.

I made the changes to [router_strategy/lowest_latency.py](https://github.com/BerriAI/litellm/blob/e453a96c6726054e89388770a35cfdea4c5bff7d/litellm/router_strategy/lowest_latency.py#L297) so that it won't return unhealthy deployments and added tests to catch in the future.

**Comment by ghost** [comment]
how could we fix the issue? @CLARKBENHAM 

happy to take a stab at it

**Comment by CLARKBENHAM** [comment]
I don't know the code well enough to say where exactly we're failing to transfer control properly. My gut says it would be more effort than it's worth to get this right. You'd have to check every async call along the path of a request to make sure that if another function started running at that point we wouldn't see these issues. 

It's not in the strategy code, since test_lowest_latency_routing works when async, but in the actual requests being made.

My goal here was to maximize the throughput of batch processing. To solve this goal I'm just going to write a queue around accesses to the Router Object. Making a function to do this was discussed here https://github.com/BerriAI/litellm/issues/527 and closed. 

If we want to support this functionality I think we should write a single function to make batch calls, not re-write everything to be coroutine safe.

**Comment by CLARKBENHAM** [comment]
@krrishdholakia 
https://github.com/BerriAI/litellm/blob/4a1b2704c28d317d8311c857dad12cdcb17160ac/litellm/proxy/utils.py#L142
The rate limiter callback is added to the list of callbacks, but then every callback is awaited individually. 

So if I start 10 async requests all at once they can pass the rate limiter callback, but then when they await the next callback, control could be transferred to another coroutine. So you'd have to stop awaiting all these callbacks at a minimum. I tried added a lock around these accesses was insufficient, so there other places a similar thing happens.

**Comment by ghost** [comment]
Hey @CLARKBENHAM i'm also exploring a queue for the router (to solve request prioritization). Do you have some code i can look at?

**Comment by CLARKBENHAM** [comment]
I'm using https://github.com/CLARKBENHAM/sep_finetune_llm/blob/main/src/llm_requests.py  for batch completion calls. It doesn't use a task queue rather a single Router with fences based on tokens consumed  previously.

Maybe it'll get you started, but it doesn't attempt to address request prioritization.

**Comment by ghost** [comment]
Hey @CLARKBENHAM 

I was able to pass the rpm check by enabling pre_call_checks for RPM limits

See - https://github.com/BerriAI/litellm/commit/0d1cca9aa0a853452fa67032e98e670fc43c8598 + https://github.com/BerriAI/litellm/commit/205ac1496a62b137ac92cd7b79b221a46e5131e1


It's a simple in-memory implementation. 

Just updates the current requests for a given deployment, and if `enable_pre_call_checks=True`, it checks the in-memory rpm against the given deployment rpm limit 


Let me know if that solves the problem 

**Update**

Also added support for checking the usage-based cache values in the pre-call check - https://github.com/BerriAI/litellm/commit/7ae6432f94dc7d3cf7ce5da6bf6e9c89f51b010a


can be enabled by doing:

```python
from litellm import Router

router = Router(.., enable_pre_call_check=True)
```

**Comment by CLARKBENHAM** [comment]
Yep, with the new changes these tests past. Thank you for doing this. 

I tried `enable_pre_call_checks=True` before and it was insufficient.

The docs don't include this right now, I'll update them https://docs.litellm.ai/docs/routing#:~:text=based%2Drouting%22)-,response%20%3D%20await%20router.acompletion(model%3D%22gpt%2D3.5%2Dturbo%22%2C%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20messages%3D%5B%7B%22role%22%3A%20%22user%22%2C%20%22content%22%3A%20%22Hey%2C%20how%27s%20it%20going%3F%22%7D%5D,-print(response

**Comment by CLARKBENHAM** [comment]
https://github.com/BerriAI/litellm/pull/2909

**Pull request merged**
