### PR TITLE
Fix Vertex AI function calling invoke: use JSON format instead of protobuf text format.

### PR DESCRIPTION
**Pull request by Guowang**
## Title

Fix Vertex AI function calling invoke: use JSON format instead of protobuf text format.

## Relevant issues

When running Tau Benchmark, we encountered errors like "Error: FindUserIdByNameZip.invoke() got an unexpected keyword argument 'fields'." The issue is that protobuf text format was passed to Vertex AI, but plain JSON format is expected.

## Type

🐛 Bug Fix

## Changes

litellm/litellm/llms/prompt_templates/factory.py
litellm/litellm/types/llms/vertex_ai.py

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

Verified with running Tau Benchmark: no error of "unexpected keyword argument 'fields'" encountered.

### CODE REVIEW

**Comment by ghost** [comment]
hi @Guowang can you share a minimal test code of this issue for repro

**Comment by Guowang** [comment]
> hi @Guowang can you share a minimal test code of this issue for repro

Sure, I've put together some code that reproduces the issue reliably. You can find it here:  https://docs.google.com/document/d/1ebpimT485sO4N5WG_GrOpS_x621dV6m0v8sT0iMqpw4/edit?usp=sharing.

To help provide context, I also inspected litellm/litellm/llms/vertex_ai_and_google_ai_studio/gemini/vertex_and_google_ai_studio_gemini.py and found that the `fields` keyword is included in the request to Gemini on line 1439.

Please let me know if you have any issues accessing the test code.

**Comment by Guowang** [comment]
More contexts on the gemini request format on REST, the documentation example should be https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#parallel-samples, instead of the one in https://github.com/BerriAI/litellm/blob/main/litellm/llms/prompt_templates/factory.py#L981.

**Comment by ghost** [comment]
> for i in range(10):
   # gemini call
   response = completion(model="gemini-1.5-pro-002", messages=messages, custom_llm_provider="gemini", tools=tools_info)


   next_message = response.choices[0].message.model_dump()
   if "fields" in repr(next_message):
       print("\n\nFound in trial ", i, " unexpected `fields` keyword in next_message: ", next_message)


your script doesn't imply an error

**Comment by ghost** [comment]
i also ran the simplified version (no for loop - hitting rate limit errors) and it works for me without the change

**Comment by ghost** [comment]
```
def test_gemini_function_call_parameter_in_messages_3():
    messages = [
        {
            "role": "user",
            "content": "I'm looking to book a one-way flight from New York to Seattle on May 20th.",
        },
        {
            "content": "Sure, could you please provide your user ID?\n",
            "role": "assistant",
            "tool_calls": None,
            "function_call": None,
        },
        {"role": "user", "content": "My user ID is mia_li_3668."},
        {
            "content": None,
            "role": "assistant",
            "tool_calls": [
                {
                    "index": 0,
                    "function": {
                        "arguments": '{"destination": "SEA", "date": "2024-05-20", "origin": "JFK"}',
                        "name": "search_direct_flight",
                    },
                    "id": "call_3f287a5d-632c-4043-9d69-b6bcfbee73ff",
                    "type": "function",
                }
            ],
            "function_call": None,
        },
        {
            "role": "tool",
            "tool_call_id": "call_3f287a5d-632c-4043-9d69-b6bcfbee73ff",
            "name": "search_direct_flight",
            "content": '[{"flight_number": "HAT069", "origin": "JFK", "destination": "SEA", "scheduled_departure_time_est": "06:00:00", "scheduled_arrival_time_est": "12:00:00", "status": "available", "available_seats": {"basic_economy": 17, "economy": 12, "business": 3}, "prices": {"basic_economy": 51, "economy": 121, "business": 239}}, {"flight_number": "HAT083", "origin": "JFK", "destination": "SEA", "scheduled_departure_time_est": "01:00:00", "scheduled_arrival_time_est": "07:00:00", "status": "available", "available_seats": {"basic_economy": 16, "economy": 7, "business": 3}, "prices": {"basic_economy": 87, "economy": 100, "business": 276}}]',
        },
    ]

    tools_info = [
        {
            "type": "function",
            "function": {
                "name": "book_reservation",
                "description": "Book a reservation.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "user_id": {
                            "type": "string",
                            "description": "The ID of the user to book the reservation, such as 'sara_doe_496'.",
                        },
                        "origin": {
                            "type": "string",
                            "description": "The IATA code for the origin city, such as 'SFO'.",
                        },
                        "destination": {
                            "type": "string",
                            "description": "The IATA code for the destination city, such as 'JFK'.",
                        },
                        "flight_type": {
                            "type": "string",
                            "enum": ["one_way", "round_trip"],
                        },
                        "cabin": {
                            "type": "string",
                            "enum": ["basic_economy", "economy", "business"],
                        },
                        "flights": {
                            "type": "array",
                            "description": "An array of objects containing details about each piece of flight.",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "flight_number": {
                                        "type": "string",
                                        "description": "Flight number, such as 'HAT001'.",
                                    },
                                    "date": {
                                        "type": "string",
                                        "description": "The date for the flight in the format 'YYYY-MM-DD', such as '2024-05-01'.",
                                    },
                                },
                                "required": ["flight_number", "date"],
                            },
                        },
                        "passengers": {
                            "type": "array",
                            "description": "An array of objects containing details about each passenger.",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "first_name": {
                                        "type": "string",
                                        "description": "The first name of the passenger, such as 'Noah'.",
                                    },
                                    "last_name": {
                                        "type": "string",
                                        "description": "The last name of the passenger, such as 'Brown'.",
                                    },
                                    "dob": {
                                        "type": "string",
                                        "description": "The date of birth of the passenger in the format 'YYYY-MM-DD', such as '1990-01-01'.",
                                    },
                                },
                                "required": ["first_name", "last_name", "dob"],
                            },
                        },
                        "payment_methods": {
                            "type": "array",
                            "description": "An array of objects containing details about each payment method.",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "payment_id": {
                                        "type": "string",
                                        "description": "The payment id stored in user profile, such as 'credit_card_7815826', 'gift_card_7815826', 'certificate_7815826'.",
                                    },
                                    "amount": {
                                        "type": "number",
                                        "description": "The amount to be paid.",
                                    },
                                },
                                "required": ["payment_id", "amount"],
                            },
                        },
                        "total_baggages": {
                            "type": "integer",
                            "description": "The total number of baggage items included in the reservation.",
                        },
                        "nonfree_baggages": {
                            "type": "integer",
                            "description": "The number of non-free baggage items included in the reservation.",
                        },
                        "insurance": {"type": "string", "enum": ["yes", "no"]},
                    },
                    "required": [
                        "user_id",
                        "origin",
                        "destination",
                        "flight_type",
                        "cabin",
                        "flights",
                        "passengers",
                        "payment_methods",
                        "total_baggages",
                        "nonfree_baggages",
                        "insurance",
                    ],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "calculate",
                "description": "Calculate the result of a mathematical expression.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "expression": {
                            "type": "string",
                            "description": "The mathematical expression to calculate, such as '2 + 2'. The expression can contain numbers, operators (+, -, *, /), parentheses, and spaces.",
                        }
                    },
                    "required": ["expression"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "cancel_reservation",
                "description": "Cancel the whole reservation.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "reservation_id": {
                            "type": "string",
                            "description": "The reservation ID, such as 'ZFA04Y'.",
                        }
                    },
                    "required": ["reservation_id"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "get_reservation_details",
                "description": "Get the details of a reservation.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "reservation_id": {
                            "type": "string",
                            "description": "The reservation id, such as '8JX2WO'.",
                        }
                    },
                    "required": ["reservation_id"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "get_user_details",
                "description": "Get the details of an user.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "user_id": {
                            "type": "string",
                            "description": "The user id, such as 'sara_doe_496'.",
                        }
                    },
                    "required": ["user_id"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "list_all_airports",
                "description": "List all airports and their cities.",
            },
        },
        {
            "type": "function",
            "function": {
                "name": "search_direct_flight",
                "description": "Search direct flights between two cities on a specific date.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "origin": {
                            "type": "string",
                            "description": "The origin city airport in three letters, such as 'JFK'.",
                        },
                        "destination": {
                            "type": "string",
                            "description": "The destination city airport in three letters, such as 'LAX'.",
                        },
                        "date": {
                            "type": "string",
                            "description": "The date of the flight in the format 'YYYY-MM-DD', such as '2024-01-01'.",
                        },
                    },
                    "required": ["origin", "destination", "date"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "search_onestop_flight",
                "description": "Search direct flights between two cities on a specific date.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "origin": {
                            "type": "string",
                            "description": "The origin city airport in three letters, such as 'JFK'.",
                        },
                        "destination": {
                            "type": "string",
                            "description": "The destination city airport in three letters, such as 'LAX'.",
                        },
                        "date": {
                            "type": "string",
                            "description": "The date of the flight in the format 'YYYY-MM-DD', such as '2024-05-01'.",
                        },
                    },
                    "required": ["origin", "destination", "date"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "send_certificate",
                "description": "Send a certificate to a user. Be careful!",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "user_id": {
                            "type": "string",
                            "description": "The ID of the user to book the reservation, such as 'sara_doe_496'.",
                        },
                        "amount": {
                            "type": "number",
                            "description": "Certificate amount to send.",
                        },
                    },
                    "required": ["user_id", "amount"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "think",
                "description": "Use the tool to think about something. It will not obtain new information or change the database, but just append the thought to the log. Use it when complex reasoning is needed.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "thought": {
                            "type": "string",
                            "description": "A thought to think about.",
                        }
                    },
                    "required": ["thought"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "transfer_to_human_agents",
                "description": "Transfer the user to a human agent, with a summary of the user's issue. Only transfer if the user explicitly asks for a human agent, or if the user's issue cannot be resolved by the agent with the available tools.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "summary": {
                            "type": "string",
                            "description": "A summary of the user's issue.",
                        }
                    },
                    "required": ["summary"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "update_reservation_baggages",
                "description": "Update the baggage information of a reservation.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "reservation_id": {
                            "type": "string",
                            "description": "The reservation ID, such as 'ZFA04Y'.",
                        },
                        "total_baggages": {
                            "type": "integer",
                            "description": "The updated total number of baggage items included in the reservation.",
                        },
                        "nonfree_baggages": {
                            "type": "integer",
                            "description": "The updated number of non-free baggage items included in the reservation.",
                        },
                        "payment_id": {
                            "type": "string",
                            "description": "The payment id stored in user profile, such as 'credit_card_7815826', 'gift_card_7815826', 'certificate_7815826'.",
                        },
                    },
                    "required": [
                        "reservation_id",
                        "total_baggages",
                        "nonfree_baggages",
                        "payment_id",
                    ],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "update_reservation_flights",
                "description": "Update the flight information of a reservation.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "reservation_id": {
                            "type": "string",
                            "description": "The reservation ID, such as 'ZFA04Y'.",
                        },
                        "cabin": {
                            "type": "string",
                            "enum": ["basic_economy", "economy", "business"],
                        },
                        "flights": {
                            "type": "array",
                            "description": "An array of objects containing details about each piece of flight in the ENTIRE new reservation. Even if the a flight segment is not changed, it should still be included in the array.",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "flight_number": {
                                        "type": "string",
                                        "description": "Flight number, such as 'HAT001'.",
                                    },
                                    "date": {
                                        "type": "string",
                                        "description": "The date for the flight in the format 'YYYY-MM-DD', such as '2024-05-01'.",
                                    },
                                },
                                "required": ["flight_number", "date"],
                            },
                        },
                        "payment_id": {
                            "type": "string",
                            "description": "The payment id stored in user profile, such as 'credit_card_7815826', 'gift_card_7815826', 'certificate_7815826'.",
                        },
                    },
                    "required": ["reservation_id", "cabin", "flights", "payment_id"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "update_reservation_passengers",
                "description": "Update the passenger information of a reservation.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "reservation_id": {
                            "type": "string",
                            "description": "The reservation ID, such as 'ZFA04Y'.",
                        },
                        "passengers": {
                            "type": "array",
                            "description": "An array of objects containing details about each passenger.",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "first_name": {
                                        "type": "string",
                                        "description": "The first name of the passenger, such as 'Noah'.",
                                    },
                                    "last_name": {
                                        "type": "string",
                                        "description": "The last name of the passenger, such as 'Brown'.",
                                    },
                                    "dob": {
                                        "type": "string",
                                        "description": "The date of birth of the passenger in the format 'YYYY-MM-DD', such as '1990-01-01'.",
                                    },
                                },
                                "required": ["first_name", "last_name", "dob"],
                            },
                        },
                    },
                    "required": ["reservation_id", "passengers"],
                },
            },
        },
    ]


    response = completion(
        model="gemini-1.5-pro-002",
        messages=messages,
        custom_llm_provider="gemini",
        tools=tools_info,
    )

```

**Comment by Guowang** [comment]
> > for i in range(10):
> 
> # gemini call
> response = completion(model="gemini-1.5-pro-002", messages=messages, custom_llm_provider="gemini", tools=tools_info)
> 
> next_message = response.choices[0].message.model_dump() if "fields" in repr(next_message): print("\n\nFound in trial ", i, " unexpected `fields` keyword in next_message: ", next_message)
> 
> your script doesn't imply an error

Thanks a lot for looking into this! 

The issue/error is in the returned model response, for example: 
{'content': None, 'role': 'assistant', 'tool_calls': [{'index': 0, 'function': {'arguments': '{"fields": {"value": {"string_value": "2024-05-20"}, "key": "date"}}', 'name': 'search_direct_flight'}, 'id': 'call_ee924f8f-7809-4c37-bbc1-70a0be0aaf83', 'type': 'function'}], 'function_call': None}

Note the "fields" in 'arguments'. This will be appended to the conversation and passed to model for the next round, and the model will be confused with the "fields" as argument and thus produce wrong results.

To print out the model response, I added following 3 lines to your test_gemini_function_call_parameter_in_messages_3() at the end:
```
response_message = response.choices[0].message.model_dump()
    if "fields" in repr(response_message):
        print(" unexpected `fields` keyword in response_message: ", response_message)
```

**Pull request merged**
