### PR TITLE
feat: friendli ai support

### PR DESCRIPTION
**Pull request by pocca2048**
## Title
[FriendliAI](https://suite.friendli.ai/) support

## Type
🆕 New Feature
📖 Documentation

## Changes
- add FriendliAI as a new LLM provider

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes
```python
from litellm import completion
import os

os.environ['FRIENDLI_TOKEN'] = ""
response = completion(
    model="friendli_ai/meta-llama-3-70b-instruct", 
    messages=[
       {"role": "user", "content": "hello from litellm"}
   ],
)
print(response)
```
image

### CODE REVIEW

**Comment by ghost** [comment]
hey @pocca2048 don't think we need a separate provider file here - it looks like friendliai is openai compatible - https://docs.friendli.ai/openapi/create-chat-completions

Just add it like this azure ai commit - https://github.com/BerriAI/litellm/pull/4134/commits/88e567af2c023b1ebe6864633bbee175a358cc7b

**Comment by ghost** [comment]
Bonus - if you can add a way to calculate friendliai cost in here - https://github.com/BerriAI/litellm/blob/5eb2822d31ff4d45016e12f90b35b437cc05bd7d/litellm/cost_calculator.py#L246

**Comment by pocca2048** [comment]
@krrishdholakia  Thank you for the suggestion! 
I will work on the cost calculation.
FriendliAI API is indeed compatible with OpenAI.
However, since it provides additional fields that OpenAI does not, it would be better to keep a separate provider file.

**Comment by ghost** [comment]
hey @pocca2048 

> However, since it provides additional fields that OpenAI does not, it would be better to keep a separate provider file.

if a param passed in is not an openai param, we'll assume it's provider specific and pass that in to the request body as a kwarg, so this should work without needing to maintain a separate file 

https://docs.litellm.ai/docs/completion/input#provider-specific-params

let me know if you face any issues

**Comment by pocca2048** [comment]
@krrishdholakia Thank you for the comment!
I would like to clarify what you mean by "separate provider file".
Do you mean `docs/providers/*.md`?
If it is the case, I think there are provider pages for other openai compatible providers as well. E.g. [azure](https://docs.litellm.ai/docs/providers/azure), [groq](https://docs.litellm.ai/docs/providers/groq), [fireworks](https://docs.litellm.ai/docs/providers/fireworks_ai)

**Comment by pocca2048** [comment]
@krrishdholakia Based on your comments, I have deleted separate provider file.
Any further feedback would be appreciated!

**Comment by pocca2048** [comment]
@ishaan-jaff @krrishdholakia
Hi team, could someone please review the PR I submitted?
Thanks.

**Comment by ghost** [comment]
Hey @pocca2048 looks great - can you share a screenshot of this working for you

**Comment by pocca2048** [comment]
@krrishdholakia Sure, here you are.
image

**Pull request merged**
