### PR TITLE
Setup pre commit

### PR DESCRIPTION
**Pull request by linediconsine**
I am working on https://github.com/BerriAI/litellm/issues/422

There issue say:
"""
For 3. In addition to the CI, I would reproduce some parts, e.g. mypy, black, isort locally using a pre-commit.
https://pre-commit.com/
"""

I noticed few conflict running both isort and black, and mypy so I dicided to create this PR as initial pre commit setup

Running locally I get 
```
(litellm-py3.10) ➜  litellm git:(setup-pre-commit) pre-commit run --all-files                     
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...............................................................Passed
check for added large files..............................................Passed
black....................................................................Passed```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
thanks for the PR @linediconsine 

What do each of these hooks do ?

-   id: trailing-whitespace
-   id: end-of-file-fixer
-   id: check-yaml
-   id: check-added-large-files


How do the pre commit hooks work ? Is it after every commit that's pushed to github?

**Comment by ishaan-jaff** [comment]
@linediconsine also can we separate this into two PRs:
- PR1 - add the config for the commits
- PR2 - run the pre commit hook on all files

**Comment by linediconsine** [comment]
Separate PRs

I created it as `PR1 - add the config for the commits`
I created https://github.com/BerriAI/litellm/pull/511

I will also reply there on the configurations question above

**Comment by ishaan-jaff** [comment]
I think this PR still has 207 change. Can we only have the change to the config in this PR @linediconsine

**Comment by ishaan-jaff** [comment]
should be good to merge after all the merge conflicts are resolved and this PR only edits one file

**Comment by linediconsine** [comment]
@ishaan-jaff can you please confirm if I need to do this task
> Can we only have the change to the config in this PR

Or are we good here 

Happy to do this, 

Thanks

**Comment by ishaan-jaff** [comment]
@linediconsine yes - for this PR can you only change 1 file which is the pre commit config

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
only change the pre commit config

**Comment by ishaan-jaff** [comment]
@linediconsine any updated on this ?

**Comment by ishaan-jaff** [comment]
closing due to inactivity

**Pull request closed without merging**
