### PR TITLE
sambanova support

### PR DESCRIPTION
**Pull request by vanuganti**
## Type

🆕 New Feature
🐛 Bug Fix
🧹 Refactoring
📖 Documentation
🚄 Infrastructure
✅ Test

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

### CODE REVIEW

**Review by ishaan-jaff — APPROVED** [review]
LGTM - is this good to merge @vanuganti ?

**Comment by ishaan-jaff** [comment]
@vanuganti   Can you send us an API Key so we can test the integration on our CI/CD pipeline ?

**Comment by vanuganti** [comment]
Can we merge with the latest API endpoint change .. let me know if you need anything else.

**Comment by vanuganti** [comment]
@ishaan-jaff

**Comment by azdolinski** [comment]
from today samba nova is available via openai api endpoint so it is possible to use it via standard configuration:

```code
### SambaNova
  - model_name: sambanova-Meta-Llama-3.1-8B-Instruct
    litellm_params:
      model: openai/Meta-Llama-3.1-8B-Instruct
      api_base: os.environ/SAMBANOVA_API_BASE
      api_key: os.environ/SAMBANOVA_API_KEY

  - model_name: sambanova-Meta-Llama-3.1-70B-Instruct
    litellm_params:
      model: openai/Meta-Llama-3.1-70B-Instruct
      api_base: os.environ/SAMBANOVA_API_BASE
      api_key: os.environ/SAMBANOVA_API_KEY

  - model_name: sambanova-Meta-Llama-3.1-405B-Instruct
    litellm_params:
      model: openai/Meta-Llama-3.1-405B-Instruct
      api_base: os.environ/SAMBANOVA_API_BASE
      api_key: os.environ/SAMBANOVA_API_KEY

```

```code
proxy:/litellm# cat .env | grep SAMBANOVA_API_BASE
SAMBANOVA_API_BASE: https://api.sambanova.ai/v1
```

**Comment by ishaan-jaff** [comment]
@vanuganti - can you fix this pr to point to https://api.sambanova.ai/v1 - happy to merge after

**Comment by vanuganti** [comment]
changes were already pushed few days back with new endpointvenuOn Sep 13, 2024, at 9:58 PM, Ishaan Jaff ***@***.***> wrote:﻿
@vanuganti - can you fix this pr to point to https://api.sambanova.ai/v1 - happy to merge after

**Pull request merged**
