### PR TITLE
protected_namespaces warning fixed for model_name & model_info

### PR DESCRIPTION
**Pull request by CyanideByte**
This is a followup to https://github.com/BerriAI/litellm/pull/2893
In litellm 1.35.25 a few more instances of this warning appeared.

```UserWarning: Field "model_name" has conflict with protected namespace "model_".```
```UserWarning: Field "model_config" has conflict with protected namespace "model_".```
```You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(```

I've resolved this warning by adding the changes to the new classes in the same manner as the previous PR.
Also added a pytest to detect this issue in the future.
EDIT: Merged _types.py from @edwinjosegeorge [PR#3340](https://github.com/BerriAI/litellm/pull/3340) - Nice finds!

### CODE REVIEW

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
Amazing  PR - @CyanideByte can you add some testing to ensure this warning never appears again ?

**Comment by CyanideByte** [comment]
> Amazing PR - @CyanideByte can you add some testing to ensure this warning never appears again ?

Thanks, I added a pytest to check if the warning happens when importing litellm.
Verified that it fails on the newest github version, but passes with my fork.

**Comment by edwinjosegeorge** [comment]
Have a look at https://github.com/BerriAI/litellm/pull/3340 that covers couple more files with possible similar warnings

**Comment by CyanideByte** [comment]
> Have a look at #3340 that covers couple more files with possible similar warnings

Nice find, I merged the _types.py cases from your PR. It looks like we both had the ones from the other 2 files.

**Comment by zheyi911** [comment]
I encountered this error

E:\python3.11\Lib\site-packages\pydantic\_internal\_fields.py:160: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
E:\python3.11\Lib\site-packages\pydantic\_internal\_fields.py:160: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

**Comment by edwinjosegeorge** [comment]
@zheyi911 This PR is not yet merged into the main branch. Could to check if you get the same results from https://github.com/CyanideByte/litellm/tree/main ? I think this PR is ready to merge

@ishaan-jaff

**Comment by ghost** [comment]
Thanks @edwinjosegeorge @CyanideByte 

LGTM!

**Comment by jtha** [comment]
Seems like this should fix the issue I've been seeing. Is this fix also reflected in the latest docker image for the proxy server? Currently using ghcr.io/berriai/litellm:main-latest and I still see this warning message resulting in container continuously restarting.

**Pull request merged**
