### PR TITLE
Add JSON mode for Gemini via Google AI Studio

### LINKED ISSUE #3365: [Feature]: Support `responseMimeType` for Gemini on AI Studio
### The Feature

Basically #2962 but for Gemini / Google AI Studio instead of Vertex AI.

```sh
curl -v \
  -H 'Content-Type: application/json' \
  -d '{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "tell me a joke in JSON"
        }
      ]
    }
  ],
  "generationConfig": {
    "responseMimeType": "application/json"
  }
}' \
  -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key=${API_KEY}"
```

### Motivation, pitch

Required for #3364 for my specific use-case.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

### PR DESCRIPTION
**Pull request by Manouchehri**
Resolves #3365.

Basically the same as #2964, but for Google AI Studio (instead of Vertex AI)

### CODE REVIEW

**Comment by ghost** [comment]
hey @Manouchehri i believe this will face the same issue as vertex ai. 

Let's try and have both moved over to httpx like anthropic.py by end of this week

**Comment by alex4o** [comment]
would you be able to support the `responseSchema` as well https://ai.google.dev/api/generate-content#v1beta.GenerationConfig?

**Comment by ghost** [comment]
@Manouchehri closing this PR as this is already live 

@alex4o just added response schema for google ai studio - https://github.com/BerriAI/litellm/commit/51211dc2a6ac5edc4e01a16a8ebc66152b4002f9

should be live by EOD 

---
@alex4o also dm'ed on linkedin to follow-up and make sure this works as expected

**Comment by alex4o** [comment]
Thanks man

**Pull request closed without merging**
