### PR TITLE
Handle bedrock tool calling in stream_chunk_builder

### LINKED ISSUE #5022: Handle bedrock tool calling in stream_chunk_builder
@krrishdholakia Sure, here you go!

```python
import litellm

model = "claude-3-5-sonnet-20240620"

system_prompt = """
You're a chatbot that answers data questions using SQL.
You have a `sql_query` tool to help you get at the data you need.
Make sure to explain to the user how you're coming up with the answer,
including the SQL.
"""

messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": "How many rows are there in the 'users' table?"},
]

tools = [
    {
        "type": "function",
        "function": {
            "name": "sql_query",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "A valid SQL query in PostgresQL format",
                    }
                },
                "required": ["query"],
            },
        },
    }
]


response = litellm.completion(model, messages, tools=tools, stream=True)
chunks = list(response)
print(chunks)

result = litellm.stream_chunk_builder(chunks)
assert result.choices[0].message.tool_calls is not None
```

_Originally posted by @jcheng5 in https://github.com/BerriAI/litellm/issues/4091#issuecomment-2265787538_

### PR DESCRIPTION
**Pull request by jcheng5**
## Title

Handle bedrock tool calling in stream_chunk_builder

## Relevant issues

Fixes #5022

## Type

🐛 Bug Fix

## Changes

The streaming chunks from Anthropic seem to violate an assumption that is implicit in the stream_chunk_builder implementation: that only tool_calls OR function_calls OR content will appear in a streamed response. The repro in #5022 shows that you can get content followed by tool calls.

These changes properly handle these combinations by building separate lists of each type of chunk (note that in theory a chunk could appear in multiple lists, e.g. both delta.tool_calls and delta.content being present on one chunk).

## [REQUIRED] Testing

```python
import dotenv
import litellm

dotenv.load_dotenv()

model = "claude-3-5-sonnet-20240620"

system_prompt = """
You're a chatbot that answers data questions using SQL.
You have a `sql_query` tool to help you get at the data you need.
Make sure to explain to the user how you're coming up with the answer,
including the SQL.
"""

messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": "How many rows are there in the 'users' table?"},
]

tools = [
    {
        "type": "function",
        "function": {
            "name": "sql_query",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "A valid SQL query in PostgresQL format",
                    }
                },
                "required": ["query"],
            },
        },
    }
]


response = litellm.completion(model, messages, tools=tools, stream=True)
chunks = list(response)

result = litellm.stream_chunk_builder(chunks)
assert result.choices[0].message.tool_calls is not None
print(result.to_json())
```
Output (note the presence of both content and tool_calls):
```
{
  "id": "chatcmpl-b263b0dc-bfec-46c7-82a5-c172272fb126",
  "choices": [
    {
      "finish_reason": "tool_calls",
      "index": 0,
      "message": {
        "content": "To answer your question about how many rows are in the 'users' table, I'll need to run a SQL query. Let me do that for you.",
        "role": "assistant",
        "tool_calls": [
          {
            "index": 0,
            "function": {
              "arguments": "",
              "name": "sql_query"
            },
            "id": "toolu_01KuqnYqdyzrEcbfXr1fE14s",
            "type": "function"
          },
          {
            "function": {
              "arguments": "{\"query\": \"SELECT COUNT(*) FROM users;\"}",
              "name": "sql_query"
            },
            "id": "toolu_01KuqnYqdyzrEcbfXr1fE14s",
            "type": "function"
          }
        ],
        "function_call": null
      }
    }
  ],
  "created": 1722628100,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion",
  "system_fingerprint": null,
  "usage": {
    "completion_tokens": 92,
    "prompt_tokens": 426,
    "total_tokens": 518
  }
}
```

### CODE REVIEW

**Comment by jcheng5** [comment]
There appears to be a second issue here--looking at the output at the end of this PR description, this:
```
        "tool_calls": [
          {
            "index": 0,
            "function": {
              "arguments": "",
              "name": "sql_query"
            },
            "id": "toolu_01KuqnYqdyzrEcbfXr1fE14s",
            "type": "function"
          },
          {
            "function": {
              "arguments": "{\"query\": \"SELECT COUNT(*) FROM users;\"}",
              "name": "sql_query"
            },
            "id": "toolu_01KuqnYqdyzrEcbfXr1fE14s",
            "type": "function"
          }
        ],
```
doesn't seem right, it looks like what was supposed to be combined into a single tool call was turned into two instead. (Note the `id` being the same, and only the first one having `index`.)

**Comment by jcheng5** [comment]
I've fixed it, the final output now looks like:

```json
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": "tool_calls",
      "index": 0,
      "message": {
        "content": "To answer your question about the number of rows in the 'users' table, I'll need to run a SQL query. Let me do that for you.",
        "role": "assistant",
        "tool_calls": [
          {
            "index": 1,
            "function": {
              "arguments": "{\"query\": \"SELECT COUNT(*) FROM users;\"}",
              "name": "sql_query"
            },
            "id": "toolu_01PUn6AKXuXwP99hvsMycubH",
            "type": "function"
          }
        ],
        "function_call": null
      }
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion",
  "system_fingerprint": null,
  "usage": {
    "completion_tokens": 92,
    "prompt_tokens": 426,
    "total_tokens": 518
  }
}
```

Super weird than Claude is returning index=1 without an index=0 coming before it, but I've verified that's what I'm getting from the API.

<details>

```json
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "To answer",
        "role": "assistant",
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " your",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " question about",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " the number of rows",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " in the '",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "users' table,",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " I'll",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " need to run",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " a SQL query.",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " Let",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " me ",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "do that for",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": " you.",
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "",
        "role": null,
        "function_call": null,
        "tool_calls": [
          {
            "id": "toolu_01PUn6AKXuXwP99hvsMycubH",
            "function": {
              "arguments": "",
              "name": "sql_query"
            },
            "type": "function",
            "index": 1
          }
        ]
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "",
        "role": null,
        "function_call": null,
        "tool_calls": [
          {
            "id": null,
            "function": {
              "arguments": "",
              "name": null
            },
            "type": "function",
            "index": 1
          }
        ]
      },
      "logprobs": null
    }
  ],
  "created": 1722629400,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "",
        "role": null,
        "function_call": null,
        "tool_calls": [
          {
            "id": null,
            "function": {
              "arguments": "{\"que",
              "name": null
            },
            "type": "function",
            "index": 1
          }
        ]
      },
      "logprobs": null
    }
  ],
  "created": 1722629401,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "",
        "role": null,
        "function_call": null,
        "tool_calls": [
          {
            "id": null,
            "function": {
              "arguments": "ry\":",
              "name": null
            },
            "type": "function",
            "index": 1
          }
        ]
      },
      "logprobs": null
    }
  ],
  "created": 1722629401,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "",
        "role": null,
        "function_call": null,
        "tool_calls": [
          {
            "id": null,
            "function": {
              "arguments": " \"SEL",
              "name": null
            },
            "type": "function",
            "index": 1
          }
        ]
      },
      "logprobs": null
    }
  ],
  "created": 1722629401,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "",
        "role": null,
        "function_call": null,
        "tool_calls": [
          {
            "id": null,
            "function": {
              "arguments": "ECT COUNT(*)",
              "name": null
            },
            "type": "function",
            "index": 1
          }
        ]
      },
      "logprobs": null
    }
  ],
  "created": 1722629401,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "",
        "role": null,
        "function_call": null,
        "tool_calls": [
          {
            "id": null,
            "function": {
              "arguments": " FROM u",
              "name": null
            },
            "type": "function",
            "index": 1
          }
        ]
      },
      "logprobs": null
    }
  ],
  "created": 1722629401,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "delta": {
        "content": "",
        "role": null,
        "function_call": null,
        "tool_calls": [
          {
            "id": null,
            "function": {
              "arguments": "sers;\"}",
              "name": null
            },
            "type": "function",
            "index": 1
          }
        ]
      },
      "logprobs": null
    }
  ],
  "created": 1722629401,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
{
  "id": "chatcmpl-176aa4e5-5a62-4aff-8102-227164ce20b1",
  "choices": [
    {
      "finish_reason": "tool_calls",
      "index": 0,
      "delta": {
        "content": null,
        "role": null,
        "function_call": null,
        "tool_calls": null
      },
      "logprobs": null
    }
  ],
  "created": 1722629401,
  "model": "claude-3-5-sonnet-20240620",
  "object": "chat.completion.chunk",
  "system_fingerprint": null
}
```

</details>

**Comment by ghost** [comment]
Hey @jcheng5 great pr. Can you add your tests here - https://github.com/BerriAI/litellm/blob/7fa25c443a328d3b3baad7cf62486d28c2378d6b/litellm/tests/test_stream_chunk_builder.py

and share a screenshot of it passing this - 

```bash
# git clone litellm 
cd litellm/litellm/tests
pytest test_stream_chunk_builder.py -x -vv
```

This will help prevent any future regressions as well

**Comment by jcheng5** [comment]
Not sure if this is in the spirit of your unit tests--I checked in `stream_chunk_testdata.py` which is the actual conversation I saw locally, rather than coding up the interaction that repros that conversation. Let me know if you'd like me to write a different type of test instead.

image

**Comment by jcheng5** [comment]
Yikes, I guess none of the existing tests cover legacy function calling :grimacing: Sorry about that!

**Pull request merged**
