### PR TITLE
fix(_redis.py): allow all supported arguments for redis cluster

### LINKED ISSUE #5552: [Bug]: cache does not support password protected Redis Clusters
### What happened?

I try to use the litellm cache in redis cluster mode. However, my cluster is protected by a password. There is no way to set the password for the `RedisCuster` client which is created by litellm:

All provided redis cluster parameter keys are filtered via the `_get_redis_cluster_kwargs()` function. It uses `inspect.getfullargspec` to retrieve the constructor arguments. However, this is not the complete list of supported arguments, as the majority of the arguments of `RedisCluster` are passed via `**kwargs`[1]. These parameters are not detected by `inspect.getfullargspec`.

With the `password` parameter, exactly this is the case and litellm filters it out before passing the rest to `RedisCluster`.

An alternative to manually building a list of supported arguments is to use `cleanup_kwargs` from `redis.cluster` directly.5

### Relevant log output

```shell
File "/app/.venv/lib/python3.12/site-packages/litellm/router.py", line 307, in __init__
    redis_cache = RedisCache(**cache_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/caching.py", line 239, in __init__
    self.redis_client = get_redis_client(**redis_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/_redis.py", line 159, in get_redis_client
    return redis.RedisCluster(startup_nodes=new_startup_nodes, **cluster_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/redis/cluster.py", line 632, in __init__
    self.nodes_manager = NodesManager(
                         ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/redis/cluster.py", line 1332, in __init__
    self.initialize()
  File "/app/.venv/lib/python3.12/site-packages/redis/cluster.py", line 1598, in initialize
    raise RedisClusterException(
redis.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node: Authentication required.
```
```


### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by Kakadus**
## Title

Support password protected redis clusters

## Relevant issues

Fixes #5552 

## Type

🐛 Bug Fix

## Changes

- use `cleanup_kwargs` instead of custom kwarg filtering

## [REQUIRED] Testing - Attach a screenshot of any new tests passing local
If UI changes, send a screenshot/GIF of working UI fixes

- adapted local test to include a password for redis cluster

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
hi @Kakadus - I tried this and it failed for me locally - I was seeing this 

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

env_overrides = {'connection_pool': BlockingConnectionPool<Connection<host=localhost,port=6379,db=0>>}, redis_kwargs = {'connection_pool': BlockingConnectionPool<Connection<host=localhost,port=6379,db=0>>}
ClusterNode = <class 'redis.cluster.ClusterNode'>, cleanup_kwargs = <function cleanup_kwargs at 0x127e78a60>, cluster_kwargs = {'connection_pool': BlockingConnectionPool<Connection<host=localhost,port=6379,db=0>>}

    def get_redis_async_client(**env_overrides):
        redis_kwargs = _get_redis_client_logic(**env_overrides)
        if "url" in redis_kwargs and redis_kwargs["url"] is not None:
            args = _get_redis_url_kwargs(client=async_redis.Redis.from_url)
            url_kwargs = {}
            for arg in redis_kwargs:
                if arg in args:
                    url_kwargs[arg] = redis_kwargs[arg]
                else:
                    litellm.print_verbose(
                        "REDIS: ignoring argument: {}. Not an allowed async_redis.Redis.from_url arg.".format(
                            arg
                        )
                    )
            return async_redis.Redis.from_url(**url_kwargs)

        if "startup_nodes" in redis_kwargs:
            from redis.cluster import ClusterNode, cleanup_kwargs

            cluster_kwargs = cleanup_kwargs(**redis_kwargs)
            print("cluster_kwargs: ", cluster_kwargs)

            new_startup_nodes: List[ClusterNode] = []

            for item in redis_kwargs["startup_nodes"]:
                new_startup_nodes.append(ClusterNode(**item))
            redis_kwargs.pop("startup_nodes")
>           return async_redis.RedisCluster(
                startup_nodes=new_startup_nodes, **cluster_kwargs
            )
E           TypeError: RedisCluster.__init__() got an unexpected keyword argument 'connection_pool'

../_redis.py:206: TypeError
------------------------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------------------------
ERROR    asyncio:base_events.py:1729 Task exception was never retrieved
future: <Task finished name='Task-2' coro=<RedisCache.ping() done, defined at /Users/ishaanjaffer/Github/litellm/litellm/caching.py:852> exception=TypeError("RedisCluster.__init__() got an unexpected keyword argument 'connection_pool'")>
Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/caching.py", line 853, in ping
    _redis_client = self.init_async_client()
  File "/Users/ishaanjaffer/Github/litellm/litellm/caching.py", line 280, in init_async_client
    return get_redis_async_client(
  File "/Users/ishaanjaffer/Github/litellm/litellm/_redis.py", line 206, in get_redis_async_client
    return async_redis.RedisCluster(
TypeError: RedisCluster.__init__() got an unexpected keyword argument 'connection_pool'
==========================================================================================
```

**Comment by ishaan-jaff** [comment]
support for setting password is done here @Kakadus https://github.com/BerriAI/litellm/pull/5579/commits/9a9c0e42eb6792478996f8b3fda5fd9b94a36fa6

**Comment by Kakadus** [comment]
I'm wondering why redis did not filter `connection_pool`... Thanks for fixing this so fast yourself!

**Comment by ishaan-jaff** [comment]
Hi @Kakadus , curious do you use LiteLLM today ? If so, I'd love to hop on a call and learn how we can improve LiteLLM for you and solve any pending issues 

- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Pull request merged**
