### PR TITLE
(fix batch_completion) method was sending the max_worker parameter to the completion method

### PR DESCRIPTION
**Pull request by josearangos**
## Relevant issues

In bash_completion the function parameters are read as follows:

image
They are then sent to the completion function, which does not have the max_workers parameter, so it fails.

image

Getting the following critical result, since the bash_completion function does not currently work
image

## Type

🐛 Bug Fix

## Changes

Just add single code line: 

image

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

### CODE REVIEW

**Comment by josearangos** [comment]
This PR, solve the next bug => https://github.com/BerriAI/litellm/issues/5973

**Comment by ghost** [comment]
Hi @josearangos can you share a screenshot of this change working as expected 

Also, could we add a new test for this, to prevent future regressions? 

https://github.com/BerriAI/litellm/blob/8995ff49ae6671192230a8a6686617ca0aaddfd4/tests/local_testing/test_batch_completions.py#L25

**Comment by ghost** [comment]
bump on this? @josearangos

**Comment by josearangos** [comment]
@krrishdholakia  I'm working on it

**Comment by josearangos** [comment]
> Hi @josearangos can you share a screenshot of this change working as expected
> 
> Also, could we add a new test for this, to prevent future regressions?
> 
> https://github.com/BerriAI/litellm/blob/8995ff49ae6671192230a8a6686617ca0aaddfd4/tests/local_testing/test_batch_completions.py#L25


@krrishdholakia  screenshot of this change working as expected
image

**Comment by josearangos** [comment]
add test to test_batch_completions.py, max_workers parameter already

**Comment by ishaan-jaff** [comment]
fixed here @josearangos  https://github.com/BerriAI/litellm/pull/6176 


closing this PR in favor of https://github.com/BerriAI/litellm/pull/6176

**Pull request closed without merging**
