### PR TITLE
[Feat] Add Semantic Caching to litellm💰

### LINKED ISSUE #1541: [Feature]: Semantic Cache Support GPTCache to OpenAI Proxy and python API
### The Feature

This enhancement aims to extend LiteLLM's support for Semantic Cache by integrating GPTCache with Redis. Currently, LiteLLM interacts with various LLM APIs. By incorporating GPTCache, we seek to optimize data retrieval and storage, specifically within the OpenAI Proxy and Python API. This technical improvement aims to enhance performance and responsiveness, providing a more efficient caching mechanism for LiteLLM users.
It's so easy to integrate it, it needs a memory vector db like Chroma config to be setup.

https://github.com/zilliztech/GPTCache

### Motivation, pitch

It's a cost saving feature, and desired in all LLM use cases.

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## Add Semantic Caching to LiteLLM 💰 
- Use with LiteLLM Proxy 
- Use with litellm.completion 

### Step 1: Add `cache` to the config.yaml
```yaml
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
  - model_name: azure-embedding-model
    litellm_params:
      model: azure/azure-embedding-model
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: "2023-07-01-preview"

litellm_settings:
  set_verbose: True
  cache: True          # set cache responses to True, litellm defaults to using a redis cache
  cache_params:
    type: "redis-semantic"  
    similarity_threshold: 0.8   # similarity threshold for semantic cache
    redis_semantic_cache_embedding_model: azure-embedding-model # set this to a model_name set in model_list
```

### Step 2: Add Redis Credentials to .env
Set either `REDIS_URL` or the `REDIS_HOST` in your os environment, to enable caching.

  ```shell
  REDIS_URL = ""        # REDIS_URL='redis://username:password@hostname:port/database'
  ## OR ## 
  REDIS_HOST = ""       # REDIS_HOST='redis-18841.c274.us-east-1-3.ec2.cloud.redislabs.com'
  REDIS_PORT = ""       # REDIS_PORT='18841'
  REDIS_PASSWORD = ""   # REDIS_PASSWORD='liteLlmIsAmazing'
  ```

**Additional kwargs**  
You can pass in any additional redis.Redis arg, by storing the variable + value in your os environment, like this: 
```shell
REDIS_<redis-kwarg-name> = ""
``` 

### Step 3: Run proxy with config
```shell
$ litellm --config /path/to/config.yaml
```

That's IT ! 

(You'll see semantic-similarity on langfuse if you set langfuse as a success_callback) 
(FYI the api key here is deleted 🔑)

Screenshot 2024-02-06 at 11 15 01 AM

## Usage with `litellm.completion`
```python
litellm.cache = Cache(
        type="redis-semantic",
        host=os.environ["REDIS_HOST"],
        port=os.environ["REDIS_PORT"],
        password=os.environ["REDIS_PASSWORD"],
        similarity_threshold=0.8,
        redis_semantic_cache_embedding_model="text-embedding-ada-002",
  )
  response1 = completion(
      model="gpt-3.5-turbo",
      messages=[
          {
              "role": "user",
              "content": f"write a one sentence poem about: {random_number}",
          }
      ],
      max_tokens=20,
  )
  print(f"response1: {response1}")

  random_number = random.randint(1, 100000)

  response2 = completion(
      model="gpt-3.5-turbo",
      messages=[
          {
              "role": "user",
              "content": f"write a one sentence poem about: {random_number}",
          }
      ],
      max_tokens=20,
  )
  print(f"response2: {response1}")
  assert response1.id == response2.id
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
merging - this passed all caching tests

**Comment by rootux** [comment]
Heartfelt thank you for this feature 🙌🏾🙌🏾

**Comment by ishaan-jaff** [comment]
@rootux are you trying to use it on the LiteLLM Proxy or on the litellm client SDK ?

**Comment by ranjancse26** [comment]
@krrishdholakia  @ishaan-jaff 

Please let me know the load testing of LiteLLM with the Redis caching aspects. To what extent it happened, how many virtual users have you considered. What's the concurrency limit? Have you considered the real workload based on the enterprise applications or products?

**Comment by ranjancse26** [comment]
@krrishdholakia  @ishaan-jaff 

Please, mark my words. The Redis caching solution is doomed for failure. Hope you guys have researched the concurrency limits and did consider the cost aspects etc. If not, please take a look at the below one, considering the customers are hosting the LiteLLM on Azure.

https://azure.microsoft.com/en-us/pricing/details/cache/

**Pull request merged**
