### PR TITLE
Bedrock llama

### PR DESCRIPTION
**Pull request by dchristian3188**
This PR adds support for meta.llama2-13b-chat-v1 via AWS Bedrock

### CODE REVIEW

**Comment by ghost** [comment]
Hey @dchristian3188 thanks for the PR - i think you're missing the json body mapping in bedrock.py - https://github.com/BerriAI/litellm/blob/548933d0bb784072d62b41f9de0871e05db3beb2/litellm/llms/bedrock.py#L307

We're awaiting llama2 access, so unable to test, fix and merge this. 

Any help would be great!

**Comment by dchristian3188** [comment]
i thought i got that on line 370 in bedrocky.py. 

Please advise if i did something wrong. 

https://github.com/BerriAI/litellm/pull/811/files

**Comment by ishaan-jaff** [comment]
@dchristian3188 
- can you help us get access to meta llama on bedrock (so we can test this) 
- this pr is missing support for enabling streaming for llama on bedrock https://github.com/BerriAI/litellm/blob/main/litellm/utils.py#L4438

**Comment by dchristian3188** [comment]
@ishaan-jaff you should be able to self request llama access. 

From the Bedrock console -> Model Access (bottom left) -> Manage Model Access -> Enable llama.

I'll also look at bedrock streaming.

**Comment by ishaan-jaff** [comment]
awesome ! if possible can you confirm that the following work locally for you with this PR @dchristian3188 
- `completion(model= meta.llama2-13b-chat-v1, messages)` 
- `completion(model= meta.llama2-13b-chat-v1, messages, stream=True)`

**Comment by ghost** [comment]
bump on this? @dchristian3188 

screenshot would work great

**Comment by dchristian3188** [comment]
Morning everybody. Added a commit to handle the streaming output. 

Let me know if it looks ok. Here's the results from my test:
Screenshot 2023-11-16 at 7 11 52 AM

**Review by ishaan-jaff — APPROVED** [review]
lgtm !

**Comment by ishaan-jaff** [comment]
amazing ! thanks for the contribution @dchristian3188

**Pull request merged**
