### PR TITLE
[WIP] Adds dynamo db support for key management

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Something went wrong, this shouldn't change more than 3-4 files.

**Comment by ghost** [comment]
This is basically the only commit that matters - https://github.com/BerriAI/litellm/commit/052374568a041e855f8bb69f4f5153747529ca1d

**Comment by ghost** [comment]
image

@ishaan-jaff can you add me to the railway project?

**Comment by ishaan-jaff** [comment]
@krrishdholakia just invited u

**Pull request merged**
