### PR TITLE
Update proxy_cli.py

### LINKED ISSUE #4324: [Bug]: The latest release broke the proxy command when specifying a config
### What happened?

Running `litellm --config my-config.yaml` blows up.  Looks like an [indentation snafu](https://github.com/BerriAI/litellm/blob/main/litellm/proxy/proxy_cli.py#L503-L511).  When fixing this a test would be a good idea ;)

### Relevant log output

```shell
File "/venv/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/litellm/proxy/proxy_cli.py", line 498, in run_server
    if key_management_settings is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'key_management_settings' where it is not associated with a value
```

### Twitter / LinkedIn details

@vanpelt

### PR DESCRIPTION
**Pull request by vanpelt**
Fixed indentation to so we don't get an `UnboundLocalError`.  Fixes #4324

## Title

Un-bork indentation

## Relevant issues

Fixes #4324

## Type

🐛 Bug Fix

## Changes

Fixe indentation

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

No testing, did this via the GH UI.

### CODE REVIEW

**Comment by ghost** [comment]
Hey @vanpelt how were you triggering this? 

Wondering how none of our testing caught it 

- do you use a secret manager today?

**Comment by ishaan-jaff** [comment]
@vanpelt - any suggestions on how we can test this code path - we have several tests on starting the proxy + using the docker image https://app.circleci.com/pipelines/github/BerriAI/litellm/11477/workflows/1b43c6d3-d33f-4828-b9c2-73815a48191a/jobs/26679 


figuring out what we can do better here

**Comment by vanpelt** [comment]
Hey guys, appreciate the enthusiasm around getting this case covered in tests.  I wasn't doing anything funky.  My use case is simply to start the proxy with a config that adds standard models like Claude or Mistral authenticated via api keys via the default environment path.

I think a simple integration test that loaded a config like the following would do it:

```yaml
model_list:
- model_name: claude-3-opus
  litellm_params:
    model: claude-3-opus-20240229
- model_name: claude-3-5-sonnet
  litellm_params:
    model: claude-3-5-sonnet-20240620
- model_name: claude-3-haiku
  litellm_params:
    model: claude-3-haiku-20240307
```

It might have been the fact that `claude-3-5-sonnet-20240620` was released today...

**Comment by ishaan-jaff** [comment]
we found the root cause - adding a test + making sure linting runs on proxy_cli.py to avoid this occurring again

**Comment by vanpelt** [comment]
For the record, I'm a big fan and am really impressed with the work you guys are doing.  Much gratitude ❤️ .  This project is making it much easier to develop AI applications and I'm looking forward to seeing it grow!  Keep up the great work 🙏

**Comment by ghost** [comment]
Thanks @vanpelt! Curious - do you use litellm proxy in production?

**Comment by vanpelt** [comment]
I'm using it in my fun side project: https://github.com/wandb/openui, it's currently in a branch.  I'm gonna release it as a native feature tomorrow.

As a founder that sells AI software, happy to meet if you want to geek out on sales motion 😜

**Pull request merged**
