### PR TITLE
Add Cohere refresh models and update pricing

### PR DESCRIPTION
**Pull request by jalammar**
## Add Cohere refresh models and update pricing
This PR adds two new Cohere models, and updates the pricing
[Cohere Command-R Refresh models](https://cohere.com/blog/command-series-0824) 
[Cohere pricing](https://cohere.com/pricing)

### CODE REVIEW

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
hi @jalammar it looks like your linting made some more changes - this makes it hard for us to review. Could you just change the fields required

**Comment by jalammar** [comment]
@ishaan-jaff Wow, thanks for the blazing fast look. Indeed I was updating it after disabling my IDE's autoformatter. Saving it as a draft now as I'd like an additional review from the Cohere side. But feel free to review and leave and feedback or suggestions.

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
Changes LGTM ! 

Can you also add this to docs: https://docs.litellm.ai/docs/providers/cohere 
file is called `cohere.md`

**Comment by jalammar** [comment]
Thank you @ishaan-jaff! Updated the docs. Also removed old models that are no longer available.

**Review by ishaan-jaff — APPROVED** [review]
lgtm

**Pull request merged**
