### PR TITLE
Update lago.py to accomodate API change

### LINKED ISSUE #5477: [Bug]: Lago Events Do Not Contain Customer ID
### What happened?

following: https://docs.litellm.ai/docs/proxy/billing, i am using `LAGO_API_CHARGE_BY` = `end_user_id`:
CleanShot 2024-09-02 at 13 09 46@2x

and i have lago configured correctly finally, and i am receiving events...

...but the received Lago event payload has null for `external_customer_id`:
```
{
  "event": {
    "transaction_id": "my-transaction-id",
    "external_customer_id": null,
    "external_subscription_id": null,
    "code": "mixtcha-test",
    "timestamp": 1725289694,
    "properties": {
      "model": "gpt-4o",
      "total_tokens": 100,
      "prompt_tokens": 17,
      "response_cost": 0.00133,
      "completion_tokens": 83
    }
  }
}
```

this is how the proxy is being called: 

```
# request sent to model set on litellm proxy, `litellm --model`
response = client.chat.completions.create(model="test-openrouter", messages = [
    {
        "role": "user",
        "content": "this is a test request, write a short poem"
    }
], user="test-myself") # 👈 whatever your customer id is

print(response.choices[0].message.content)
```

and to be very clear, the user is correctly being accounted for in the proxy, it's just not being sent to lago: 

CleanShot 2024-09-02 at 13 21 37@2x

### Relevant log output

_No response_

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by rawwerks**
external_customer_id is deprecated. 

external_subscription_id is the replacement.

closes https://github.com/BerriAI/litellm/issues/5477

## Type

🆕 New Feature
🐛 Bug Fix
🧹 Refactoring
📖 Documentation
🚄 Infrastructure
✅ Test

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
If UI changes, send a screenshot/GIF of working UI fixes

### CODE REVIEW

**Comment by ghost** [comment]
Hi @rawwerks can you share a screenshot of this working as expected. 

My understanding of this doc is that you need to pass in `external_subscription_id` in addition to `external_customer_id` 

Screenshot 2024-09-03 at 5 31 51 PM

**Comment by rawwerks** [comment]
nope, instead of, not in addition to. see the minus sign in that image of the diff?

as @jdenquin wrote here: https://github.com/BerriAI/litellm/issues/5477#issuecomment-2327684271 - this is to be used instead of. he can confirm if you don't believe me. 

look at https://docs.getlago.com/api-reference/events/usage#send-usage-event, no sign of `external_customer_id`.

read this thread: https://lago-community.slack.com/archives/C03MCH55EL8/p1725409719662939?thread_ts=1725407568.186619&cid=C03MCH55EL8

`external_customer_id` is, in @jdenquin 's words "forever null" on new lago installs. this is why i had such a hard time catching it. the field is fully deprecated.

**Comment by ghost** [comment]
Got it. Can you confirm the change works for you as expected (screenshot would be great)

**Comment by sarkissianraffi** [comment]
Lago founder here. Indeed, the external customer id is no longer supported. To ingest high volume usage and enable multiple subscriptions for the same customer, we ask our users to send the external subscription id instead. Happy to help and guide you if needed

**Comment by rawwerks** [comment]
i really need Lago to start using LiteLLM proxy in production...this is a 1 LOC change, when can we expect to be merged?

**Comment by ghost** [comment]
Hi @rawwerks merge is blocked on this 

> Got it. Can you confirm the change works for you as expected (screenshot would be great)


I should've made that clearer

**Comment by ghost** [comment]
merging to a dev branch for testing

**Comment by ghost** [comment]
will take care of pushing this pr to prod

**Comment by rawwerks** [comment]
great, thank you so much.

i have been having a lot of trouble testing this locally, because it seems to require networking two docker containers together. (which i'm not familiar with)

related: are there specific instructions for using github actions to build the litellm docker image using GitHub Packages? specifically for the lago integration (and probably other callbacks), i think it is probably better to test it out with both the litellm proxy and lago running on separate servers. 

building/publishing docker images seems fairly straightforward (https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images) - but if there are instructions specific to litellm you can provide - that would help me better contribute to the development of the proxy server. (related: https://discord.com/channels/1123360753068540065/1280869330170417243 )

**Pull request merged**
