### PR TITLE
Add Support for Custom Providers in Vision and Function Call Utils

### PR DESCRIPTION
**Pull request by ColeMurray**
## Title

Add Support for Custom Providers in Vision and Function Call Utils

## Relevant issues

https://github.com/BerriAI/litellm/issues/5608

## Type

🆕 New Feature
🐛 Bug Fix

## Changes

Modified vision check and function calling checks to support custom llm provider and to use get_model_info

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locall
no added tests

### CODE REVIEW

**Comment by ghost** [comment]
hi @ColeMurray can you add a test here - https://github.com/BerriAI/litellm/blob/cd8d7ca9156a5fc2510db1ef0d43956d3239eccf/litellm/tests/test_utils.py#L4

to confirm the fixes work as expected. 

Happy to merge once you can share a screenshot of the tests passing

**Comment by ColeMurray** [comment]
Added tests. There's some other tests that are failing within the package, potentially due to improper dev env. CI should validate.

image

**Comment by ColeMurray** [comment]
@krrishdholakia ping on this

**Comment by ColeMurray** [comment]
@krrishdholakia bumping this up

**Comment by ColeMurray** [comment]
@ishaan-jaff @krrishdholakia this PR is currently blocking and preventing expected usage around function calls and vision within litellm

**Comment by ghost** [comment]
Hey @ColeMurray thanks for the bump - reviewing now

**Comment by ghost** [comment]
Merged into today's stable dev branch. Will aim to have this out by EOD if it's fine, else will revert back with updates

**Pull request merged**
