### PR TITLE
Allowing extra headers for bedrock 

### PR DESCRIPTION
**Pull request by themrzmaster**
I really need this on my use case here. It allows me to pass extra header to the bedrock endpoint. Can me merge this? thanks

### CODE REVIEW

**Comment by ghost** [comment]
sure - but can you add a test for this in `test_completion.py` @themrzmaster

**Comment by themrzmaster** [comment]
@krrishdholakia thanks. I've added a test

**Comment by themrzmaster** [comment]
@krrishdholakia do you need something from my side? thanks

**Comment by ghost** [comment]
yup - just share a screenshot of it passing. And then we should be good to merge 🚀 

Thanks for the work on this! @themrzmaster excited to have this out on tonight's release.

**Comment by themrzmaster** [comment]
Captura de Tela 2024-05-02 às 09 44 48
@krrishdholakia sorry, forgot to post

**Comment by themrzmaster** [comment]
@krrishdholakia do you need anything more? thanks

**Comment by ghost** [comment]
missed this. thanks for the bump. LGTM!

**Pull request merged**
