### PR TITLE
little changes to better work with Pycharm and VSCode

### PR DESCRIPTION
**Pull request by shuther**

### CODE REVIEW

**Comment by shuther** [comment]
start some refactoring effort and move some configuration under json5

**Comment by ghost** [comment]
@shuther this makes a bunch of changes and i'm not sure i understand why. 

example adding a dependency for json5 


Could you explain the specific problem you faced / you're trying to tackle with this PR?

**Comment by shuther** [comment]
we could use json, but if we wanted to embed the comments you had in your code (so we don't lose them) into the .json(5) file I had to use json5. I am not concened by the performance issue (small file and only during the "boot" time. Would you want a json?

**Comment by ghost** [comment]
@shuther i guess i'm trying to understand why we'd want to change things in the first place 😄 

Understanding the issues you faced would help give me some context on this PR

**Comment by shuther** [comment]
For now, it is a bit of refactoring, I would like the configuration of the models to be outside of the code so it is easier to extend it and amend it. I am planning to use litellm as a proxy/router as one element part of a bigger picture (let's consider it will be in a docker-compose with many other compononents) and everything that is configurable (i.e. cost, rate limits, closed list of allowed llm with fallback, selection of the strategy to rotate APIkeys, ....) should be configurable (through env or file). Do you have any concern? Do you see any risk?

**Comment by shuther** [comment]
for now, I maintain my commits in a fork so we may close this PR for now (I consider it outdated), but I would like to know if you get a concern with json5 and what do you need to accept PR?

**Pull request closed without merging**
